// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/identity/v1/artifacts.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interface int32

const (
	Interface_INTERFACE_UNSPECIFIED Interface = 0
	Interface_INTERFACE_OPERATOR    Interface = 1
	Interface_INTERFACE_APPLICATION Interface = 2
)

// Enum value maps for Interface.
var (
	Interface_name = map[int32]string{
		0: "INTERFACE_UNSPECIFIED",
		1: "INTERFACE_OPERATOR",
		2: "INTERFACE_APPLICATION",
	}
	Interface_value = map[string]int32{
		"INTERFACE_UNSPECIFIED": 0,
		"INTERFACE_OPERATOR":    1,
		"INTERFACE_APPLICATION": 2,
	}
)

func (x Interface) Enum() *Interface {
	p := new(Interface)
	*p = x
	return p
}

func (x Interface) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interface) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ardents_identity_v1_artifacts_proto_enumTypes[0].Descriptor()
}

func (Interface) Type() protoreflect.EnumType {
	return &file_api_ardents_identity_v1_artifacts_proto_enumTypes[0]
}

func (x Interface) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interface.Descriptor instead.
func (Interface) EnumDescriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{0}
}

type CredentialPurpose int32

const (
	CredentialPurpose_CREDENTIAL_PURPOSE_UNSPECIFIED  CredentialPurpose = 0
	CredentialPurpose_CREDENTIAL_PURPOSE_AUTHENTICATE CredentialPurpose = 1
)

// Enum value maps for CredentialPurpose.
var (
	CredentialPurpose_name = map[int32]string{
		0: "CREDENTIAL_PURPOSE_UNSPECIFIED",
		1: "CREDENTIAL_PURPOSE_AUTHENTICATE",
	}
	CredentialPurpose_value = map[string]int32{
		"CREDENTIAL_PURPOSE_UNSPECIFIED":  0,
		"CREDENTIAL_PURPOSE_AUTHENTICATE": 1,
	}
)

func (x CredentialPurpose) Enum() *CredentialPurpose {
	p := new(CredentialPurpose)
	*p = x
	return p
}

func (x CredentialPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ardents_identity_v1_artifacts_proto_enumTypes[1].Descriptor()
}

func (CredentialPurpose) Type() protoreflect.EnumType {
	return &file_api_ardents_identity_v1_artifacts_proto_enumTypes[1]
}

func (x CredentialPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialPurpose.Descriptor instead.
func (CredentialPurpose) EnumDescriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{1}
}

type ChallengePurpose int32

const (
	ChallengePurpose_CHALLENGE_PURPOSE_UNSPECIFIED      ChallengePurpose = 0
	ChallengePurpose_CHALLENGE_PURPOSE_SESSION          ChallengePurpose = 1
	ChallengePurpose_CHALLENGE_PURPOSE_ENROLLMENT_PROOF ChallengePurpose = 2
)

// Enum value maps for ChallengePurpose.
var (
	ChallengePurpose_name = map[int32]string{
		0: "CHALLENGE_PURPOSE_UNSPECIFIED",
		1: "CHALLENGE_PURPOSE_SESSION",
		2: "CHALLENGE_PURPOSE_ENROLLMENT_PROOF",
	}
	ChallengePurpose_value = map[string]int32{
		"CHALLENGE_PURPOSE_UNSPECIFIED":      0,
		"CHALLENGE_PURPOSE_SESSION":          1,
		"CHALLENGE_PURPOSE_ENROLLMENT_PROOF": 2,
	}
)

func (x ChallengePurpose) Enum() *ChallengePurpose {
	p := new(ChallengePurpose)
	*p = x
	return p
}

func (x ChallengePurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengePurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ardents_identity_v1_artifacts_proto_enumTypes[2].Descriptor()
}

func (ChallengePurpose) Type() protoreflect.EnumType {
	return &file_api_ardents_identity_v1_artifacts_proto_enumTypes[2]
}

func (x ChallengePurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengePurpose.Descriptor instead.
func (ChallengePurpose) EnumDescriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{2}
}

type TransportProfile int32

const (
	TransportProfile_TRANSPORT_PROFILE_UNSPECIFIED   TransportProfile = 0
	TransportProfile_TRANSPORT_PROFILE_UNIX_LOCAL_V1 TransportProfile = 1
)

// Enum value maps for TransportProfile.
var (
	TransportProfile_name = map[int32]string{
		0: "TRANSPORT_PROFILE_UNSPECIFIED",
		1: "TRANSPORT_PROFILE_UNIX_LOCAL_V1",
	}
	TransportProfile_value = map[string]int32{
		"TRANSPORT_PROFILE_UNSPECIFIED":   0,
		"TRANSPORT_PROFILE_UNIX_LOCAL_V1": 1,
	}
)

func (x TransportProfile) Enum() *TransportProfile {
	p := new(TransportProfile)
	*p = x
	return p
}

func (x TransportProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ardents_identity_v1_artifacts_proto_enumTypes[3].Descriptor()
}

func (TransportProfile) Type() protoreflect.EnumType {
	return &file_api_ardents_identity_v1_artifacts_proto_enumTypes[3]
}

func (x TransportProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportProfile.Descriptor instead.
func (TransportProfile) EnumDescriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{3}
}

type Audience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Interface     Interface              `protobuf:"varint,2,opt,name=interface,proto3,enum=ardents.identity.v1.Interface" json:"interface,omitempty"`
	ProtocolMajor uint32                 `protobuf:"varint,3,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audience) Reset() {
	*x = Audience{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audience) ProtoMessage() {}

func (x *Audience) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audience.ProtoReflect.Descriptor instead.
func (*Audience) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{0}
}

func (x *Audience) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Audience) GetInterface() Interface {
	if x != nil {
		return x.Interface
	}
	return Interface_INTERFACE_UNSPECIFIED
}

func (x *Audience) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

type AuthenticationBinding struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Audience         *Audience              `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	TransportProfile TransportProfile       `protobuf:"varint,2,opt,name=transport_profile,json=transportProfile,proto3,enum=ardents.identity.v1.TransportProfile" json:"transport_profile,omitempty"`
	PeerBinding      []byte                 `protobuf:"bytes,3,opt,name=peer_binding,json=peerBinding,proto3" json:"peer_binding,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthenticationBinding) Reset() {
	*x = AuthenticationBinding{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationBinding) ProtoMessage() {}

func (x *AuthenticationBinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationBinding.ProtoReflect.Descriptor instead.
func (*AuthenticationBinding) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationBinding) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *AuthenticationBinding) GetTransportProfile() TransportProfile {
	if x != nil {
		return x.TransportProfile
	}
	return TransportProfile_TRANSPORT_PROFILE_UNSPECIFIED
}

func (x *AuthenticationBinding) GetPeerBinding() []byte {
	if x != nil {
		return x.PeerBinding
	}
	return nil
}

// ChallengeFields is the complete deterministic protobuf signed under exactly
// one purpose-specific domain. It is not an opaque server-selected payload.
type ChallengeFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Principal     string                 `protobuf:"bytes,4,opt,name=principal,proto3" json:"principal,omitempty"`
	Binding       *AuthenticationBinding `protobuf:"bytes,5,opt,name=binding,proto3" json:"binding,omitempty"`
	Purpose       ChallengePurpose       `protobuf:"varint,6,opt,name=purpose,proto3,enum=ardents.identity.v1.ChallengePurpose" json:"purpose,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeFields) Reset() {
	*x = ChallengeFields{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeFields) ProtoMessage() {}

func (x *ChallengeFields) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeFields.ProtoReflect.Descriptor instead.
func (*ChallengeFields) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeFields) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChallengeFields) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ChallengeFields) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ChallengeFields) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *ChallengeFields) GetBinding() *AuthenticationBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *ChallengeFields) GetPurpose() ChallengePurpose {
	if x != nil {
		return x.Purpose
	}
	return ChallengePurpose_CHALLENGE_PURPOSE_UNSPECIFIED
}

func (x *ChallengeFields) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *ChallengeFields) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	CanonicalId   string                 `protobuf:"bytes,4,opt,name=canonical_id,json=canonicalId,proto3" json:"canonical_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceRef) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ResourceRef) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ResourceRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRef) GetCanonicalId() string {
	if x != nil {
		return x.CanonicalId
	}
	return ""
}

type NodeScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeScope) Reset() {
	*x = NodeScope{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScope) ProtoMessage() {}

func (x *NodeScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScope.ProtoReflect.Descriptor instead.
func (*NodeScope) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{4}
}

type PrincipalOwnedScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalOwnedScope) Reset() {
	*x = PrincipalOwnedScope{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalOwnedScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalOwnedScope) ProtoMessage() {}

func (x *PrincipalOwnedScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalOwnedScope.ProtoReflect.Descriptor instead.
func (*PrincipalOwnedScope) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{5}
}

func (x *PrincipalOwnedScope) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ExactScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceRef           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExactScope) Reset() {
	*x = ExactScope{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExactScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExactScope) ProtoMessage() {}

func (x *ExactScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExactScope.ProtoReflect.Descriptor instead.
func (*ExactScope) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{6}
}

func (x *ExactScope) GetResource() *ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ResourceScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*ResourceScope_Node
	//	*ResourceScope_PrincipalOwned
	//	*ResourceScope_Exact
	Scope         isResourceScope_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceScope) Reset() {
	*x = ResourceScope{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceScope) ProtoMessage() {}

func (x *ResourceScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceScope.ProtoReflect.Descriptor instead.
func (*ResourceScope) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceScope) GetScope() isResourceScope_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ResourceScope) GetNode() *NodeScope {
	if x != nil {
		if x, ok := x.Scope.(*ResourceScope_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *ResourceScope) GetPrincipalOwned() *PrincipalOwnedScope {
	if x != nil {
		if x, ok := x.Scope.(*ResourceScope_PrincipalOwned); ok {
			return x.PrincipalOwned
		}
	}
	return nil
}

func (x *ResourceScope) GetExact() *ExactScope {
	if x != nil {
		if x, ok := x.Scope.(*ResourceScope_Exact); ok {
			return x.Exact
		}
	}
	return nil
}

type isResourceScope_Scope interface {
	isResourceScope_Scope()
}

type ResourceScope_Node struct {
	Node *NodeScope `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type ResourceScope_PrincipalOwned struct {
	PrincipalOwned *PrincipalOwnedScope `protobuf:"bytes,2,opt,name=principal_owned,json=principalOwned,proto3,oneof"`
}

type ResourceScope_Exact struct {
	Exact *ExactScope `protobuf:"bytes,3,opt,name=exact,proto3,oneof"`
}

func (*ResourceScope_Node) isResourceScope_Scope() {}

func (*ResourceScope_PrincipalOwned) isResourceScope_Scope() {}

func (*ResourceScope_Exact) isResourceScope_Scope() {}

type KeyCredentialPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Subject         string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	RootPublicKey   []byte                 `protobuf:"bytes,3,opt,name=root_public_key,json=rootPublicKey,proto3" json:"root_public_key,omitempty"`
	DeviceId        string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey []byte                 `protobuf:"bytes,5,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	Purposes        []CredentialPurpose    `protobuf:"varint,6,rep,packed,name=purposes,proto3,enum=ardents.identity.v1.CredentialPurpose" json:"purposes,omitempty"`
	NotBefore       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyCredentialPayload) Reset() {
	*x = KeyCredentialPayload{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCredentialPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCredentialPayload) ProtoMessage() {}

func (x *KeyCredentialPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCredentialPayload.ProtoReflect.Descriptor instead.
func (*KeyCredentialPayload) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{8}
}

func (x *KeyCredentialPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyCredentialPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *KeyCredentialPayload) GetRootPublicKey() []byte {
	if x != nil {
		return x.RootPublicKey
	}
	return nil
}

func (x *KeyCredentialPayload) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KeyCredentialPayload) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *KeyCredentialPayload) GetPurposes() []CredentialPurpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

func (x *KeyCredentialPayload) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *KeyCredentialPayload) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type KeyCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *KeyCredentialPayload  `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCredential) Reset() {
	*x = KeyCredential{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCredential) ProtoMessage() {}

func (x *KeyCredential) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCredential.ProtoReflect.Descriptor instead.
func (*KeyCredential) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{9}
}

func (x *KeyCredential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyCredential) GetPayload() *KeyCredentialPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KeyCredential) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AccessGrantPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience      *Audience              `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	Actions       []string               `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Scope         *ResourceScope         `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessGrantPayload) Reset() {
	*x = AccessGrantPayload{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGrantPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGrantPayload) ProtoMessage() {}

func (x *AccessGrantPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGrantPayload.ProtoReflect.Descriptor instead.
func (*AccessGrantPayload) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{10}
}

func (x *AccessGrantPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AccessGrantPayload) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AccessGrantPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AccessGrantPayload) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *AccessGrantPayload) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AccessGrantPayload) GetScope() *ResourceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AccessGrantPayload) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *AccessGrantPayload) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type AccessGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *AccessGrantPayload    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessGrant) Reset() {
	*x = AccessGrant{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGrant) ProtoMessage() {}

func (x *AccessGrant) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGrant.ProtoReflect.Descriptor instead.
func (*AccessGrant) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{11}
}

func (x *AccessGrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessGrant) GetPayload() *AccessGrantPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AccessGrant) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DelegationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Delegator     string                 `protobuf:"bytes,2,opt,name=delegator,proto3" json:"delegator,omitempty"`
	Delegatee     string                 `protobuf:"bytes,3,opt,name=delegatee,proto3" json:"delegatee,omitempty"`
	Audience      *Audience              `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	Actions       []string               `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Scope         *ResourceScope         `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Credential    *KeyCredential         `protobuf:"bytes,9,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationPayload) Reset() {
	*x = DelegationPayload{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationPayload) ProtoMessage() {}

func (x *DelegationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationPayload.ProtoReflect.Descriptor instead.
func (*DelegationPayload) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{12}
}

func (x *DelegationPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DelegationPayload) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *DelegationPayload) GetDelegatee() string {
	if x != nil {
		return x.Delegatee
	}
	return ""
}

func (x *DelegationPayload) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *DelegationPayload) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *DelegationPayload) GetScope() *ResourceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *DelegationPayload) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *DelegationPayload) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *DelegationPayload) GetCredential() *KeyCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type Delegation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *DelegationPayload     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delegation) Reset() {
	*x = Delegation{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delegation) ProtoMessage() {}

func (x *Delegation) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delegation.ProtoReflect.Descriptor instead.
func (*Delegation) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{13}
}

func (x *Delegation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delegation) GetPayload() *DelegationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Delegation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DeviceRevocationPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TargetId       string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Issuer         string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience       *Audience              `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	RevokedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,6,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	Subject        string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceRevocationPayload) Reset() {
	*x = DeviceRevocationPayload{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRevocationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRevocationPayload) ProtoMessage() {}

func (x *DeviceRevocationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRevocationPayload.ProtoReflect.Descriptor instead.
func (*DeviceRevocationPayload) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{14}
}

func (x *DeviceRevocationPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeviceRevocationPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DeviceRevocationPayload) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *DeviceRevocationPayload) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *DeviceRevocationPayload) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *DeviceRevocationPayload) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *DeviceRevocationPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type DeviceRevocation struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *DeviceRevocationPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRevocation) Reset() {
	*x = DeviceRevocation{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRevocation) ProtoMessage() {}

func (x *DeviceRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRevocation.ProtoReflect.Descriptor instead.
func (*DeviceRevocation) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceRevocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceRevocation) GetPayload() *DeviceRevocationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeviceRevocation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AccessGrantRevocationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      *Audience              `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessGrantRevocationPayload) Reset() {
	*x = AccessGrantRevocationPayload{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGrantRevocationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGrantRevocationPayload) ProtoMessage() {}

func (x *AccessGrantRevocationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGrantRevocationPayload.ProtoReflect.Descriptor instead.
func (*AccessGrantRevocationPayload) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{16}
}

func (x *AccessGrantRevocationPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AccessGrantRevocationPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AccessGrantRevocationPayload) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AccessGrantRevocationPayload) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *AccessGrantRevocationPayload) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type AccessGrantRevocation struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *AccessGrantRevocationPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessGrantRevocation) Reset() {
	*x = AccessGrantRevocation{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGrantRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGrantRevocation) ProtoMessage() {}

func (x *AccessGrantRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGrantRevocation.ProtoReflect.Descriptor instead.
func (*AccessGrantRevocation) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{17}
}

func (x *AccessGrantRevocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessGrantRevocation) GetPayload() *AccessGrantRevocationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AccessGrantRevocation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DelegationRevocationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      *Audience              `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Delegator     string                 `protobuf:"bytes,6,opt,name=delegator,proto3" json:"delegator,omitempty"`
	Delegatee     string                 `protobuf:"bytes,7,opt,name=delegatee,proto3" json:"delegatee,omitempty"`
	Credential    *KeyCredential         `protobuf:"bytes,8,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationRevocationPayload) Reset() {
	*x = DelegationRevocationPayload{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationRevocationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationRevocationPayload) ProtoMessage() {}

func (x *DelegationRevocationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationRevocationPayload.ProtoReflect.Descriptor instead.
func (*DelegationRevocationPayload) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{18}
}

func (x *DelegationRevocationPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DelegationRevocationPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DelegationRevocationPayload) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *DelegationRevocationPayload) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *DelegationRevocationPayload) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *DelegationRevocationPayload) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *DelegationRevocationPayload) GetDelegatee() string {
	if x != nil {
		return x.Delegatee
	}
	return ""
}

func (x *DelegationRevocationPayload) GetCredential() *KeyCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type DelegationRevocation struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *DelegationRevocationPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                       `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationRevocation) Reset() {
	*x = DelegationRevocation{}
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationRevocation) ProtoMessage() {}

func (x *DelegationRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_identity_v1_artifacts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationRevocation.ProtoReflect.Descriptor instead.
func (*DelegationRevocation) Descriptor() ([]byte, []int) {
	return file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP(), []int{19}
}

func (x *DelegationRevocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DelegationRevocation) GetPayload() *DelegationRevocationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DelegationRevocation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_api_ardents_identity_v1_artifacts_proto protoreflect.FileDescriptor

const file_api_ardents_identity_v1_artifacts_proto_rawDesc = "" +
	"\n" +
	"'api/ardents/identity/v1/artifacts.proto\x12\x13ardents.identity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\bAudience\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12<\n" +
	"\tinterface\x18\x02 \x01(\x0e2\x1e.ardents.identity.v1.InterfaceR\tinterface\x12%\n" +
	"\x0eprotocol_major\x18\x03 \x01(\rR\rprotocolMajor\"\xc9\x01\n" +
	"\x15AuthenticationBinding\x129\n" +
	"\baudience\x18\x01 \x01(\v2\x1d.ardents.identity.v1.AudienceR\baudience\x12R\n" +
	"\x11transport_profile\x18\x02 \x01(\x0e2%.ardents.identity.v1.TransportProfileR\x10transportProfile\x12!\n" +
	"\fpeer_binding\x18\x03 \x01(\fR\vpeerBinding\"\xea\x02\n" +
	"\x0fChallengeFields\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tprincipal\x18\x04 \x01(\tR\tprincipal\x12D\n" +
	"\abinding\x18\x05 \x01(\v2*.ardents.identity.v1.AuthenticationBindingR\abinding\x12?\n" +
	"\apurpose\x18\x06 \x01(\x0e2%.ardents.identity.v1.ChallengePurposeR\apurpose\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"n\n" +
	"\vResourceRef\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12!\n" +
	"\fcanonical_id\x18\x04 \x01(\tR\vcanonicalId\"\v\n" +
	"\tNodeScope\"+\n" +
	"\x13PrincipalOwnedScope\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\"J\n" +
	"\n" +
	"ExactScope\x12<\n" +
	"\bresource\x18\x01 \x01(\v2 .ardents.identity.v1.ResourceRefR\bresource\"\xdc\x01\n" +
	"\rResourceScope\x124\n" +
	"\x04node\x18\x01 \x01(\v2\x1e.ardents.identity.v1.NodeScopeH\x00R\x04node\x12S\n" +
	"\x0fprincipal_owned\x18\x02 \x01(\v2(.ardents.identity.v1.PrincipalOwnedScopeH\x00R\x0eprincipalOwned\x127\n" +
	"\x05exact\x18\x03 \x01(\v2\x1f.ardents.identity.v1.ExactScopeH\x00R\x05exactB\a\n" +
	"\x05scope\"\xf3\x02\n" +
	"\x14KeyCredentialPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12&\n" +
	"\x0froot_public_key\x18\x03 \x01(\fR\rrootPublicKey\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x05 \x01(\fR\x0fdevicePublicKey\x12B\n" +
	"\bpurposes\x18\x06 \x03(\x0e2&.ardents.identity.v1.CredentialPurposeR\bpurposes\x129\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"\x82\x01\n" +
	"\rKeyCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\apayload\x18\x02 \x01(\v2).ardents.identity.v1.KeyCredentialPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xe3\x02\n" +
	"\x12AccessGrantPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x129\n" +
	"\baudience\x18\x04 \x01(\v2\x1d.ardents.identity.v1.AudienceR\baudience\x12\x18\n" +
	"\aactions\x18\x05 \x03(\tR\aactions\x128\n" +
	"\x05scope\x18\x06 \x01(\v2\".ardents.identity.v1.ResourceScopeR\x05scope\x129\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"~\n" +
	"\vAccessGrant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\apayload\x18\x02 \x01(\v2'.ardents.identity.v1.AccessGrantPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xb0\x03\n" +
	"\x11DelegationPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\tdelegator\x18\x02 \x01(\tR\tdelegator\x12\x1c\n" +
	"\tdelegatee\x18\x03 \x01(\tR\tdelegatee\x129\n" +
	"\baudience\x18\x04 \x01(\v2\x1d.ardents.identity.v1.AudienceR\baudience\x12\x18\n" +
	"\aactions\x18\x05 \x03(\tR\aactions\x128\n" +
	"\x05scope\x18\x06 \x01(\v2\".ardents.identity.v1.ResourceScopeR\x05scope\x129\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12B\n" +
	"\n" +
	"credential\x18\t \x01(\v2\".ardents.identity.v1.KeyCredentialR\n" +
	"credential\"|\n" +
	"\n" +
	"Delegation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\apayload\x18\x02 \x01(\v2&.ardents.identity.v1.DelegationPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xa2\x02\n" +
	"\x17DeviceRevocationPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x129\n" +
	"\baudience\x18\x04 \x01(\v2\x1d.ardents.identity.v1.AudienceR\baudience\x129\n" +
	"\n" +
	"revoked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12(\n" +
	"\x10target_device_id\x18\x06 \x01(\tR\x0etargetDeviceId\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\"\x88\x01\n" +
	"\x10DeviceRevocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\apayload\x18\x02 \x01(\v2,.ardents.identity.v1.DeviceRevocationPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xe3\x01\n" +
	"\x1cAccessGrantRevocationPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x129\n" +
	"\baudience\x18\x04 \x01(\v2\x1d.ardents.identity.v1.AudienceR\baudience\x129\n" +
	"\n" +
	"revoked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\x92\x01\n" +
	"\x15AccessGrantRevocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\apayload\x18\x02 \x01(\v21.ardents.identity.v1.AccessGrantRevocationPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xe2\x02\n" +
	"\x1bDelegationRevocationPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x129\n" +
	"\baudience\x18\x04 \x01(\v2\x1d.ardents.identity.v1.AudienceR\baudience\x129\n" +
	"\n" +
	"revoked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x1c\n" +
	"\tdelegator\x18\x06 \x01(\tR\tdelegator\x12\x1c\n" +
	"\tdelegatee\x18\a \x01(\tR\tdelegatee\x12B\n" +
	"\n" +
	"credential\x18\b \x01(\v2\".ardents.identity.v1.KeyCredentialR\n" +
	"credential\"\x90\x01\n" +
	"\x14DelegationRevocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12J\n" +
	"\apayload\x18\x02 \x01(\v20.ardents.identity.v1.DelegationRevocationPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature*Y\n" +
	"\tInterface\x12\x19\n" +
	"\x15INTERFACE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INTERFACE_OPERATOR\x10\x01\x12\x19\n" +
	"\x15INTERFACE_APPLICATION\x10\x02*\\\n" +
	"\x11CredentialPurpose\x12\"\n" +
	"\x1eCREDENTIAL_PURPOSE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCREDENTIAL_PURPOSE_AUTHENTICATE\x10\x01*|\n" +
	"\x10ChallengePurpose\x12!\n" +
	"\x1dCHALLENGE_PURPOSE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CHALLENGE_PURPOSE_SESSION\x10\x01\x12&\n" +
	"\"CHALLENGE_PURPOSE_ENROLLMENT_PROOF\x10\x02*Z\n" +
	"\x10TransportProfile\x12!\n" +
	"\x1dTRANSPORT_PROFILE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fTRANSPORT_PROFILE_UNIX_LOCAL_V1\x10\x01B$Z\"ardents/internal/identity/protocolb\x06proto3"

var (
	file_api_ardents_identity_v1_artifacts_proto_rawDescOnce sync.Once
	file_api_ardents_identity_v1_artifacts_proto_rawDescData []byte
)

func file_api_ardents_identity_v1_artifacts_proto_rawDescGZIP() []byte {
	file_api_ardents_identity_v1_artifacts_proto_rawDescOnce.Do(func() {
		file_api_ardents_identity_v1_artifacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_identity_v1_artifacts_proto_rawDesc), len(file_api_ardents_identity_v1_artifacts_proto_rawDesc)))
	})
	return file_api_ardents_identity_v1_artifacts_proto_rawDescData
}

var file_api_ardents_identity_v1_artifacts_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_ardents_identity_v1_artifacts_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_ardents_identity_v1_artifacts_proto_goTypes = []any{
	(Interface)(0),                       // 0: ardents.identity.v1.Interface
	(CredentialPurpose)(0),               // 1: ardents.identity.v1.CredentialPurpose
	(ChallengePurpose)(0),                // 2: ardents.identity.v1.ChallengePurpose
	(TransportProfile)(0),                // 3: ardents.identity.v1.TransportProfile
	(*Audience)(nil),                     // 4: ardents.identity.v1.Audience
	(*AuthenticationBinding)(nil),        // 5: ardents.identity.v1.AuthenticationBinding
	(*ChallengeFields)(nil),              // 6: ardents.identity.v1.ChallengeFields
	(*ResourceRef)(nil),                  // 7: ardents.identity.v1.ResourceRef
	(*NodeScope)(nil),                    // 8: ardents.identity.v1.NodeScope
	(*PrincipalOwnedScope)(nil),          // 9: ardents.identity.v1.PrincipalOwnedScope
	(*ExactScope)(nil),                   // 10: ardents.identity.v1.ExactScope
	(*ResourceScope)(nil),                // 11: ardents.identity.v1.ResourceScope
	(*KeyCredentialPayload)(nil),         // 12: ardents.identity.v1.KeyCredentialPayload
	(*KeyCredential)(nil),                // 13: ardents.identity.v1.KeyCredential
	(*AccessGrantPayload)(nil),           // 14: ardents.identity.v1.AccessGrantPayload
	(*AccessGrant)(nil),                  // 15: ardents.identity.v1.AccessGrant
	(*DelegationPayload)(nil),            // 16: ardents.identity.v1.DelegationPayload
	(*Delegation)(nil),                   // 17: ardents.identity.v1.Delegation
	(*DeviceRevocationPayload)(nil),      // 18: ardents.identity.v1.DeviceRevocationPayload
	(*DeviceRevocation)(nil),             // 19: ardents.identity.v1.DeviceRevocation
	(*AccessGrantRevocationPayload)(nil), // 20: ardents.identity.v1.AccessGrantRevocationPayload
	(*AccessGrantRevocation)(nil),        // 21: ardents.identity.v1.AccessGrantRevocation
	(*DelegationRevocationPayload)(nil),  // 22: ardents.identity.v1.DelegationRevocationPayload
	(*DelegationRevocation)(nil),         // 23: ardents.identity.v1.DelegationRevocation
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
}
var file_api_ardents_identity_v1_artifacts_proto_depIdxs = []int32{
	0,  // 0: ardents.identity.v1.Audience.interface:type_name -> ardents.identity.v1.Interface
	4,  // 1: ardents.identity.v1.AuthenticationBinding.audience:type_name -> ardents.identity.v1.Audience
	3,  // 2: ardents.identity.v1.AuthenticationBinding.transport_profile:type_name -> ardents.identity.v1.TransportProfile
	5,  // 3: ardents.identity.v1.ChallengeFields.binding:type_name -> ardents.identity.v1.AuthenticationBinding
	2,  // 4: ardents.identity.v1.ChallengeFields.purpose:type_name -> ardents.identity.v1.ChallengePurpose
	24, // 5: ardents.identity.v1.ChallengeFields.issued_at:type_name -> google.protobuf.Timestamp
	24, // 6: ardents.identity.v1.ChallengeFields.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 7: ardents.identity.v1.ExactScope.resource:type_name -> ardents.identity.v1.ResourceRef
	8,  // 8: ardents.identity.v1.ResourceScope.node:type_name -> ardents.identity.v1.NodeScope
	9,  // 9: ardents.identity.v1.ResourceScope.principal_owned:type_name -> ardents.identity.v1.PrincipalOwnedScope
	10, // 10: ardents.identity.v1.ResourceScope.exact:type_name -> ardents.identity.v1.ExactScope
	1,  // 11: ardents.identity.v1.KeyCredentialPayload.purposes:type_name -> ardents.identity.v1.CredentialPurpose
	24, // 12: ardents.identity.v1.KeyCredentialPayload.not_before:type_name -> google.protobuf.Timestamp
	24, // 13: ardents.identity.v1.KeyCredentialPayload.not_after:type_name -> google.protobuf.Timestamp
	12, // 14: ardents.identity.v1.KeyCredential.payload:type_name -> ardents.identity.v1.KeyCredentialPayload
	4,  // 15: ardents.identity.v1.AccessGrantPayload.audience:type_name -> ardents.identity.v1.Audience
	11, // 16: ardents.identity.v1.AccessGrantPayload.scope:type_name -> ardents.identity.v1.ResourceScope
	24, // 17: ardents.identity.v1.AccessGrantPayload.not_before:type_name -> google.protobuf.Timestamp
	24, // 18: ardents.identity.v1.AccessGrantPayload.not_after:type_name -> google.protobuf.Timestamp
	14, // 19: ardents.identity.v1.AccessGrant.payload:type_name -> ardents.identity.v1.AccessGrantPayload
	4,  // 20: ardents.identity.v1.DelegationPayload.audience:type_name -> ardents.identity.v1.Audience
	11, // 21: ardents.identity.v1.DelegationPayload.scope:type_name -> ardents.identity.v1.ResourceScope
	24, // 22: ardents.identity.v1.DelegationPayload.not_before:type_name -> google.protobuf.Timestamp
	24, // 23: ardents.identity.v1.DelegationPayload.not_after:type_name -> google.protobuf.Timestamp
	13, // 24: ardents.identity.v1.DelegationPayload.credential:type_name -> ardents.identity.v1.KeyCredential
	16, // 25: ardents.identity.v1.Delegation.payload:type_name -> ardents.identity.v1.DelegationPayload
	4,  // 26: ardents.identity.v1.DeviceRevocationPayload.audience:type_name -> ardents.identity.v1.Audience
	24, // 27: ardents.identity.v1.DeviceRevocationPayload.revoked_at:type_name -> google.protobuf.Timestamp
	18, // 28: ardents.identity.v1.DeviceRevocation.payload:type_name -> ardents.identity.v1.DeviceRevocationPayload
	4,  // 29: ardents.identity.v1.AccessGrantRevocationPayload.audience:type_name -> ardents.identity.v1.Audience
	24, // 30: ardents.identity.v1.AccessGrantRevocationPayload.revoked_at:type_name -> google.protobuf.Timestamp
	20, // 31: ardents.identity.v1.AccessGrantRevocation.payload:type_name -> ardents.identity.v1.AccessGrantRevocationPayload
	4,  // 32: ardents.identity.v1.DelegationRevocationPayload.audience:type_name -> ardents.identity.v1.Audience
	24, // 33: ardents.identity.v1.DelegationRevocationPayload.revoked_at:type_name -> google.protobuf.Timestamp
	13, // 34: ardents.identity.v1.DelegationRevocationPayload.credential:type_name -> ardents.identity.v1.KeyCredential
	22, // 35: ardents.identity.v1.DelegationRevocation.payload:type_name -> ardents.identity.v1.DelegationRevocationPayload
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_api_ardents_identity_v1_artifacts_proto_init() }
func file_api_ardents_identity_v1_artifacts_proto_init() {
	if File_api_ardents_identity_v1_artifacts_proto != nil {
		return
	}
	file_api_ardents_identity_v1_artifacts_proto_msgTypes[7].OneofWrappers = []any{
		(*ResourceScope_Node)(nil),
		(*ResourceScope_PrincipalOwned)(nil),
		(*ResourceScope_Exact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_identity_v1_artifacts_proto_rawDesc), len(file_api_ardents_identity_v1_artifacts_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ardents_identity_v1_artifacts_proto_goTypes,
		DependencyIndexes: file_api_ardents_identity_v1_artifacts_proto_depIdxs,
		EnumInfos:         file_api_ardents_identity_v1_artifacts_proto_enumTypes,
		MessageInfos:      file_api_ardents_identity_v1_artifacts_proto_msgTypes,
	}.Build()
	File_api_ardents_identity_v1_artifacts_proto = out.File
	file_api_ardents_identity_v1_artifacts_proto_goTypes = nil
	file_api_ardents_identity_v1_artifacts_proto_depIdxs = nil
}
