// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/application/v1/common.proto

package applicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED        ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT   ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHENTICATED    ErrorCode = 2
	ErrorCode_ERROR_CODE_FORBIDDEN          ErrorCode = 3
	ErrorCode_ERROR_CODE_NOT_FOUND          ErrorCode = 4
	ErrorCode_ERROR_CODE_CONFLICT           ErrorCode = 5
	ErrorCode_ERROR_CODE_UNAVAILABLE        ErrorCode = 6
	ErrorCode_ERROR_CODE_INTEGRITY_FAILED   ErrorCode = 7
	ErrorCode_ERROR_CODE_INTERNAL           ErrorCode = 8
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED ErrorCode = 9
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_UNAUTHENTICATED",
		3: "ERROR_CODE_FORBIDDEN",
		4: "ERROR_CODE_NOT_FOUND",
		5: "ERROR_CODE_CONFLICT",
		6: "ERROR_CODE_UNAVAILABLE",
		7: "ERROR_CODE_INTEGRITY_FAILED",
		8: "ERROR_CODE_INTERNAL",
		9: "ERROR_CODE_RESOURCE_EXHAUSTED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":        0,
		"ERROR_CODE_INVALID_ARGUMENT":   1,
		"ERROR_CODE_UNAUTHENTICATED":    2,
		"ERROR_CODE_FORBIDDEN":          3,
		"ERROR_CODE_NOT_FOUND":          4,
		"ERROR_CODE_CONFLICT":           5,
		"ERROR_CODE_UNAVAILABLE":        6,
		"ERROR_CODE_INTEGRITY_FAILED":   7,
		"ERROR_CODE_INTERNAL":           8,
		"ERROR_CODE_RESOURCE_EXHAUSTED": 9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ardents_application_v1_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_ardents_application_v1_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_common_proto_rawDescGZIP(), []int{0}
}

type ApplicationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=ardents.application.v1.ErrorCode" json:"code,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationError) Reset() {
	*x = ApplicationError{}
	mi := &file_api_ardents_application_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationError) ProtoMessage() {}

func (x *ApplicationError) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationError.ProtoReflect.Descriptor instead.
func (*ApplicationError) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ApplicationError) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ApplicationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplicationError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ApplicationError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_ardents_application_v1_common_proto protoreflect.FileDescriptor

const file_api_ardents_application_v1_common_proto_rawDesc = "" +
	"\n" +
	"'api/ardents/application/v1/common.proto\x12\x16ardents.application.v1\"\xac\x02\n" +
	"\x10ApplicationError\x125\n" +
	"\x04code\x18\x01 \x01(\x0e2!.ardents.application.v1.ErrorCodeR\x04code\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12O\n" +
	"\adetails\x18\x05 \x03(\v25.ardents.application.v1.ApplicationError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xae\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x05\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x06\x12\x1f\n" +
	"\x1bERROR_CODE_INTEGRITY_FAILED\x10\a\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\b\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\tB5Z3ardents/sdk/go/protocol/applicationv1;applicationv1b\x06proto3"

var (
	file_api_ardents_application_v1_common_proto_rawDescOnce sync.Once
	file_api_ardents_application_v1_common_proto_rawDescData []byte
)

func file_api_ardents_application_v1_common_proto_rawDescGZIP() []byte {
	file_api_ardents_application_v1_common_proto_rawDescOnce.Do(func() {
		file_api_ardents_application_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_common_proto_rawDesc), len(file_api_ardents_application_v1_common_proto_rawDesc)))
	})
	return file_api_ardents_application_v1_common_proto_rawDescData
}

var file_api_ardents_application_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ardents_application_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ardents_application_v1_common_proto_goTypes = []any{
	(ErrorCode)(0),           // 0: ardents.application.v1.ErrorCode
	(*ApplicationError)(nil), // 1: ardents.application.v1.ApplicationError
	nil,                      // 2: ardents.application.v1.ApplicationError.DetailsEntry
}
var file_api_ardents_application_v1_common_proto_depIdxs = []int32{
	0, // 0: ardents.application.v1.ApplicationError.code:type_name -> ardents.application.v1.ErrorCode
	2, // 1: ardents.application.v1.ApplicationError.details:type_name -> ardents.application.v1.ApplicationError.DetailsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ardents_application_v1_common_proto_init() }
func file_api_ardents_application_v1_common_proto_init() {
	if File_api_ardents_application_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_common_proto_rawDesc), len(file_api_ardents_application_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ardents_application_v1_common_proto_goTypes,
		DependencyIndexes: file_api_ardents_application_v1_common_proto_depIdxs,
		EnumInfos:         file_api_ardents_application_v1_common_proto_enumTypes,
		MessageInfos:      file_api_ardents_application_v1_common_proto_msgTypes,
	}.Build()
	File_api_ardents_application_v1_common_proto = out.File
	file_api_ardents_application_v1_common_proto_goTypes = nil
	file_api_ardents_application_v1_common_proto_depIdxs = nil
}
