// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/application/v1/content.proto

package applicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentReference) Reset() {
	*x = ContentReference{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentReference) ProtoMessage() {}

func (x *ContentReference) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentReference.ProtoReflect.Descriptor instead.
func (*ContentReference) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PutContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentRequest) Reset() {
	*x = PutContentRequest{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentRequest) ProtoMessage() {}

func (x *PutContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentRequest.ProtoReflect.Descriptor instead.
func (*PutContentRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *PutContentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutContentRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type PutContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     *ContentReference      `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentResponse) Reset() {
	*x = PutContentResponse{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentResponse) ProtoMessage() {}

func (x *PutContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentResponse.ProtoReflect.Descriptor instead.
func (*PutContentResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *PutContentResponse) GetReference() *ContentReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *PutContentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutContentResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     *ContentReference      `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentRequest) GetReference() *ContentReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetContentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetContentResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

var File_api_ardents_application_v1_content_proto protoreflect.FileDescriptor

const file_api_ardents_application_v1_content_proto_rawDesc = "" +
	"\n" +
	"(api/ardents/application/v1/content.proto\x12\x16ardents.application.v1\"6\n" +
	"\x10ContentReference\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"L\n" +
	"\x11PutContentRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\"\x8f\x01\n" +
	"\x12PutContentResponse\x12F\n" +
	"\treference\x18\x01 \x01(\v2(.ardents.application.v1.ContentReferenceR\treference\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"[\n" +
	"\x11GetContentRequest\x12F\n" +
	"\treference\x18\x01 \x01(\v2(.ardents.application.v1.ContentReferenceR\treference\"a\n" +
	"\x12GetContentResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType2\xcc\x01\n" +
	"\x0eContentService\x12\\\n" +
	"\x03Put\x12).ardents.application.v1.PutContentRequest\x1a*.ardents.application.v1.PutContentResponse\x12\\\n" +
	"\x03Get\x12).ardents.application.v1.GetContentRequest\x1a*.ardents.application.v1.GetContentResponseB5Z3ardents/sdk/go/protocol/applicationv1;applicationv1b\x06proto3"

var (
	file_api_ardents_application_v1_content_proto_rawDescOnce sync.Once
	file_api_ardents_application_v1_content_proto_rawDescData []byte
)

func file_api_ardents_application_v1_content_proto_rawDescGZIP() []byte {
	file_api_ardents_application_v1_content_proto_rawDescOnce.Do(func() {
		file_api_ardents_application_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_content_proto_rawDesc), len(file_api_ardents_application_v1_content_proto_rawDesc)))
	})
	return file_api_ardents_application_v1_content_proto_rawDescData
}

var file_api_ardents_application_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_ardents_application_v1_content_proto_goTypes = []any{
	(*ContentReference)(nil),   // 0: ardents.application.v1.ContentReference
	(*PutContentRequest)(nil),  // 1: ardents.application.v1.PutContentRequest
	(*PutContentResponse)(nil), // 2: ardents.application.v1.PutContentResponse
	(*GetContentRequest)(nil),  // 3: ardents.application.v1.GetContentRequest
	(*GetContentResponse)(nil), // 4: ardents.application.v1.GetContentResponse
}
var file_api_ardents_application_v1_content_proto_depIdxs = []int32{
	0, // 0: ardents.application.v1.PutContentResponse.reference:type_name -> ardents.application.v1.ContentReference
	0, // 1: ardents.application.v1.GetContentRequest.reference:type_name -> ardents.application.v1.ContentReference
	1, // 2: ardents.application.v1.ContentService.Put:input_type -> ardents.application.v1.PutContentRequest
	3, // 3: ardents.application.v1.ContentService.Get:input_type -> ardents.application.v1.GetContentRequest
	2, // 4: ardents.application.v1.ContentService.Put:output_type -> ardents.application.v1.PutContentResponse
	4, // 5: ardents.application.v1.ContentService.Get:output_type -> ardents.application.v1.GetContentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ardents_application_v1_content_proto_init() }
func file_api_ardents_application_v1_content_proto_init() {
	if File_api_ardents_application_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_content_proto_rawDesc), len(file_api_ardents_application_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_application_v1_content_proto_goTypes,
		DependencyIndexes: file_api_ardents_application_v1_content_proto_depIdxs,
		MessageInfos:      file_api_ardents_application_v1_content_proto_msgTypes,
	}.Build()
	File_api_ardents_application_v1_content_proto = out.File
	file_api_ardents_application_v1_content_proto_goTypes = nil
	file_api_ardents_application_v1_content_proto_depIdxs = nil
}
