// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/application/v1/content.proto

package applicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED        ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT   ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHENTICATED    ErrorCode = 2
	ErrorCode_ERROR_CODE_FORBIDDEN          ErrorCode = 3
	ErrorCode_ERROR_CODE_NOT_FOUND          ErrorCode = 4
	ErrorCode_ERROR_CODE_CONFLICT           ErrorCode = 5
	ErrorCode_ERROR_CODE_UNAVAILABLE        ErrorCode = 6
	ErrorCode_ERROR_CODE_INTEGRITY_FAILED   ErrorCode = 7
	ErrorCode_ERROR_CODE_INTERNAL           ErrorCode = 8
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED ErrorCode = 9
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_UNAUTHENTICATED",
		3: "ERROR_CODE_FORBIDDEN",
		4: "ERROR_CODE_NOT_FOUND",
		5: "ERROR_CODE_CONFLICT",
		6: "ERROR_CODE_UNAVAILABLE",
		7: "ERROR_CODE_INTEGRITY_FAILED",
		8: "ERROR_CODE_INTERNAL",
		9: "ERROR_CODE_RESOURCE_EXHAUSTED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":        0,
		"ERROR_CODE_INVALID_ARGUMENT":   1,
		"ERROR_CODE_UNAUTHENTICATED":    2,
		"ERROR_CODE_FORBIDDEN":          3,
		"ERROR_CODE_NOT_FOUND":          4,
		"ERROR_CODE_CONFLICT":           5,
		"ERROR_CODE_UNAVAILABLE":        6,
		"ERROR_CODE_INTEGRITY_FAILED":   7,
		"ERROR_CODE_INTERNAL":           8,
		"ERROR_CODE_RESOURCE_EXHAUSTED": 9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ardents_application_v1_content_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_ardents_application_v1_content_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{0}
}

type ContentReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentReference) Reset() {
	*x = ContentReference{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentReference) ProtoMessage() {}

func (x *ContentReference) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentReference.ProtoReflect.Descriptor instead.
func (*ContentReference) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PutContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentRequest) Reset() {
	*x = PutContentRequest{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentRequest) ProtoMessage() {}

func (x *PutContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentRequest.ProtoReflect.Descriptor instead.
func (*PutContentRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *PutContentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutContentRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type PutContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     *ContentReference      `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentResponse) Reset() {
	*x = PutContentResponse{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentResponse) ProtoMessage() {}

func (x *PutContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentResponse.ProtoReflect.Descriptor instead.
func (*PutContentResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *PutContentResponse) GetReference() *ContentReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *PutContentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutContentResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     *ContentReference      `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentRequest) GetReference() *ContentReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetContentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetContentResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type ApplicationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=ardents.application.v1.ErrorCode" json:"code,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationError) Reset() {
	*x = ApplicationError{}
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationError) ProtoMessage() {}

func (x *ApplicationError) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationError.ProtoReflect.Descriptor instead.
func (*ApplicationError) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *ApplicationError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ApplicationError) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ApplicationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplicationError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ApplicationError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_ardents_application_v1_content_proto protoreflect.FileDescriptor

const file_api_ardents_application_v1_content_proto_rawDesc = "" +
	"\n" +
	"(api/ardents/application/v1/content.proto\x12\x16ardents.application.v1\"6\n" +
	"\x10ContentReference\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"L\n" +
	"\x11PutContentRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\"\x8f\x01\n" +
	"\x12PutContentResponse\x12F\n" +
	"\treference\x18\x01 \x01(\v2(.ardents.application.v1.ContentReferenceR\treference\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"[\n" +
	"\x11GetContentRequest\x12F\n" +
	"\treference\x18\x01 \x01(\v2(.ardents.application.v1.ContentReferenceR\treference\"a\n" +
	"\x12GetContentResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"\xac\x02\n" +
	"\x10ApplicationError\x125\n" +
	"\x04code\x18\x01 \x01(\x0e2!.ardents.application.v1.ErrorCodeR\x04code\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12O\n" +
	"\adetails\x18\x05 \x03(\v25.ardents.application.v1.ApplicationError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xae\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x05\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x06\x12\x1f\n" +
	"\x1bERROR_CODE_INTEGRITY_FAILED\x10\a\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\b\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\t2\xcc\x01\n" +
	"\x0eContentService\x12\\\n" +
	"\x03Put\x12).ardents.application.v1.PutContentRequest\x1a*.ardents.application.v1.PutContentResponse\x12\\\n" +
	"\x03Get\x12).ardents.application.v1.GetContentRequest\x1a*.ardents.application.v1.GetContentResponseB5Z3ardents/sdk/go/protocol/applicationv1;applicationv1b\x06proto3"

var (
	file_api_ardents_application_v1_content_proto_rawDescOnce sync.Once
	file_api_ardents_application_v1_content_proto_rawDescData []byte
)

func file_api_ardents_application_v1_content_proto_rawDescGZIP() []byte {
	file_api_ardents_application_v1_content_proto_rawDescOnce.Do(func() {
		file_api_ardents_application_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_content_proto_rawDesc), len(file_api_ardents_application_v1_content_proto_rawDesc)))
	})
	return file_api_ardents_application_v1_content_proto_rawDescData
}

var file_api_ardents_application_v1_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ardents_application_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_ardents_application_v1_content_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: ardents.application.v1.ErrorCode
	(*ContentReference)(nil),   // 1: ardents.application.v1.ContentReference
	(*PutContentRequest)(nil),  // 2: ardents.application.v1.PutContentRequest
	(*PutContentResponse)(nil), // 3: ardents.application.v1.PutContentResponse
	(*GetContentRequest)(nil),  // 4: ardents.application.v1.GetContentRequest
	(*GetContentResponse)(nil), // 5: ardents.application.v1.GetContentResponse
	(*ApplicationError)(nil),   // 6: ardents.application.v1.ApplicationError
	nil,                        // 7: ardents.application.v1.ApplicationError.DetailsEntry
}
var file_api_ardents_application_v1_content_proto_depIdxs = []int32{
	1, // 0: ardents.application.v1.PutContentResponse.reference:type_name -> ardents.application.v1.ContentReference
	1, // 1: ardents.application.v1.GetContentRequest.reference:type_name -> ardents.application.v1.ContentReference
	0, // 2: ardents.application.v1.ApplicationError.code:type_name -> ardents.application.v1.ErrorCode
	7, // 3: ardents.application.v1.ApplicationError.details:type_name -> ardents.application.v1.ApplicationError.DetailsEntry
	2, // 4: ardents.application.v1.ContentService.Put:input_type -> ardents.application.v1.PutContentRequest
	4, // 5: ardents.application.v1.ContentService.Get:input_type -> ardents.application.v1.GetContentRequest
	3, // 6: ardents.application.v1.ContentService.Put:output_type -> ardents.application.v1.PutContentResponse
	5, // 7: ardents.application.v1.ContentService.Get:output_type -> ardents.application.v1.GetContentResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ardents_application_v1_content_proto_init() }
func file_api_ardents_application_v1_content_proto_init() {
	if File_api_ardents_application_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_content_proto_rawDesc), len(file_api_ardents_application_v1_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_application_v1_content_proto_goTypes,
		DependencyIndexes: file_api_ardents_application_v1_content_proto_depIdxs,
		EnumInfos:         file_api_ardents_application_v1_content_proto_enumTypes,
		MessageInfos:      file_api_ardents_application_v1_content_proto_msgTypes,
	}.Build()
	File_api_ardents_application_v1_content_proto = out.File
	file_api_ardents_application_v1_content_proto_goTypes = nil
	file_api_ardents_application_v1_content_proto_depIdxs = nil
}
