// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/application/v1/discovery.proto

package applicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveServiceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceType     string                 `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	AcceptedSchemes []string               `protobuf:"bytes,2,rep,name=accepted_schemes,json=acceptedSchemes,proto3" json:"accepted_schemes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveServiceRequest) Reset() {
	*x = ResolveServiceRequest{}
	mi := &file_api_ardents_application_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceRequest) ProtoMessage() {}

func (x *ResolveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceRequest.ProtoReflect.Descriptor instead.
func (*ResolveServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveServiceRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ResolveServiceRequest) GetAcceptedSchemes() []string {
	if x != nil {
		return x.AcceptedSchemes
	}
	return nil
}

type ResolvedServiceTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Scheme        string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedServiceTarget) Reset() {
	*x = ResolvedServiceTarget{}
	mi := &file_api_ardents_application_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedServiceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedServiceTarget) ProtoMessage() {}

func (x *ResolvedServiceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedServiceTarget.ProtoReflect.Descriptor instead.
func (*ResolvedServiceTarget) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvedServiceTarget) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ResolvedServiceTarget) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ResolvedServiceTarget) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

type ResolveServiceResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Targets       []*ResolvedServiceTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveServiceResponse) Reset() {
	*x = ResolveServiceResponse{}
	mi := &file_api_ardents_application_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceResponse) ProtoMessage() {}

func (x *ResolveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceResponse.ProtoReflect.Descriptor instead.
func (*ResolveServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveServiceResponse) GetTargets() []*ResolvedServiceTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_api_ardents_application_v1_discovery_proto protoreflect.FileDescriptor

const file_api_ardents_application_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"*api/ardents/application/v1/discovery.proto\x12\x16ardents.application.v1\"e\n" +
	"\x15ResolveServiceRequest\x12!\n" +
	"\fservice_type\x18\x01 \x01(\tR\vserviceType\x12)\n" +
	"\x10accepted_schemes\x18\x02 \x03(\tR\x0facceptedSchemes\"j\n" +
	"\x15ResolvedServiceTarget\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\"a\n" +
	"\x16ResolveServiceResponse\x12G\n" +
	"\atargets\x18\x01 \x03(\v2-.ardents.application.v1.ResolvedServiceTargetR\atargets2|\n" +
	"\x10DiscoveryService\x12h\n" +
	"\aResolve\x12-.ardents.application.v1.ResolveServiceRequest\x1a..ardents.application.v1.ResolveServiceResponseB5Z3ardents/sdk/go/protocol/applicationv1;applicationv1b\x06proto3"

var (
	file_api_ardents_application_v1_discovery_proto_rawDescOnce sync.Once
	file_api_ardents_application_v1_discovery_proto_rawDescData []byte
)

func file_api_ardents_application_v1_discovery_proto_rawDescGZIP() []byte {
	file_api_ardents_application_v1_discovery_proto_rawDescOnce.Do(func() {
		file_api_ardents_application_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_discovery_proto_rawDesc), len(file_api_ardents_application_v1_discovery_proto_rawDesc)))
	})
	return file_api_ardents_application_v1_discovery_proto_rawDescData
}

var file_api_ardents_application_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_ardents_application_v1_discovery_proto_goTypes = []any{
	(*ResolveServiceRequest)(nil),  // 0: ardents.application.v1.ResolveServiceRequest
	(*ResolvedServiceTarget)(nil),  // 1: ardents.application.v1.ResolvedServiceTarget
	(*ResolveServiceResponse)(nil), // 2: ardents.application.v1.ResolveServiceResponse
}
var file_api_ardents_application_v1_discovery_proto_depIdxs = []int32{
	1, // 0: ardents.application.v1.ResolveServiceResponse.targets:type_name -> ardents.application.v1.ResolvedServiceTarget
	0, // 1: ardents.application.v1.DiscoveryService.Resolve:input_type -> ardents.application.v1.ResolveServiceRequest
	2, // 2: ardents.application.v1.DiscoveryService.Resolve:output_type -> ardents.application.v1.ResolveServiceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ardents_application_v1_discovery_proto_init() }
func file_api_ardents_application_v1_discovery_proto_init() {
	if File_api_ardents_application_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_discovery_proto_rawDesc), len(file_api_ardents_application_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_application_v1_discovery_proto_goTypes,
		DependencyIndexes: file_api_ardents_application_v1_discovery_proto_depIdxs,
		MessageInfos:      file_api_ardents_application_v1_discovery_proto_msgTypes,
	}.Build()
	File_api_ardents_application_v1_discovery_proto = out.File
	file_api_ardents_application_v1_discovery_proto_goTypes = nil
	file_api_ardents_application_v1_discovery_proto_depIdxs = nil
}
