// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/application/v1/identity.proto

package applicationv1

import (
	identityv1 "ardents/sdk/go/protocol/identityv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginAuthenticationRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	PrincipalId   string                      `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Purpose       identityv1.ChallengePurpose `protobuf:"varint,2,opt,name=purpose,proto3,enum=ardents.identity.v1.ChallengePurpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthenticationRequest) Reset() {
	*x = BeginAuthenticationRequest{}
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthenticationRequest) ProtoMessage() {}

func (x *BeginAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*BeginAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *BeginAuthenticationRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *BeginAuthenticationRequest) GetPurpose() identityv1.ChallengePurpose {
	if x != nil {
		return x.Purpose
	}
	return identityv1.ChallengePurpose(0)
}

type BeginAuthenticationResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Challenge     *identityv1.ChallengeFields `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthenticationResponse) Reset() {
	*x = BeginAuthenticationResponse{}
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthenticationResponse) ProtoMessage() {}

func (x *BeginAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*BeginAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *BeginAuthenticationResponse) GetChallenge() *identityv1.ChallengeFields {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type CompleteAuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	RootPublicKey []byte                 `protobuf:"bytes,3,opt,name=root_public_key,json=rootPublicKey,proto3" json:"root_public_key,omitempty"`
	Credential    []byte                 `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthenticationRequest) Reset() {
	*x = CompleteAuthenticationRequest{}
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthenticationRequest) ProtoMessage() {}

func (x *CompleteAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*CompleteAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteAuthenticationRequest) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *CompleteAuthenticationRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *CompleteAuthenticationRequest) GetRootPublicKey() []byte {
	if x != nil {
		return x.RootPublicKey
	}
	return nil
}

func (x *CompleteAuthenticationRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CompleteAuthenticationRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CompleteAuthenticationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionSecret   []byte                 `protobuf:"bytes,1,opt,name=session_secret,json=sessionSecret,proto3" json:"session_secret,omitempty"`
	EnrollmentProof []byte                 `protobuf:"bytes,2,opt,name=enrollment_proof,json=enrollmentProof,proto3" json:"enrollment_proof,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteAuthenticationResponse) Reset() {
	*x = CompleteAuthenticationResponse{}
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthenticationResponse) ProtoMessage() {}

func (x *CompleteAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*CompleteAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteAuthenticationResponse) GetSessionSecret() []byte {
	if x != nil {
		return x.SessionSecret
	}
	return nil
}

func (x *CompleteAuthenticationResponse) GetEnrollmentProof() []byte {
	if x != nil {
		return x.EnrollmentProof
	}
	return nil
}

func (x *CompleteAuthenticationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteAuthenticationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type EnrollApplicationRequest struct {
	state                       protoimpl.MessageState      `protogen:"open.v1"`
	ApplicationEnrollmentTicket []byte                      `protobuf:"bytes,1,opt,name=application_enrollment_ticket,json=applicationEnrollmentTicket,proto3" json:"application_enrollment_ticket,omitempty"`
	Challenge                   *identityv1.ChallengeFields `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	EnrollmentProof             []byte                      `protobuf:"bytes,3,opt,name=enrollment_proof,json=enrollmentProof,proto3" json:"enrollment_proof,omitempty"`
	RootPublicKey               []byte                      `protobuf:"bytes,4,opt,name=root_public_key,json=rootPublicKey,proto3" json:"root_public_key,omitempty"`
	Credential                  []byte                      `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EnrollApplicationRequest) Reset() {
	*x = EnrollApplicationRequest{}
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollApplicationRequest) ProtoMessage() {}

func (x *EnrollApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollApplicationRequest.ProtoReflect.Descriptor instead.
func (*EnrollApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollApplicationRequest) GetApplicationEnrollmentTicket() []byte {
	if x != nil {
		return x.ApplicationEnrollmentTicket
	}
	return nil
}

func (x *EnrollApplicationRequest) GetChallenge() *identityv1.ChallengeFields {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *EnrollApplicationRequest) GetEnrollmentProof() []byte {
	if x != nil {
		return x.EnrollmentProof
	}
	return nil
}

func (x *EnrollApplicationRequest) GetRootPublicKey() []byte {
	if x != nil {
		return x.RootPublicKey
	}
	return nil
}

func (x *EnrollApplicationRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type EnrollApplicationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId    string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	CredentialId   string                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	GrantId        string                 `protobuf:"bytes,3,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	GrantExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=grant_expires_at,json=grantExpiresAt,proto3" json:"grant_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrollApplicationResponse) Reset() {
	*x = EnrollApplicationResponse{}
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollApplicationResponse) ProtoMessage() {}

func (x *EnrollApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_application_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollApplicationResponse.ProtoReflect.Descriptor instead.
func (*EnrollApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_application_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollApplicationResponse) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *EnrollApplicationResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *EnrollApplicationResponse) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *EnrollApplicationResponse) GetGrantExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantExpiresAt
	}
	return nil
}

var File_api_ardents_application_v1_identity_proto protoreflect.FileDescriptor

const file_api_ardents_application_v1_identity_proto_rawDesc = "" +
	"\n" +
	")api/ardents/application/v1/identity.proto\x12\x16ardents.application.v1\x1a'api/ardents/identity/v1/artifacts.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x1aBeginAuthenticationRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12?\n" +
	"\apurpose\x18\x02 \x01(\x0e2%.ardents.identity.v1.ChallengePurposeR\apurpose\"a\n" +
	"\x1bBeginAuthenticationResponse\x12B\n" +
	"\tchallenge\x18\x01 \x01(\v2$.ardents.identity.v1.ChallengeFieldsR\tchallenge\"\xcb\x01\n" +
	"\x1dCompleteAuthenticationRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12&\n" +
	"\x0froot_public_key\x18\x03 \x01(\fR\rrootPublicKey\x12\x1e\n" +
	"\n" +
	"credential\x18\x04 \x01(\fR\n" +
	"credential\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xcc\x01\n" +
	"\x1eCompleteAuthenticationResponse\x12%\n" +
	"\x0esession_secret\x18\x01 \x01(\fR\rsessionSecret\x12)\n" +
	"\x10enrollment_proof\x18\x02 \x01(\fR\x0fenrollmentProof\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x95\x02\n" +
	"\x18EnrollApplicationRequest\x12B\n" +
	"\x1dapplication_enrollment_ticket\x18\x01 \x01(\fR\x1bapplicationEnrollmentTicket\x12B\n" +
	"\tchallenge\x18\x02 \x01(\v2$.ardents.identity.v1.ChallengeFieldsR\tchallenge\x12)\n" +
	"\x10enrollment_proof\x18\x03 \x01(\fR\x0fenrollmentProof\x12&\n" +
	"\x0froot_public_key\x18\x04 \x01(\fR\rrootPublicKey\x12\x1e\n" +
	"\n" +
	"credential\x18\x05 \x01(\fR\n" +
	"credential\"\xc4\x01\n" +
	"\x19EnrollApplicationResponse\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12\x19\n" +
	"\bgrant_id\x18\x03 \x01(\tR\agrantId\x12D\n" +
	"\x10grant_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0egrantExpiresAt2\x95\x03\n" +
	"\x0fIdentityService\x12~\n" +
	"\x13BeginAuthentication\x122.ardents.application.v1.BeginAuthenticationRequest\x1a3.ardents.application.v1.BeginAuthenticationResponse\x12\x87\x01\n" +
	"\x16CompleteAuthentication\x125.ardents.application.v1.CompleteAuthenticationRequest\x1a6.ardents.application.v1.CompleteAuthenticationResponse\x12x\n" +
	"\x11EnrollApplication\x120.ardents.application.v1.EnrollApplicationRequest\x1a1.ardents.application.v1.EnrollApplicationResponseB5Z3ardents/sdk/go/protocol/applicationv1;applicationv1b\x06proto3"

var (
	file_api_ardents_application_v1_identity_proto_rawDescOnce sync.Once
	file_api_ardents_application_v1_identity_proto_rawDescData []byte
)

func file_api_ardents_application_v1_identity_proto_rawDescGZIP() []byte {
	file_api_ardents_application_v1_identity_proto_rawDescOnce.Do(func() {
		file_api_ardents_application_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_identity_proto_rawDesc), len(file_api_ardents_application_v1_identity_proto_rawDesc)))
	})
	return file_api_ardents_application_v1_identity_proto_rawDescData
}

var file_api_ardents_application_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_ardents_application_v1_identity_proto_goTypes = []any{
	(*BeginAuthenticationRequest)(nil),     // 0: ardents.application.v1.BeginAuthenticationRequest
	(*BeginAuthenticationResponse)(nil),    // 1: ardents.application.v1.BeginAuthenticationResponse
	(*CompleteAuthenticationRequest)(nil),  // 2: ardents.application.v1.CompleteAuthenticationRequest
	(*CompleteAuthenticationResponse)(nil), // 3: ardents.application.v1.CompleteAuthenticationResponse
	(*EnrollApplicationRequest)(nil),       // 4: ardents.application.v1.EnrollApplicationRequest
	(*EnrollApplicationResponse)(nil),      // 5: ardents.application.v1.EnrollApplicationResponse
	(identityv1.ChallengePurpose)(0),       // 6: ardents.identity.v1.ChallengePurpose
	(*identityv1.ChallengeFields)(nil),     // 7: ardents.identity.v1.ChallengeFields
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_api_ardents_application_v1_identity_proto_depIdxs = []int32{
	6, // 0: ardents.application.v1.BeginAuthenticationRequest.purpose:type_name -> ardents.identity.v1.ChallengePurpose
	7, // 1: ardents.application.v1.BeginAuthenticationResponse.challenge:type_name -> ardents.identity.v1.ChallengeFields
	8, // 2: ardents.application.v1.CompleteAuthenticationResponse.expires_at:type_name -> google.protobuf.Timestamp
	7, // 3: ardents.application.v1.EnrollApplicationRequest.challenge:type_name -> ardents.identity.v1.ChallengeFields
	8, // 4: ardents.application.v1.EnrollApplicationResponse.grant_expires_at:type_name -> google.protobuf.Timestamp
	0, // 5: ardents.application.v1.IdentityService.BeginAuthentication:input_type -> ardents.application.v1.BeginAuthenticationRequest
	2, // 6: ardents.application.v1.IdentityService.CompleteAuthentication:input_type -> ardents.application.v1.CompleteAuthenticationRequest
	4, // 7: ardents.application.v1.IdentityService.EnrollApplication:input_type -> ardents.application.v1.EnrollApplicationRequest
	1, // 8: ardents.application.v1.IdentityService.BeginAuthentication:output_type -> ardents.application.v1.BeginAuthenticationResponse
	3, // 9: ardents.application.v1.IdentityService.CompleteAuthentication:output_type -> ardents.application.v1.CompleteAuthenticationResponse
	5, // 10: ardents.application.v1.IdentityService.EnrollApplication:output_type -> ardents.application.v1.EnrollApplicationResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_ardents_application_v1_identity_proto_init() }
func file_api_ardents_application_v1_identity_proto_init() {
	if File_api_ardents_application_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_application_v1_identity_proto_rawDesc), len(file_api_ardents_application_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_application_v1_identity_proto_goTypes,
		DependencyIndexes: file_api_ardents_application_v1_identity_proto_depIdxs,
		MessageInfos:      file_api_ardents_application_v1_identity_proto_msgTypes,
	}.Build()
	File_api_ardents_application_v1_identity_proto = out.File
	file_api_ardents_application_v1_identity_proto_goTypes = nil
	file_api_ardents_application_v1_identity_proto_depIdxs = nil
}
