// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/authority.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthorityServiceName is the fully-qualified name of the AuthorityService service.
	AuthorityServiceName = "ardents.v1.AuthorityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthorityServiceCreateRealmAuthorityProcedure is the fully-qualified name of the
	// AuthorityService's CreateRealmAuthority RPC.
	AuthorityServiceCreateRealmAuthorityProcedure = "/ardents.v1.AuthorityService/CreateRealmAuthority"
	// AuthorityServiceInspectRealmAuthorityProcedure is the fully-qualified name of the
	// AuthorityService's InspectRealmAuthority RPC.
	AuthorityServiceInspectRealmAuthorityProcedure = "/ardents.v1.AuthorityService/InspectRealmAuthority"
)

// AuthorityServiceClient is a client for the ardents.v1.AuthorityService service.
type AuthorityServiceClient interface {
	CreateRealmAuthority(context.Context, *connect.Request[protocol.CreateRealmAuthorityRequest]) (*connect.Response[protocol.CreateRealmAuthorityResponse], error)
	InspectRealmAuthority(context.Context, *connect.Request[protocol.InspectRealmAuthorityRequest]) (*connect.Response[protocol.InspectRealmAuthorityResponse], error)
}

// NewAuthorityServiceClient constructs a client for the ardents.v1.AuthorityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthorityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthorityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authorityServiceMethods := protocol.File_api_ardents_v1_authority_proto.Services().ByName("AuthorityService").Methods()
	return &authorityServiceClient{
		createRealmAuthority: connect.NewClient[protocol.CreateRealmAuthorityRequest, protocol.CreateRealmAuthorityResponse](
			httpClient,
			baseURL+AuthorityServiceCreateRealmAuthorityProcedure,
			connect.WithSchema(authorityServiceMethods.ByName("CreateRealmAuthority")),
			connect.WithClientOptions(opts...),
		),
		inspectRealmAuthority: connect.NewClient[protocol.InspectRealmAuthorityRequest, protocol.InspectRealmAuthorityResponse](
			httpClient,
			baseURL+AuthorityServiceInspectRealmAuthorityProcedure,
			connect.WithSchema(authorityServiceMethods.ByName("InspectRealmAuthority")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authorityServiceClient implements AuthorityServiceClient.
type authorityServiceClient struct {
	createRealmAuthority  *connect.Client[protocol.CreateRealmAuthorityRequest, protocol.CreateRealmAuthorityResponse]
	inspectRealmAuthority *connect.Client[protocol.InspectRealmAuthorityRequest, protocol.InspectRealmAuthorityResponse]
}

// CreateRealmAuthority calls ardents.v1.AuthorityService.CreateRealmAuthority.
func (c *authorityServiceClient) CreateRealmAuthority(ctx context.Context, req *connect.Request[protocol.CreateRealmAuthorityRequest]) (*connect.Response[protocol.CreateRealmAuthorityResponse], error) {
	return c.createRealmAuthority.CallUnary(ctx, req)
}

// InspectRealmAuthority calls ardents.v1.AuthorityService.InspectRealmAuthority.
func (c *authorityServiceClient) InspectRealmAuthority(ctx context.Context, req *connect.Request[protocol.InspectRealmAuthorityRequest]) (*connect.Response[protocol.InspectRealmAuthorityResponse], error) {
	return c.inspectRealmAuthority.CallUnary(ctx, req)
}

// AuthorityServiceHandler is an implementation of the ardents.v1.AuthorityService service.
type AuthorityServiceHandler interface {
	CreateRealmAuthority(context.Context, *connect.Request[protocol.CreateRealmAuthorityRequest]) (*connect.Response[protocol.CreateRealmAuthorityResponse], error)
	InspectRealmAuthority(context.Context, *connect.Request[protocol.InspectRealmAuthorityRequest]) (*connect.Response[protocol.InspectRealmAuthorityResponse], error)
}

// NewAuthorityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthorityServiceHandler(svc AuthorityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authorityServiceMethods := protocol.File_api_ardents_v1_authority_proto.Services().ByName("AuthorityService").Methods()
	authorityServiceCreateRealmAuthorityHandler := connect.NewUnaryHandler(
		AuthorityServiceCreateRealmAuthorityProcedure,
		svc.CreateRealmAuthority,
		connect.WithSchema(authorityServiceMethods.ByName("CreateRealmAuthority")),
		connect.WithHandlerOptions(opts...),
	)
	authorityServiceInspectRealmAuthorityHandler := connect.NewUnaryHandler(
		AuthorityServiceInspectRealmAuthorityProcedure,
		svc.InspectRealmAuthority,
		connect.WithSchema(authorityServiceMethods.ByName("InspectRealmAuthority")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.AuthorityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthorityServiceCreateRealmAuthorityProcedure:
			authorityServiceCreateRealmAuthorityHandler.ServeHTTP(w, r)
		case AuthorityServiceInspectRealmAuthorityProcedure:
			authorityServiceInspectRealmAuthorityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthorityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthorityServiceHandler struct{}

func (UnimplementedAuthorityServiceHandler) CreateRealmAuthority(context.Context, *connect.Request[protocol.CreateRealmAuthorityRequest]) (*connect.Response[protocol.CreateRealmAuthorityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.AuthorityService.CreateRealmAuthority is not implemented"))
}

func (UnimplementedAuthorityServiceHandler) InspectRealmAuthority(context.Context, *connect.Request[protocol.InspectRealmAuthorityRequest]) (*connect.Response[protocol.InspectRealmAuthorityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.AuthorityService.InspectRealmAuthority is not implemented"))
}
