// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/configuration.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigurationServiceName is the fully-qualified name of the ConfigurationService service.
	ConfigurationServiceName = "ardents.v1.ConfigurationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigurationServiceGetEffectiveConfigurationProcedure is the fully-qualified name of the
	// ConfigurationService's GetEffectiveConfiguration RPC.
	ConfigurationServiceGetEffectiveConfigurationProcedure = "/ardents.v1.ConfigurationService/GetEffectiveConfiguration"
	// ConfigurationServiceReloadConfigurationProcedure is the fully-qualified name of the
	// ConfigurationService's ReloadConfiguration RPC.
	ConfigurationServiceReloadConfigurationProcedure = "/ardents.v1.ConfigurationService/ReloadConfiguration"
)

// ConfigurationServiceClient is a client for the ardents.v1.ConfigurationService service.
type ConfigurationServiceClient interface {
	GetEffectiveConfiguration(context.Context, *connect.Request[protocol.GetEffectiveConfigurationRequest]) (*connect.Response[protocol.EffectiveConfigurationResponse], error)
	ReloadConfiguration(context.Context, *connect.Request[protocol.ReloadConfigurationRequest]) (*connect.Response[protocol.ReloadConfigurationResponse], error)
}

// NewConfigurationServiceClient constructs a client for the ardents.v1.ConfigurationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigurationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigurationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configurationServiceMethods := protocol.File_api_ardents_v1_configuration_proto.Services().ByName("ConfigurationService").Methods()
	return &configurationServiceClient{
		getEffectiveConfiguration: connect.NewClient[protocol.GetEffectiveConfigurationRequest, protocol.EffectiveConfigurationResponse](
			httpClient,
			baseURL+ConfigurationServiceGetEffectiveConfigurationProcedure,
			connect.WithSchema(configurationServiceMethods.ByName("GetEffectiveConfiguration")),
			connect.WithClientOptions(opts...),
		),
		reloadConfiguration: connect.NewClient[protocol.ReloadConfigurationRequest, protocol.ReloadConfigurationResponse](
			httpClient,
			baseURL+ConfigurationServiceReloadConfigurationProcedure,
			connect.WithSchema(configurationServiceMethods.ByName("ReloadConfiguration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configurationServiceClient implements ConfigurationServiceClient.
type configurationServiceClient struct {
	getEffectiveConfiguration *connect.Client[protocol.GetEffectiveConfigurationRequest, protocol.EffectiveConfigurationResponse]
	reloadConfiguration       *connect.Client[protocol.ReloadConfigurationRequest, protocol.ReloadConfigurationResponse]
}

// GetEffectiveConfiguration calls ardents.v1.ConfigurationService.GetEffectiveConfiguration.
func (c *configurationServiceClient) GetEffectiveConfiguration(ctx context.Context, req *connect.Request[protocol.GetEffectiveConfigurationRequest]) (*connect.Response[protocol.EffectiveConfigurationResponse], error) {
	return c.getEffectiveConfiguration.CallUnary(ctx, req)
}

// ReloadConfiguration calls ardents.v1.ConfigurationService.ReloadConfiguration.
func (c *configurationServiceClient) ReloadConfiguration(ctx context.Context, req *connect.Request[protocol.ReloadConfigurationRequest]) (*connect.Response[protocol.ReloadConfigurationResponse], error) {
	return c.reloadConfiguration.CallUnary(ctx, req)
}

// ConfigurationServiceHandler is an implementation of the ardents.v1.ConfigurationService service.
type ConfigurationServiceHandler interface {
	GetEffectiveConfiguration(context.Context, *connect.Request[protocol.GetEffectiveConfigurationRequest]) (*connect.Response[protocol.EffectiveConfigurationResponse], error)
	ReloadConfiguration(context.Context, *connect.Request[protocol.ReloadConfigurationRequest]) (*connect.Response[protocol.ReloadConfigurationResponse], error)
}

// NewConfigurationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigurationServiceHandler(svc ConfigurationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configurationServiceMethods := protocol.File_api_ardents_v1_configuration_proto.Services().ByName("ConfigurationService").Methods()
	configurationServiceGetEffectiveConfigurationHandler := connect.NewUnaryHandler(
		ConfigurationServiceGetEffectiveConfigurationProcedure,
		svc.GetEffectiveConfiguration,
		connect.WithSchema(configurationServiceMethods.ByName("GetEffectiveConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	configurationServiceReloadConfigurationHandler := connect.NewUnaryHandler(
		ConfigurationServiceReloadConfigurationProcedure,
		svc.ReloadConfiguration,
		connect.WithSchema(configurationServiceMethods.ByName("ReloadConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.ConfigurationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigurationServiceGetEffectiveConfigurationProcedure:
			configurationServiceGetEffectiveConfigurationHandler.ServeHTTP(w, r)
		case ConfigurationServiceReloadConfigurationProcedure:
			configurationServiceReloadConfigurationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigurationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigurationServiceHandler struct{}

func (UnimplementedConfigurationServiceHandler) GetEffectiveConfiguration(context.Context, *connect.Request[protocol.GetEffectiveConfigurationRequest]) (*connect.Response[protocol.EffectiveConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ConfigurationService.GetEffectiveConfiguration is not implemented"))
}

func (UnimplementedConfigurationServiceHandler) ReloadConfiguration(context.Context, *connect.Request[protocol.ReloadConfigurationRequest]) (*connect.Response[protocol.ReloadConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ConfigurationService.ReloadConfiguration is not implemented"))
}
