// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/content.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ContentServiceName is the fully-qualified name of the ContentService service.
	ContentServiceName = "ardents.v1.ContentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ContentServicePublishObjectProcedure is the fully-qualified name of the ContentService's
	// PublishObject RPC.
	ContentServicePublishObjectProcedure = "/ardents.v1.ContentService/PublishObject"
	// ContentServiceGetObjectProcedure is the fully-qualified name of the ContentService's GetObject
	// RPC.
	ContentServiceGetObjectProcedure = "/ardents.v1.ContentService/GetObject"
	// ContentServiceListObjectsProcedure is the fully-qualified name of the ContentService's
	// ListObjects RPC.
	ContentServiceListObjectsProcedure = "/ardents.v1.ContentService/ListObjects"
	// ContentServicePublishBlobProcedure is the fully-qualified name of the ContentService's
	// PublishBlob RPC.
	ContentServicePublishBlobProcedure = "/ardents.v1.ContentService/PublishBlob"
	// ContentServiceGetBlobProcedure is the fully-qualified name of the ContentService's GetBlob RPC.
	ContentServiceGetBlobProcedure = "/ardents.v1.ContentService/GetBlob"
	// ContentServiceListBlobsProcedure is the fully-qualified name of the ContentService's ListBlobs
	// RPC.
	ContentServiceListBlobsProcedure = "/ardents.v1.ContentService/ListBlobs"
	// ContentServicePublishManifestProcedure is the fully-qualified name of the ContentService's
	// PublishManifest RPC.
	ContentServicePublishManifestProcedure = "/ardents.v1.ContentService/PublishManifest"
	// ContentServiceGetManifestProcedure is the fully-qualified name of the ContentService's
	// GetManifest RPC.
	ContentServiceGetManifestProcedure = "/ardents.v1.ContentService/GetManifest"
	// ContentServiceListManifestsProcedure is the fully-qualified name of the ContentService's
	// ListManifests RPC.
	ContentServiceListManifestsProcedure = "/ardents.v1.ContentService/ListManifests"
	// ContentServiceGetDataInventoryProcedure is the fully-qualified name of the ContentService's
	// GetDataInventory RPC.
	ContentServiceGetDataInventoryProcedure = "/ardents.v1.ContentService/GetDataInventory"
)

// ContentServiceClient is a client for the ardents.v1.ContentService service.
type ContentServiceClient interface {
	PublishObject(context.Context, *connect.Request[protocol.PublishObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error)
	GetObject(context.Context, *connect.Request[protocol.GetObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error)
	ListObjects(context.Context, *connect.Request[protocol.ListObjectsRequest]) (*connect.Response[protocol.ListObjectsResponse], error)
	PublishBlob(context.Context, *connect.Request[protocol.PublishBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	GetBlob(context.Context, *connect.Request[protocol.GetBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	ListBlobs(context.Context, *connect.Request[protocol.ListBlobsRequest]) (*connect.Response[protocol.ListBlobsResponse], error)
	PublishManifest(context.Context, *connect.Request[protocol.PublishManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error)
	GetManifest(context.Context, *connect.Request[protocol.GetManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error)
	ListManifests(context.Context, *connect.Request[protocol.ListManifestsRequest]) (*connect.Response[protocol.ListManifestsResponse], error)
	GetDataInventory(context.Context, *connect.Request[protocol.GetDataInventoryRequest]) (*connect.Response[protocol.DataInventorySnapshot], error)
}

// NewContentServiceClient constructs a client for the ardents.v1.ContentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewContentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ContentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	contentServiceMethods := protocol.File_api_ardents_v1_content_proto.Services().ByName("ContentService").Methods()
	return &contentServiceClient{
		publishObject: connect.NewClient[protocol.PublishObjectRequest, protocol.ObjectSnapshot](
			httpClient,
			baseURL+ContentServicePublishObjectProcedure,
			connect.WithSchema(contentServiceMethods.ByName("PublishObject")),
			connect.WithClientOptions(opts...),
		),
		getObject: connect.NewClient[protocol.GetObjectRequest, protocol.ObjectSnapshot](
			httpClient,
			baseURL+ContentServiceGetObjectProcedure,
			connect.WithSchema(contentServiceMethods.ByName("GetObject")),
			connect.WithClientOptions(opts...),
		),
		listObjects: connect.NewClient[protocol.ListObjectsRequest, protocol.ListObjectsResponse](
			httpClient,
			baseURL+ContentServiceListObjectsProcedure,
			connect.WithSchema(contentServiceMethods.ByName("ListObjects")),
			connect.WithClientOptions(opts...),
		),
		publishBlob: connect.NewClient[protocol.PublishBlobRequest, protocol.BlobSnapshot](
			httpClient,
			baseURL+ContentServicePublishBlobProcedure,
			connect.WithSchema(contentServiceMethods.ByName("PublishBlob")),
			connect.WithClientOptions(opts...),
		),
		getBlob: connect.NewClient[protocol.GetBlobRequest, protocol.BlobSnapshot](
			httpClient,
			baseURL+ContentServiceGetBlobProcedure,
			connect.WithSchema(contentServiceMethods.ByName("GetBlob")),
			connect.WithClientOptions(opts...),
		),
		listBlobs: connect.NewClient[protocol.ListBlobsRequest, protocol.ListBlobsResponse](
			httpClient,
			baseURL+ContentServiceListBlobsProcedure,
			connect.WithSchema(contentServiceMethods.ByName("ListBlobs")),
			connect.WithClientOptions(opts...),
		),
		publishManifest: connect.NewClient[protocol.PublishManifestRequest, protocol.ManifestSnapshot](
			httpClient,
			baseURL+ContentServicePublishManifestProcedure,
			connect.WithSchema(contentServiceMethods.ByName("PublishManifest")),
			connect.WithClientOptions(opts...),
		),
		getManifest: connect.NewClient[protocol.GetManifestRequest, protocol.ManifestSnapshot](
			httpClient,
			baseURL+ContentServiceGetManifestProcedure,
			connect.WithSchema(contentServiceMethods.ByName("GetManifest")),
			connect.WithClientOptions(opts...),
		),
		listManifests: connect.NewClient[protocol.ListManifestsRequest, protocol.ListManifestsResponse](
			httpClient,
			baseURL+ContentServiceListManifestsProcedure,
			connect.WithSchema(contentServiceMethods.ByName("ListManifests")),
			connect.WithClientOptions(opts...),
		),
		getDataInventory: connect.NewClient[protocol.GetDataInventoryRequest, protocol.DataInventorySnapshot](
			httpClient,
			baseURL+ContentServiceGetDataInventoryProcedure,
			connect.WithSchema(contentServiceMethods.ByName("GetDataInventory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// contentServiceClient implements ContentServiceClient.
type contentServiceClient struct {
	publishObject    *connect.Client[protocol.PublishObjectRequest, protocol.ObjectSnapshot]
	getObject        *connect.Client[protocol.GetObjectRequest, protocol.ObjectSnapshot]
	listObjects      *connect.Client[protocol.ListObjectsRequest, protocol.ListObjectsResponse]
	publishBlob      *connect.Client[protocol.PublishBlobRequest, protocol.BlobSnapshot]
	getBlob          *connect.Client[protocol.GetBlobRequest, protocol.BlobSnapshot]
	listBlobs        *connect.Client[protocol.ListBlobsRequest, protocol.ListBlobsResponse]
	publishManifest  *connect.Client[protocol.PublishManifestRequest, protocol.ManifestSnapshot]
	getManifest      *connect.Client[protocol.GetManifestRequest, protocol.ManifestSnapshot]
	listManifests    *connect.Client[protocol.ListManifestsRequest, protocol.ListManifestsResponse]
	getDataInventory *connect.Client[protocol.GetDataInventoryRequest, protocol.DataInventorySnapshot]
}

// PublishObject calls ardents.v1.ContentService.PublishObject.
func (c *contentServiceClient) PublishObject(ctx context.Context, req *connect.Request[protocol.PublishObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error) {
	return c.publishObject.CallUnary(ctx, req)
}

// GetObject calls ardents.v1.ContentService.GetObject.
func (c *contentServiceClient) GetObject(ctx context.Context, req *connect.Request[protocol.GetObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error) {
	return c.getObject.CallUnary(ctx, req)
}

// ListObjects calls ardents.v1.ContentService.ListObjects.
func (c *contentServiceClient) ListObjects(ctx context.Context, req *connect.Request[protocol.ListObjectsRequest]) (*connect.Response[protocol.ListObjectsResponse], error) {
	return c.listObjects.CallUnary(ctx, req)
}

// PublishBlob calls ardents.v1.ContentService.PublishBlob.
func (c *contentServiceClient) PublishBlob(ctx context.Context, req *connect.Request[protocol.PublishBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return c.publishBlob.CallUnary(ctx, req)
}

// GetBlob calls ardents.v1.ContentService.GetBlob.
func (c *contentServiceClient) GetBlob(ctx context.Context, req *connect.Request[protocol.GetBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return c.getBlob.CallUnary(ctx, req)
}

// ListBlobs calls ardents.v1.ContentService.ListBlobs.
func (c *contentServiceClient) ListBlobs(ctx context.Context, req *connect.Request[protocol.ListBlobsRequest]) (*connect.Response[protocol.ListBlobsResponse], error) {
	return c.listBlobs.CallUnary(ctx, req)
}

// PublishManifest calls ardents.v1.ContentService.PublishManifest.
func (c *contentServiceClient) PublishManifest(ctx context.Context, req *connect.Request[protocol.PublishManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error) {
	return c.publishManifest.CallUnary(ctx, req)
}

// GetManifest calls ardents.v1.ContentService.GetManifest.
func (c *contentServiceClient) GetManifest(ctx context.Context, req *connect.Request[protocol.GetManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// ListManifests calls ardents.v1.ContentService.ListManifests.
func (c *contentServiceClient) ListManifests(ctx context.Context, req *connect.Request[protocol.ListManifestsRequest]) (*connect.Response[protocol.ListManifestsResponse], error) {
	return c.listManifests.CallUnary(ctx, req)
}

// GetDataInventory calls ardents.v1.ContentService.GetDataInventory.
func (c *contentServiceClient) GetDataInventory(ctx context.Context, req *connect.Request[protocol.GetDataInventoryRequest]) (*connect.Response[protocol.DataInventorySnapshot], error) {
	return c.getDataInventory.CallUnary(ctx, req)
}

// ContentServiceHandler is an implementation of the ardents.v1.ContentService service.
type ContentServiceHandler interface {
	PublishObject(context.Context, *connect.Request[protocol.PublishObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error)
	GetObject(context.Context, *connect.Request[protocol.GetObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error)
	ListObjects(context.Context, *connect.Request[protocol.ListObjectsRequest]) (*connect.Response[protocol.ListObjectsResponse], error)
	PublishBlob(context.Context, *connect.Request[protocol.PublishBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	GetBlob(context.Context, *connect.Request[protocol.GetBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	ListBlobs(context.Context, *connect.Request[protocol.ListBlobsRequest]) (*connect.Response[protocol.ListBlobsResponse], error)
	PublishManifest(context.Context, *connect.Request[protocol.PublishManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error)
	GetManifest(context.Context, *connect.Request[protocol.GetManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error)
	ListManifests(context.Context, *connect.Request[protocol.ListManifestsRequest]) (*connect.Response[protocol.ListManifestsResponse], error)
	GetDataInventory(context.Context, *connect.Request[protocol.GetDataInventoryRequest]) (*connect.Response[protocol.DataInventorySnapshot], error)
}

// NewContentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewContentServiceHandler(svc ContentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	contentServiceMethods := protocol.File_api_ardents_v1_content_proto.Services().ByName("ContentService").Methods()
	contentServicePublishObjectHandler := connect.NewUnaryHandler(
		ContentServicePublishObjectProcedure,
		svc.PublishObject,
		connect.WithSchema(contentServiceMethods.ByName("PublishObject")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceGetObjectHandler := connect.NewUnaryHandler(
		ContentServiceGetObjectProcedure,
		svc.GetObject,
		connect.WithSchema(contentServiceMethods.ByName("GetObject")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceListObjectsHandler := connect.NewUnaryHandler(
		ContentServiceListObjectsProcedure,
		svc.ListObjects,
		connect.WithSchema(contentServiceMethods.ByName("ListObjects")),
		connect.WithHandlerOptions(opts...),
	)
	contentServicePublishBlobHandler := connect.NewUnaryHandler(
		ContentServicePublishBlobProcedure,
		svc.PublishBlob,
		connect.WithSchema(contentServiceMethods.ByName("PublishBlob")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceGetBlobHandler := connect.NewUnaryHandler(
		ContentServiceGetBlobProcedure,
		svc.GetBlob,
		connect.WithSchema(contentServiceMethods.ByName("GetBlob")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceListBlobsHandler := connect.NewUnaryHandler(
		ContentServiceListBlobsProcedure,
		svc.ListBlobs,
		connect.WithSchema(contentServiceMethods.ByName("ListBlobs")),
		connect.WithHandlerOptions(opts...),
	)
	contentServicePublishManifestHandler := connect.NewUnaryHandler(
		ContentServicePublishManifestProcedure,
		svc.PublishManifest,
		connect.WithSchema(contentServiceMethods.ByName("PublishManifest")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceGetManifestHandler := connect.NewUnaryHandler(
		ContentServiceGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(contentServiceMethods.ByName("GetManifest")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceListManifestsHandler := connect.NewUnaryHandler(
		ContentServiceListManifestsProcedure,
		svc.ListManifests,
		connect.WithSchema(contentServiceMethods.ByName("ListManifests")),
		connect.WithHandlerOptions(opts...),
	)
	contentServiceGetDataInventoryHandler := connect.NewUnaryHandler(
		ContentServiceGetDataInventoryProcedure,
		svc.GetDataInventory,
		connect.WithSchema(contentServiceMethods.ByName("GetDataInventory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.ContentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ContentServicePublishObjectProcedure:
			contentServicePublishObjectHandler.ServeHTTP(w, r)
		case ContentServiceGetObjectProcedure:
			contentServiceGetObjectHandler.ServeHTTP(w, r)
		case ContentServiceListObjectsProcedure:
			contentServiceListObjectsHandler.ServeHTTP(w, r)
		case ContentServicePublishBlobProcedure:
			contentServicePublishBlobHandler.ServeHTTP(w, r)
		case ContentServiceGetBlobProcedure:
			contentServiceGetBlobHandler.ServeHTTP(w, r)
		case ContentServiceListBlobsProcedure:
			contentServiceListBlobsHandler.ServeHTTP(w, r)
		case ContentServicePublishManifestProcedure:
			contentServicePublishManifestHandler.ServeHTTP(w, r)
		case ContentServiceGetManifestProcedure:
			contentServiceGetManifestHandler.ServeHTTP(w, r)
		case ContentServiceListManifestsProcedure:
			contentServiceListManifestsHandler.ServeHTTP(w, r)
		case ContentServiceGetDataInventoryProcedure:
			contentServiceGetDataInventoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedContentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedContentServiceHandler struct{}

func (UnimplementedContentServiceHandler) PublishObject(context.Context, *connect.Request[protocol.PublishObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.PublishObject is not implemented"))
}

func (UnimplementedContentServiceHandler) GetObject(context.Context, *connect.Request[protocol.GetObjectRequest]) (*connect.Response[protocol.ObjectSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.GetObject is not implemented"))
}

func (UnimplementedContentServiceHandler) ListObjects(context.Context, *connect.Request[protocol.ListObjectsRequest]) (*connect.Response[protocol.ListObjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.ListObjects is not implemented"))
}

func (UnimplementedContentServiceHandler) PublishBlob(context.Context, *connect.Request[protocol.PublishBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.PublishBlob is not implemented"))
}

func (UnimplementedContentServiceHandler) GetBlob(context.Context, *connect.Request[protocol.GetBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.GetBlob is not implemented"))
}

func (UnimplementedContentServiceHandler) ListBlobs(context.Context, *connect.Request[protocol.ListBlobsRequest]) (*connect.Response[protocol.ListBlobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.ListBlobs is not implemented"))
}

func (UnimplementedContentServiceHandler) PublishManifest(context.Context, *connect.Request[protocol.PublishManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.PublishManifest is not implemented"))
}

func (UnimplementedContentServiceHandler) GetManifest(context.Context, *connect.Request[protocol.GetManifestRequest]) (*connect.Response[protocol.ManifestSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.GetManifest is not implemented"))
}

func (UnimplementedContentServiceHandler) ListManifests(context.Context, *connect.Request[protocol.ListManifestsRequest]) (*connect.Response[protocol.ListManifestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.ListManifests is not implemented"))
}

func (UnimplementedContentServiceHandler) GetDataInventory(context.Context, *connect.Request[protocol.GetDataInventoryRequest]) (*connect.Response[protocol.DataInventorySnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.ContentService.GetDataInventory is not implemented"))
}
