// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/diagnostics.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DiagnosticsServiceName is the fully-qualified name of the DiagnosticsService service.
	DiagnosticsServiceName = "ardents.v1.DiagnosticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DiagnosticsServiceGetDiagnosticsProcedure is the fully-qualified name of the DiagnosticsService's
	// GetDiagnostics RPC.
	DiagnosticsServiceGetDiagnosticsProcedure = "/ardents.v1.DiagnosticsService/GetDiagnostics"
	// DiagnosticsServiceGetPendingOperationsProcedure is the fully-qualified name of the
	// DiagnosticsService's GetPendingOperations RPC.
	DiagnosticsServiceGetPendingOperationsProcedure = "/ardents.v1.DiagnosticsService/GetPendingOperations"
	// DiagnosticsServiceGetHealthSummaryProcedure is the fully-qualified name of the
	// DiagnosticsService's GetHealthSummary RPC.
	DiagnosticsServiceGetHealthSummaryProcedure = "/ardents.v1.DiagnosticsService/GetHealthSummary"
	// DiagnosticsServiceExplainFailureProcedure is the fully-qualified name of the DiagnosticsService's
	// ExplainFailure RPC.
	DiagnosticsServiceExplainFailureProcedure = "/ardents.v1.DiagnosticsService/ExplainFailure"
	// DiagnosticsServiceListRecentEventsProcedure is the fully-qualified name of the
	// DiagnosticsService's ListRecentEvents RPC.
	DiagnosticsServiceListRecentEventsProcedure = "/ardents.v1.DiagnosticsService/ListRecentEvents"
)

// DiagnosticsServiceClient is a client for the ardents.v1.DiagnosticsService service.
type DiagnosticsServiceClient interface {
	GetDiagnostics(context.Context, *connect.Request[protocol.GetDiagnosticsRequest]) (*connect.Response[protocol.DiagnosticsSnapshotResponse], error)
	GetPendingOperations(context.Context, *connect.Request[protocol.GetPendingOperationsRequest]) (*connect.Response[protocol.PendingOperationsResponse], error)
	GetHealthSummary(context.Context, *connect.Request[protocol.GetHealthSummaryRequest]) (*connect.Response[protocol.HealthSummaryResponse], error)
	ExplainFailure(context.Context, *connect.Request[protocol.ExplainFailureRequest]) (*connect.Response[protocol.FailureExplanationResponse], error)
	ListRecentEvents(context.Context, *connect.Request[protocol.ListRecentEventsRequest]) (*connect.Response[protocol.ListEventsResponse], error)
}

// NewDiagnosticsServiceClient constructs a client for the ardents.v1.DiagnosticsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDiagnosticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DiagnosticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	diagnosticsServiceMethods := protocol.File_api_ardents_v1_diagnostics_proto.Services().ByName("DiagnosticsService").Methods()
	return &diagnosticsServiceClient{
		getDiagnostics: connect.NewClient[protocol.GetDiagnosticsRequest, protocol.DiagnosticsSnapshotResponse](
			httpClient,
			baseURL+DiagnosticsServiceGetDiagnosticsProcedure,
			connect.WithSchema(diagnosticsServiceMethods.ByName("GetDiagnostics")),
			connect.WithClientOptions(opts...),
		),
		getPendingOperations: connect.NewClient[protocol.GetPendingOperationsRequest, protocol.PendingOperationsResponse](
			httpClient,
			baseURL+DiagnosticsServiceGetPendingOperationsProcedure,
			connect.WithSchema(diagnosticsServiceMethods.ByName("GetPendingOperations")),
			connect.WithClientOptions(opts...),
		),
		getHealthSummary: connect.NewClient[protocol.GetHealthSummaryRequest, protocol.HealthSummaryResponse](
			httpClient,
			baseURL+DiagnosticsServiceGetHealthSummaryProcedure,
			connect.WithSchema(diagnosticsServiceMethods.ByName("GetHealthSummary")),
			connect.WithClientOptions(opts...),
		),
		explainFailure: connect.NewClient[protocol.ExplainFailureRequest, protocol.FailureExplanationResponse](
			httpClient,
			baseURL+DiagnosticsServiceExplainFailureProcedure,
			connect.WithSchema(diagnosticsServiceMethods.ByName("ExplainFailure")),
			connect.WithClientOptions(opts...),
		),
		listRecentEvents: connect.NewClient[protocol.ListRecentEventsRequest, protocol.ListEventsResponse](
			httpClient,
			baseURL+DiagnosticsServiceListRecentEventsProcedure,
			connect.WithSchema(diagnosticsServiceMethods.ByName("ListRecentEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// diagnosticsServiceClient implements DiagnosticsServiceClient.
type diagnosticsServiceClient struct {
	getDiagnostics       *connect.Client[protocol.GetDiagnosticsRequest, protocol.DiagnosticsSnapshotResponse]
	getPendingOperations *connect.Client[protocol.GetPendingOperationsRequest, protocol.PendingOperationsResponse]
	getHealthSummary     *connect.Client[protocol.GetHealthSummaryRequest, protocol.HealthSummaryResponse]
	explainFailure       *connect.Client[protocol.ExplainFailureRequest, protocol.FailureExplanationResponse]
	listRecentEvents     *connect.Client[protocol.ListRecentEventsRequest, protocol.ListEventsResponse]
}

// GetDiagnostics calls ardents.v1.DiagnosticsService.GetDiagnostics.
func (c *diagnosticsServiceClient) GetDiagnostics(ctx context.Context, req *connect.Request[protocol.GetDiagnosticsRequest]) (*connect.Response[protocol.DiagnosticsSnapshotResponse], error) {
	return c.getDiagnostics.CallUnary(ctx, req)
}

// GetPendingOperations calls ardents.v1.DiagnosticsService.GetPendingOperations.
func (c *diagnosticsServiceClient) GetPendingOperations(ctx context.Context, req *connect.Request[protocol.GetPendingOperationsRequest]) (*connect.Response[protocol.PendingOperationsResponse], error) {
	return c.getPendingOperations.CallUnary(ctx, req)
}

// GetHealthSummary calls ardents.v1.DiagnosticsService.GetHealthSummary.
func (c *diagnosticsServiceClient) GetHealthSummary(ctx context.Context, req *connect.Request[protocol.GetHealthSummaryRequest]) (*connect.Response[protocol.HealthSummaryResponse], error) {
	return c.getHealthSummary.CallUnary(ctx, req)
}

// ExplainFailure calls ardents.v1.DiagnosticsService.ExplainFailure.
func (c *diagnosticsServiceClient) ExplainFailure(ctx context.Context, req *connect.Request[protocol.ExplainFailureRequest]) (*connect.Response[protocol.FailureExplanationResponse], error) {
	return c.explainFailure.CallUnary(ctx, req)
}

// ListRecentEvents calls ardents.v1.DiagnosticsService.ListRecentEvents.
func (c *diagnosticsServiceClient) ListRecentEvents(ctx context.Context, req *connect.Request[protocol.ListRecentEventsRequest]) (*connect.Response[protocol.ListEventsResponse], error) {
	return c.listRecentEvents.CallUnary(ctx, req)
}

// DiagnosticsServiceHandler is an implementation of the ardents.v1.DiagnosticsService service.
type DiagnosticsServiceHandler interface {
	GetDiagnostics(context.Context, *connect.Request[protocol.GetDiagnosticsRequest]) (*connect.Response[protocol.DiagnosticsSnapshotResponse], error)
	GetPendingOperations(context.Context, *connect.Request[protocol.GetPendingOperationsRequest]) (*connect.Response[protocol.PendingOperationsResponse], error)
	GetHealthSummary(context.Context, *connect.Request[protocol.GetHealthSummaryRequest]) (*connect.Response[protocol.HealthSummaryResponse], error)
	ExplainFailure(context.Context, *connect.Request[protocol.ExplainFailureRequest]) (*connect.Response[protocol.FailureExplanationResponse], error)
	ListRecentEvents(context.Context, *connect.Request[protocol.ListRecentEventsRequest]) (*connect.Response[protocol.ListEventsResponse], error)
}

// NewDiagnosticsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDiagnosticsServiceHandler(svc DiagnosticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	diagnosticsServiceMethods := protocol.File_api_ardents_v1_diagnostics_proto.Services().ByName("DiagnosticsService").Methods()
	diagnosticsServiceGetDiagnosticsHandler := connect.NewUnaryHandler(
		DiagnosticsServiceGetDiagnosticsProcedure,
		svc.GetDiagnostics,
		connect.WithSchema(diagnosticsServiceMethods.ByName("GetDiagnostics")),
		connect.WithHandlerOptions(opts...),
	)
	diagnosticsServiceGetPendingOperationsHandler := connect.NewUnaryHandler(
		DiagnosticsServiceGetPendingOperationsProcedure,
		svc.GetPendingOperations,
		connect.WithSchema(diagnosticsServiceMethods.ByName("GetPendingOperations")),
		connect.WithHandlerOptions(opts...),
	)
	diagnosticsServiceGetHealthSummaryHandler := connect.NewUnaryHandler(
		DiagnosticsServiceGetHealthSummaryProcedure,
		svc.GetHealthSummary,
		connect.WithSchema(diagnosticsServiceMethods.ByName("GetHealthSummary")),
		connect.WithHandlerOptions(opts...),
	)
	diagnosticsServiceExplainFailureHandler := connect.NewUnaryHandler(
		DiagnosticsServiceExplainFailureProcedure,
		svc.ExplainFailure,
		connect.WithSchema(diagnosticsServiceMethods.ByName("ExplainFailure")),
		connect.WithHandlerOptions(opts...),
	)
	diagnosticsServiceListRecentEventsHandler := connect.NewUnaryHandler(
		DiagnosticsServiceListRecentEventsProcedure,
		svc.ListRecentEvents,
		connect.WithSchema(diagnosticsServiceMethods.ByName("ListRecentEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.DiagnosticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DiagnosticsServiceGetDiagnosticsProcedure:
			diagnosticsServiceGetDiagnosticsHandler.ServeHTTP(w, r)
		case DiagnosticsServiceGetPendingOperationsProcedure:
			diagnosticsServiceGetPendingOperationsHandler.ServeHTTP(w, r)
		case DiagnosticsServiceGetHealthSummaryProcedure:
			diagnosticsServiceGetHealthSummaryHandler.ServeHTTP(w, r)
		case DiagnosticsServiceExplainFailureProcedure:
			diagnosticsServiceExplainFailureHandler.ServeHTTP(w, r)
		case DiagnosticsServiceListRecentEventsProcedure:
			diagnosticsServiceListRecentEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDiagnosticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDiagnosticsServiceHandler struct{}

func (UnimplementedDiagnosticsServiceHandler) GetDiagnostics(context.Context, *connect.Request[protocol.GetDiagnosticsRequest]) (*connect.Response[protocol.DiagnosticsSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.DiagnosticsService.GetDiagnostics is not implemented"))
}

func (UnimplementedDiagnosticsServiceHandler) GetPendingOperations(context.Context, *connect.Request[protocol.GetPendingOperationsRequest]) (*connect.Response[protocol.PendingOperationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.DiagnosticsService.GetPendingOperations is not implemented"))
}

func (UnimplementedDiagnosticsServiceHandler) GetHealthSummary(context.Context, *connect.Request[protocol.GetHealthSummaryRequest]) (*connect.Response[protocol.HealthSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.DiagnosticsService.GetHealthSummary is not implemented"))
}

func (UnimplementedDiagnosticsServiceHandler) ExplainFailure(context.Context, *connect.Request[protocol.ExplainFailureRequest]) (*connect.Response[protocol.FailureExplanationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.DiagnosticsService.ExplainFailure is not implemented"))
}

func (UnimplementedDiagnosticsServiceHandler) ListRecentEvents(context.Context, *connect.Request[protocol.ListRecentEventsRequest]) (*connect.Response[protocol.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.DiagnosticsService.ListRecentEvents is not implemented"))
}
