// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/identity.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "ardents.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceBeginAuthenticationProcedure is the fully-qualified name of the IdentityService's
	// BeginAuthentication RPC.
	IdentityServiceBeginAuthenticationProcedure = "/ardents.v1.IdentityService/BeginAuthentication"
	// IdentityServiceCompleteAuthenticationProcedure is the fully-qualified name of the
	// IdentityService's CompleteAuthentication RPC.
	IdentityServiceCompleteAuthenticationProcedure = "/ardents.v1.IdentityService/CompleteAuthentication"
	// IdentityServiceEnrollFirstPrincipalProcedure is the fully-qualified name of the IdentityService's
	// EnrollFirstPrincipal RPC.
	IdentityServiceEnrollFirstPrincipalProcedure = "/ardents.v1.IdentityService/EnrollFirstPrincipal"
	// IdentityServiceEnrollPrincipalProcedure is the fully-qualified name of the IdentityService's
	// EnrollPrincipal RPC.
	IdentityServiceEnrollPrincipalProcedure = "/ardents.v1.IdentityService/EnrollPrincipal"
	// IdentityServiceRevokeDeviceProcedure is the fully-qualified name of the IdentityService's
	// RevokeDevice RPC.
	IdentityServiceRevokeDeviceProcedure = "/ardents.v1.IdentityService/RevokeDevice"
	// IdentityServiceListDeviceRevocationsProcedure is the fully-qualified name of the
	// IdentityService's ListDeviceRevocations RPC.
	IdentityServiceListDeviceRevocationsProcedure = "/ardents.v1.IdentityService/ListDeviceRevocations"
	// IdentityServiceIssueAccessGrantProcedure is the fully-qualified name of the IdentityService's
	// IssueAccessGrant RPC.
	IdentityServiceIssueAccessGrantProcedure = "/ardents.v1.IdentityService/IssueAccessGrant"
	// IdentityServiceRevokeAccessGrantProcedure is the fully-qualified name of the IdentityService's
	// RevokeAccessGrant RPC.
	IdentityServiceRevokeAccessGrantProcedure = "/ardents.v1.IdentityService/RevokeAccessGrant"
	// IdentityServiceListAccessGrantsProcedure is the fully-qualified name of the IdentityService's
	// ListAccessGrants RPC.
	IdentityServiceListAccessGrantsProcedure = "/ardents.v1.IdentityService/ListAccessGrants"
	// IdentityServiceIssueApplicationEnrollmentTicketProcedure is the fully-qualified name of the
	// IdentityService's IssueApplicationEnrollmentTicket RPC.
	IdentityServiceIssueApplicationEnrollmentTicketProcedure = "/ardents.v1.IdentityService/IssueApplicationEnrollmentTicket"
	// IdentityServiceImportDelegationRevocationProcedure is the fully-qualified name of the
	// IdentityService's ImportDelegationRevocation RPC.
	IdentityServiceImportDelegationRevocationProcedure = "/ardents.v1.IdentityService/ImportDelegationRevocation"
)

// IdentityServiceClient is a client for the ardents.v1.IdentityService service.
type IdentityServiceClient interface {
	BeginAuthentication(context.Context, *connect.Request[protocol.BeginAuthenticationRequest]) (*connect.Response[protocol.BeginAuthenticationResponse], error)
	CompleteAuthentication(context.Context, *connect.Request[protocol.CompleteAuthenticationRequest]) (*connect.Response[protocol.CompleteAuthenticationResponse], error)
	EnrollFirstPrincipal(context.Context, *connect.Request[protocol.EnrollFirstPrincipalRequest]) (*connect.Response[protocol.EnrollFirstPrincipalResponse], error)
	EnrollPrincipal(context.Context, *connect.Request[protocol.EnrollPrincipalRequest]) (*connect.Response[protocol.EnrollPrincipalResponse], error)
	RevokeDevice(context.Context, *connect.Request[protocol.RevokeDeviceRequest]) (*connect.Response[protocol.RevokeDeviceResponse], error)
	ListDeviceRevocations(context.Context, *connect.Request[protocol.ListDeviceRevocationsRequest]) (*connect.Response[protocol.ListDeviceRevocationsResponse], error)
	IssueAccessGrant(context.Context, *connect.Request[protocol.IssueAccessGrantRequest]) (*connect.Response[protocol.IssueAccessGrantResponse], error)
	RevokeAccessGrant(context.Context, *connect.Request[protocol.RevokeAccessGrantRequest]) (*connect.Response[protocol.RevokeAccessGrantResponse], error)
	ListAccessGrants(context.Context, *connect.Request[protocol.ListAccessGrantsRequest]) (*connect.Response[protocol.ListAccessGrantsResponse], error)
	IssueApplicationEnrollmentTicket(context.Context, *connect.Request[protocol.IssueApplicationEnrollmentTicketRequest]) (*connect.Response[protocol.IssueApplicationEnrollmentTicketResponse], error)
	ImportDelegationRevocation(context.Context, *connect.Request[protocol.ImportDelegationRevocationRequest]) (*connect.Response[protocol.ImportDelegationRevocationResponse], error)
}

// NewIdentityServiceClient constructs a client for the ardents.v1.IdentityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := protocol.File_api_ardents_v1_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		beginAuthentication: connect.NewClient[protocol.BeginAuthenticationRequest, protocol.BeginAuthenticationResponse](
			httpClient,
			baseURL+IdentityServiceBeginAuthenticationProcedure,
			connect.WithSchema(identityServiceMethods.ByName("BeginAuthentication")),
			connect.WithClientOptions(opts...),
		),
		completeAuthentication: connect.NewClient[protocol.CompleteAuthenticationRequest, protocol.CompleteAuthenticationResponse](
			httpClient,
			baseURL+IdentityServiceCompleteAuthenticationProcedure,
			connect.WithSchema(identityServiceMethods.ByName("CompleteAuthentication")),
			connect.WithClientOptions(opts...),
		),
		enrollFirstPrincipal: connect.NewClient[protocol.EnrollFirstPrincipalRequest, protocol.EnrollFirstPrincipalResponse](
			httpClient,
			baseURL+IdentityServiceEnrollFirstPrincipalProcedure,
			connect.WithSchema(identityServiceMethods.ByName("EnrollFirstPrincipal")),
			connect.WithClientOptions(opts...),
		),
		enrollPrincipal: connect.NewClient[protocol.EnrollPrincipalRequest, protocol.EnrollPrincipalResponse](
			httpClient,
			baseURL+IdentityServiceEnrollPrincipalProcedure,
			connect.WithSchema(identityServiceMethods.ByName("EnrollPrincipal")),
			connect.WithClientOptions(opts...),
		),
		revokeDevice: connect.NewClient[protocol.RevokeDeviceRequest, protocol.RevokeDeviceResponse](
			httpClient,
			baseURL+IdentityServiceRevokeDeviceProcedure,
			connect.WithSchema(identityServiceMethods.ByName("RevokeDevice")),
			connect.WithClientOptions(opts...),
		),
		listDeviceRevocations: connect.NewClient[protocol.ListDeviceRevocationsRequest, protocol.ListDeviceRevocationsResponse](
			httpClient,
			baseURL+IdentityServiceListDeviceRevocationsProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ListDeviceRevocations")),
			connect.WithClientOptions(opts...),
		),
		issueAccessGrant: connect.NewClient[protocol.IssueAccessGrantRequest, protocol.IssueAccessGrantResponse](
			httpClient,
			baseURL+IdentityServiceIssueAccessGrantProcedure,
			connect.WithSchema(identityServiceMethods.ByName("IssueAccessGrant")),
			connect.WithClientOptions(opts...),
		),
		revokeAccessGrant: connect.NewClient[protocol.RevokeAccessGrantRequest, protocol.RevokeAccessGrantResponse](
			httpClient,
			baseURL+IdentityServiceRevokeAccessGrantProcedure,
			connect.WithSchema(identityServiceMethods.ByName("RevokeAccessGrant")),
			connect.WithClientOptions(opts...),
		),
		listAccessGrants: connect.NewClient[protocol.ListAccessGrantsRequest, protocol.ListAccessGrantsResponse](
			httpClient,
			baseURL+IdentityServiceListAccessGrantsProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ListAccessGrants")),
			connect.WithClientOptions(opts...),
		),
		issueApplicationEnrollmentTicket: connect.NewClient[protocol.IssueApplicationEnrollmentTicketRequest, protocol.IssueApplicationEnrollmentTicketResponse](
			httpClient,
			baseURL+IdentityServiceIssueApplicationEnrollmentTicketProcedure,
			connect.WithSchema(identityServiceMethods.ByName("IssueApplicationEnrollmentTicket")),
			connect.WithClientOptions(opts...),
		),
		importDelegationRevocation: connect.NewClient[protocol.ImportDelegationRevocationRequest, protocol.ImportDelegationRevocationResponse](
			httpClient,
			baseURL+IdentityServiceImportDelegationRevocationProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ImportDelegationRevocation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	beginAuthentication              *connect.Client[protocol.BeginAuthenticationRequest, protocol.BeginAuthenticationResponse]
	completeAuthentication           *connect.Client[protocol.CompleteAuthenticationRequest, protocol.CompleteAuthenticationResponse]
	enrollFirstPrincipal             *connect.Client[protocol.EnrollFirstPrincipalRequest, protocol.EnrollFirstPrincipalResponse]
	enrollPrincipal                  *connect.Client[protocol.EnrollPrincipalRequest, protocol.EnrollPrincipalResponse]
	revokeDevice                     *connect.Client[protocol.RevokeDeviceRequest, protocol.RevokeDeviceResponse]
	listDeviceRevocations            *connect.Client[protocol.ListDeviceRevocationsRequest, protocol.ListDeviceRevocationsResponse]
	issueAccessGrant                 *connect.Client[protocol.IssueAccessGrantRequest, protocol.IssueAccessGrantResponse]
	revokeAccessGrant                *connect.Client[protocol.RevokeAccessGrantRequest, protocol.RevokeAccessGrantResponse]
	listAccessGrants                 *connect.Client[protocol.ListAccessGrantsRequest, protocol.ListAccessGrantsResponse]
	issueApplicationEnrollmentTicket *connect.Client[protocol.IssueApplicationEnrollmentTicketRequest, protocol.IssueApplicationEnrollmentTicketResponse]
	importDelegationRevocation       *connect.Client[protocol.ImportDelegationRevocationRequest, protocol.ImportDelegationRevocationResponse]
}

// BeginAuthentication calls ardents.v1.IdentityService.BeginAuthentication.
func (c *identityServiceClient) BeginAuthentication(ctx context.Context, req *connect.Request[protocol.BeginAuthenticationRequest]) (*connect.Response[protocol.BeginAuthenticationResponse], error) {
	return c.beginAuthentication.CallUnary(ctx, req)
}

// CompleteAuthentication calls ardents.v1.IdentityService.CompleteAuthentication.
func (c *identityServiceClient) CompleteAuthentication(ctx context.Context, req *connect.Request[protocol.CompleteAuthenticationRequest]) (*connect.Response[protocol.CompleteAuthenticationResponse], error) {
	return c.completeAuthentication.CallUnary(ctx, req)
}

// EnrollFirstPrincipal calls ardents.v1.IdentityService.EnrollFirstPrincipal.
func (c *identityServiceClient) EnrollFirstPrincipal(ctx context.Context, req *connect.Request[protocol.EnrollFirstPrincipalRequest]) (*connect.Response[protocol.EnrollFirstPrincipalResponse], error) {
	return c.enrollFirstPrincipal.CallUnary(ctx, req)
}

// EnrollPrincipal calls ardents.v1.IdentityService.EnrollPrincipal.
func (c *identityServiceClient) EnrollPrincipal(ctx context.Context, req *connect.Request[protocol.EnrollPrincipalRequest]) (*connect.Response[protocol.EnrollPrincipalResponse], error) {
	return c.enrollPrincipal.CallUnary(ctx, req)
}

// RevokeDevice calls ardents.v1.IdentityService.RevokeDevice.
func (c *identityServiceClient) RevokeDevice(ctx context.Context, req *connect.Request[protocol.RevokeDeviceRequest]) (*connect.Response[protocol.RevokeDeviceResponse], error) {
	return c.revokeDevice.CallUnary(ctx, req)
}

// ListDeviceRevocations calls ardents.v1.IdentityService.ListDeviceRevocations.
func (c *identityServiceClient) ListDeviceRevocations(ctx context.Context, req *connect.Request[protocol.ListDeviceRevocationsRequest]) (*connect.Response[protocol.ListDeviceRevocationsResponse], error) {
	return c.listDeviceRevocations.CallUnary(ctx, req)
}

// IssueAccessGrant calls ardents.v1.IdentityService.IssueAccessGrant.
func (c *identityServiceClient) IssueAccessGrant(ctx context.Context, req *connect.Request[protocol.IssueAccessGrantRequest]) (*connect.Response[protocol.IssueAccessGrantResponse], error) {
	return c.issueAccessGrant.CallUnary(ctx, req)
}

// RevokeAccessGrant calls ardents.v1.IdentityService.RevokeAccessGrant.
func (c *identityServiceClient) RevokeAccessGrant(ctx context.Context, req *connect.Request[protocol.RevokeAccessGrantRequest]) (*connect.Response[protocol.RevokeAccessGrantResponse], error) {
	return c.revokeAccessGrant.CallUnary(ctx, req)
}

// ListAccessGrants calls ardents.v1.IdentityService.ListAccessGrants.
func (c *identityServiceClient) ListAccessGrants(ctx context.Context, req *connect.Request[protocol.ListAccessGrantsRequest]) (*connect.Response[protocol.ListAccessGrantsResponse], error) {
	return c.listAccessGrants.CallUnary(ctx, req)
}

// IssueApplicationEnrollmentTicket calls
// ardents.v1.IdentityService.IssueApplicationEnrollmentTicket.
func (c *identityServiceClient) IssueApplicationEnrollmentTicket(ctx context.Context, req *connect.Request[protocol.IssueApplicationEnrollmentTicketRequest]) (*connect.Response[protocol.IssueApplicationEnrollmentTicketResponse], error) {
	return c.issueApplicationEnrollmentTicket.CallUnary(ctx, req)
}

// ImportDelegationRevocation calls ardents.v1.IdentityService.ImportDelegationRevocation.
func (c *identityServiceClient) ImportDelegationRevocation(ctx context.Context, req *connect.Request[protocol.ImportDelegationRevocationRequest]) (*connect.Response[protocol.ImportDelegationRevocationResponse], error) {
	return c.importDelegationRevocation.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the ardents.v1.IdentityService service.
type IdentityServiceHandler interface {
	BeginAuthentication(context.Context, *connect.Request[protocol.BeginAuthenticationRequest]) (*connect.Response[protocol.BeginAuthenticationResponse], error)
	CompleteAuthentication(context.Context, *connect.Request[protocol.CompleteAuthenticationRequest]) (*connect.Response[protocol.CompleteAuthenticationResponse], error)
	EnrollFirstPrincipal(context.Context, *connect.Request[protocol.EnrollFirstPrincipalRequest]) (*connect.Response[protocol.EnrollFirstPrincipalResponse], error)
	EnrollPrincipal(context.Context, *connect.Request[protocol.EnrollPrincipalRequest]) (*connect.Response[protocol.EnrollPrincipalResponse], error)
	RevokeDevice(context.Context, *connect.Request[protocol.RevokeDeviceRequest]) (*connect.Response[protocol.RevokeDeviceResponse], error)
	ListDeviceRevocations(context.Context, *connect.Request[protocol.ListDeviceRevocationsRequest]) (*connect.Response[protocol.ListDeviceRevocationsResponse], error)
	IssueAccessGrant(context.Context, *connect.Request[protocol.IssueAccessGrantRequest]) (*connect.Response[protocol.IssueAccessGrantResponse], error)
	RevokeAccessGrant(context.Context, *connect.Request[protocol.RevokeAccessGrantRequest]) (*connect.Response[protocol.RevokeAccessGrantResponse], error)
	ListAccessGrants(context.Context, *connect.Request[protocol.ListAccessGrantsRequest]) (*connect.Response[protocol.ListAccessGrantsResponse], error)
	IssueApplicationEnrollmentTicket(context.Context, *connect.Request[protocol.IssueApplicationEnrollmentTicketRequest]) (*connect.Response[protocol.IssueApplicationEnrollmentTicketResponse], error)
	ImportDelegationRevocation(context.Context, *connect.Request[protocol.ImportDelegationRevocationRequest]) (*connect.Response[protocol.ImportDelegationRevocationResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := protocol.File_api_ardents_v1_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceBeginAuthenticationHandler := connect.NewUnaryHandler(
		IdentityServiceBeginAuthenticationProcedure,
		svc.BeginAuthentication,
		connect.WithSchema(identityServiceMethods.ByName("BeginAuthentication")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceCompleteAuthenticationHandler := connect.NewUnaryHandler(
		IdentityServiceCompleteAuthenticationProcedure,
		svc.CompleteAuthentication,
		connect.WithSchema(identityServiceMethods.ByName("CompleteAuthentication")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceEnrollFirstPrincipalHandler := connect.NewUnaryHandler(
		IdentityServiceEnrollFirstPrincipalProcedure,
		svc.EnrollFirstPrincipal,
		connect.WithSchema(identityServiceMethods.ByName("EnrollFirstPrincipal")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceEnrollPrincipalHandler := connect.NewUnaryHandler(
		IdentityServiceEnrollPrincipalProcedure,
		svc.EnrollPrincipal,
		connect.WithSchema(identityServiceMethods.ByName("EnrollPrincipal")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRevokeDeviceHandler := connect.NewUnaryHandler(
		IdentityServiceRevokeDeviceProcedure,
		svc.RevokeDevice,
		connect.WithSchema(identityServiceMethods.ByName("RevokeDevice")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceListDeviceRevocationsHandler := connect.NewUnaryHandler(
		IdentityServiceListDeviceRevocationsProcedure,
		svc.ListDeviceRevocations,
		connect.WithSchema(identityServiceMethods.ByName("ListDeviceRevocations")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceIssueAccessGrantHandler := connect.NewUnaryHandler(
		IdentityServiceIssueAccessGrantProcedure,
		svc.IssueAccessGrant,
		connect.WithSchema(identityServiceMethods.ByName("IssueAccessGrant")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRevokeAccessGrantHandler := connect.NewUnaryHandler(
		IdentityServiceRevokeAccessGrantProcedure,
		svc.RevokeAccessGrant,
		connect.WithSchema(identityServiceMethods.ByName("RevokeAccessGrant")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceListAccessGrantsHandler := connect.NewUnaryHandler(
		IdentityServiceListAccessGrantsProcedure,
		svc.ListAccessGrants,
		connect.WithSchema(identityServiceMethods.ByName("ListAccessGrants")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceIssueApplicationEnrollmentTicketHandler := connect.NewUnaryHandler(
		IdentityServiceIssueApplicationEnrollmentTicketProcedure,
		svc.IssueApplicationEnrollmentTicket,
		connect.WithSchema(identityServiceMethods.ByName("IssueApplicationEnrollmentTicket")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceImportDelegationRevocationHandler := connect.NewUnaryHandler(
		IdentityServiceImportDelegationRevocationProcedure,
		svc.ImportDelegationRevocation,
		connect.WithSchema(identityServiceMethods.ByName("ImportDelegationRevocation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceBeginAuthenticationProcedure:
			identityServiceBeginAuthenticationHandler.ServeHTTP(w, r)
		case IdentityServiceCompleteAuthenticationProcedure:
			identityServiceCompleteAuthenticationHandler.ServeHTTP(w, r)
		case IdentityServiceEnrollFirstPrincipalProcedure:
			identityServiceEnrollFirstPrincipalHandler.ServeHTTP(w, r)
		case IdentityServiceEnrollPrincipalProcedure:
			identityServiceEnrollPrincipalHandler.ServeHTTP(w, r)
		case IdentityServiceRevokeDeviceProcedure:
			identityServiceRevokeDeviceHandler.ServeHTTP(w, r)
		case IdentityServiceListDeviceRevocationsProcedure:
			identityServiceListDeviceRevocationsHandler.ServeHTTP(w, r)
		case IdentityServiceIssueAccessGrantProcedure:
			identityServiceIssueAccessGrantHandler.ServeHTTP(w, r)
		case IdentityServiceRevokeAccessGrantProcedure:
			identityServiceRevokeAccessGrantHandler.ServeHTTP(w, r)
		case IdentityServiceListAccessGrantsProcedure:
			identityServiceListAccessGrantsHandler.ServeHTTP(w, r)
		case IdentityServiceIssueApplicationEnrollmentTicketProcedure:
			identityServiceIssueApplicationEnrollmentTicketHandler.ServeHTTP(w, r)
		case IdentityServiceImportDelegationRevocationProcedure:
			identityServiceImportDelegationRevocationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) BeginAuthentication(context.Context, *connect.Request[protocol.BeginAuthenticationRequest]) (*connect.Response[protocol.BeginAuthenticationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.BeginAuthentication is not implemented"))
}

func (UnimplementedIdentityServiceHandler) CompleteAuthentication(context.Context, *connect.Request[protocol.CompleteAuthenticationRequest]) (*connect.Response[protocol.CompleteAuthenticationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.CompleteAuthentication is not implemented"))
}

func (UnimplementedIdentityServiceHandler) EnrollFirstPrincipal(context.Context, *connect.Request[protocol.EnrollFirstPrincipalRequest]) (*connect.Response[protocol.EnrollFirstPrincipalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.EnrollFirstPrincipal is not implemented"))
}

func (UnimplementedIdentityServiceHandler) EnrollPrincipal(context.Context, *connect.Request[protocol.EnrollPrincipalRequest]) (*connect.Response[protocol.EnrollPrincipalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.EnrollPrincipal is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RevokeDevice(context.Context, *connect.Request[protocol.RevokeDeviceRequest]) (*connect.Response[protocol.RevokeDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.RevokeDevice is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ListDeviceRevocations(context.Context, *connect.Request[protocol.ListDeviceRevocationsRequest]) (*connect.Response[protocol.ListDeviceRevocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.ListDeviceRevocations is not implemented"))
}

func (UnimplementedIdentityServiceHandler) IssueAccessGrant(context.Context, *connect.Request[protocol.IssueAccessGrantRequest]) (*connect.Response[protocol.IssueAccessGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.IssueAccessGrant is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RevokeAccessGrant(context.Context, *connect.Request[protocol.RevokeAccessGrantRequest]) (*connect.Response[protocol.RevokeAccessGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.RevokeAccessGrant is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ListAccessGrants(context.Context, *connect.Request[protocol.ListAccessGrantsRequest]) (*connect.Response[protocol.ListAccessGrantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.ListAccessGrants is not implemented"))
}

func (UnimplementedIdentityServiceHandler) IssueApplicationEnrollmentTicket(context.Context, *connect.Request[protocol.IssueApplicationEnrollmentTicketRequest]) (*connect.Response[protocol.IssueApplicationEnrollmentTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.IssueApplicationEnrollmentTicket is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ImportDelegationRevocation(context.Context, *connect.Request[protocol.ImportDelegationRevocationRequest]) (*connect.Response[protocol.ImportDelegationRevocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.IdentityService.ImportDelegationRevocation is not implemented"))
}
