// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/network.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NetworkServiceName is the fully-qualified name of the NetworkService service.
	NetworkServiceName = "ardents.v1.NetworkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NetworkServiceGetNetworkStatusProcedure is the fully-qualified name of the NetworkService's
	// GetNetworkStatus RPC.
	NetworkServiceGetNetworkStatusProcedure = "/ardents.v1.NetworkService/GetNetworkStatus"
	// NetworkServiceGetDiscoveryStatusProcedure is the fully-qualified name of the NetworkService's
	// GetDiscoveryStatus RPC.
	NetworkServiceGetDiscoveryStatusProcedure = "/ardents.v1.NetworkService/GetDiscoveryStatus"
	// NetworkServiceGetLocalPresenceProcedure is the fully-qualified name of the NetworkService's
	// GetLocalPresence RPC.
	NetworkServiceGetLocalPresenceProcedure = "/ardents.v1.NetworkService/GetLocalPresence"
	// NetworkServiceListPeersProcedure is the fully-qualified name of the NetworkService's ListPeers
	// RPC.
	NetworkServiceListPeersProcedure = "/ardents.v1.NetworkService/ListPeers"
	// NetworkServiceListRouteCandidatesProcedure is the fully-qualified name of the NetworkService's
	// ListRouteCandidates RPC.
	NetworkServiceListRouteCandidatesProcedure = "/ardents.v1.NetworkService/ListRouteCandidates"
	// NetworkServiceResolveRecordProcedure is the fully-qualified name of the NetworkService's
	// ResolveRecord RPC.
	NetworkServiceResolveRecordProcedure = "/ardents.v1.NetworkService/ResolveRecord"
	// NetworkServiceResolveServiceProcedure is the fully-qualified name of the NetworkService's
	// ResolveService RPC.
	NetworkServiceResolveServiceProcedure = "/ardents.v1.NetworkService/ResolveService"
	// NetworkServiceListRecordsProcedure is the fully-qualified name of the NetworkService's
	// ListRecords RPC.
	NetworkServiceListRecordsProcedure = "/ardents.v1.NetworkService/ListRecords"
	// NetworkServiceImportRecordProcedure is the fully-qualified name of the NetworkService's
	// ImportRecord RPC.
	NetworkServiceImportRecordProcedure = "/ardents.v1.NetworkService/ImportRecord"
)

// NetworkServiceClient is a client for the ardents.v1.NetworkService service.
type NetworkServiceClient interface {
	GetNetworkStatus(context.Context, *connect.Request[protocol.GetNetworkStatusRequest]) (*connect.Response[protocol.NetworkStatusResponse], error)
	GetDiscoveryStatus(context.Context, *connect.Request[protocol.GetDiscoveryStatusRequest]) (*connect.Response[protocol.DiscoveryStatusResponse], error)
	GetLocalPresence(context.Context, *connect.Request[protocol.GetLocalPresenceRequest]) (*connect.Response[protocol.LocalPresenceResponse], error)
	ListPeers(context.Context, *connect.Request[protocol.ListPeersRequest]) (*connect.Response[protocol.ListPeersResponse], error)
	ListRouteCandidates(context.Context, *connect.Request[protocol.ListRouteCandidatesRequest]) (*connect.Response[protocol.ListRouteCandidatesResponse], error)
	ResolveRecord(context.Context, *connect.Request[protocol.ResolveRecordRequest]) (*connect.Response[protocol.DiscoveryResult], error)
	ResolveService(context.Context, *connect.Request[protocol.ResolveServiceRequest]) (*connect.Response[protocol.ServiceResult], error)
	ListRecords(context.Context, *connect.Request[protocol.ListRecordsRequest]) (*connect.Response[protocol.ListRecordsResponse], error)
	ImportRecord(context.Context, *connect.Request[protocol.ImportRecordRequest]) (*connect.Response[protocol.RecordImportResponse], error)
}

// NewNetworkServiceClient constructs a client for the ardents.v1.NetworkService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNetworkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NetworkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	networkServiceMethods := protocol.File_api_ardents_v1_network_proto.Services().ByName("NetworkService").Methods()
	return &networkServiceClient{
		getNetworkStatus: connect.NewClient[protocol.GetNetworkStatusRequest, protocol.NetworkStatusResponse](
			httpClient,
			baseURL+NetworkServiceGetNetworkStatusProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetNetworkStatus")),
			connect.WithClientOptions(opts...),
		),
		getDiscoveryStatus: connect.NewClient[protocol.GetDiscoveryStatusRequest, protocol.DiscoveryStatusResponse](
			httpClient,
			baseURL+NetworkServiceGetDiscoveryStatusProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetDiscoveryStatus")),
			connect.WithClientOptions(opts...),
		),
		getLocalPresence: connect.NewClient[protocol.GetLocalPresenceRequest, protocol.LocalPresenceResponse](
			httpClient,
			baseURL+NetworkServiceGetLocalPresenceProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetLocalPresence")),
			connect.WithClientOptions(opts...),
		),
		listPeers: connect.NewClient[protocol.ListPeersRequest, protocol.ListPeersResponse](
			httpClient,
			baseURL+NetworkServiceListPeersProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListPeers")),
			connect.WithClientOptions(opts...),
		),
		listRouteCandidates: connect.NewClient[protocol.ListRouteCandidatesRequest, protocol.ListRouteCandidatesResponse](
			httpClient,
			baseURL+NetworkServiceListRouteCandidatesProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListRouteCandidates")),
			connect.WithClientOptions(opts...),
		),
		resolveRecord: connect.NewClient[protocol.ResolveRecordRequest, protocol.DiscoveryResult](
			httpClient,
			baseURL+NetworkServiceResolveRecordProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ResolveRecord")),
			connect.WithClientOptions(opts...),
		),
		resolveService: connect.NewClient[protocol.ResolveServiceRequest, protocol.ServiceResult](
			httpClient,
			baseURL+NetworkServiceResolveServiceProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ResolveService")),
			connect.WithClientOptions(opts...),
		),
		listRecords: connect.NewClient[protocol.ListRecordsRequest, protocol.ListRecordsResponse](
			httpClient,
			baseURL+NetworkServiceListRecordsProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListRecords")),
			connect.WithClientOptions(opts...),
		),
		importRecord: connect.NewClient[protocol.ImportRecordRequest, protocol.RecordImportResponse](
			httpClient,
			baseURL+NetworkServiceImportRecordProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ImportRecord")),
			connect.WithClientOptions(opts...),
		),
	}
}

// networkServiceClient implements NetworkServiceClient.
type networkServiceClient struct {
	getNetworkStatus    *connect.Client[protocol.GetNetworkStatusRequest, protocol.NetworkStatusResponse]
	getDiscoveryStatus  *connect.Client[protocol.GetDiscoveryStatusRequest, protocol.DiscoveryStatusResponse]
	getLocalPresence    *connect.Client[protocol.GetLocalPresenceRequest, protocol.LocalPresenceResponse]
	listPeers           *connect.Client[protocol.ListPeersRequest, protocol.ListPeersResponse]
	listRouteCandidates *connect.Client[protocol.ListRouteCandidatesRequest, protocol.ListRouteCandidatesResponse]
	resolveRecord       *connect.Client[protocol.ResolveRecordRequest, protocol.DiscoveryResult]
	resolveService      *connect.Client[protocol.ResolveServiceRequest, protocol.ServiceResult]
	listRecords         *connect.Client[protocol.ListRecordsRequest, protocol.ListRecordsResponse]
	importRecord        *connect.Client[protocol.ImportRecordRequest, protocol.RecordImportResponse]
}

// GetNetworkStatus calls ardents.v1.NetworkService.GetNetworkStatus.
func (c *networkServiceClient) GetNetworkStatus(ctx context.Context, req *connect.Request[protocol.GetNetworkStatusRequest]) (*connect.Response[protocol.NetworkStatusResponse], error) {
	return c.getNetworkStatus.CallUnary(ctx, req)
}

// GetDiscoveryStatus calls ardents.v1.NetworkService.GetDiscoveryStatus.
func (c *networkServiceClient) GetDiscoveryStatus(ctx context.Context, req *connect.Request[protocol.GetDiscoveryStatusRequest]) (*connect.Response[protocol.DiscoveryStatusResponse], error) {
	return c.getDiscoveryStatus.CallUnary(ctx, req)
}

// GetLocalPresence calls ardents.v1.NetworkService.GetLocalPresence.
func (c *networkServiceClient) GetLocalPresence(ctx context.Context, req *connect.Request[protocol.GetLocalPresenceRequest]) (*connect.Response[protocol.LocalPresenceResponse], error) {
	return c.getLocalPresence.CallUnary(ctx, req)
}

// ListPeers calls ardents.v1.NetworkService.ListPeers.
func (c *networkServiceClient) ListPeers(ctx context.Context, req *connect.Request[protocol.ListPeersRequest]) (*connect.Response[protocol.ListPeersResponse], error) {
	return c.listPeers.CallUnary(ctx, req)
}

// ListRouteCandidates calls ardents.v1.NetworkService.ListRouteCandidates.
func (c *networkServiceClient) ListRouteCandidates(ctx context.Context, req *connect.Request[protocol.ListRouteCandidatesRequest]) (*connect.Response[protocol.ListRouteCandidatesResponse], error) {
	return c.listRouteCandidates.CallUnary(ctx, req)
}

// ResolveRecord calls ardents.v1.NetworkService.ResolveRecord.
func (c *networkServiceClient) ResolveRecord(ctx context.Context, req *connect.Request[protocol.ResolveRecordRequest]) (*connect.Response[protocol.DiscoveryResult], error) {
	return c.resolveRecord.CallUnary(ctx, req)
}

// ResolveService calls ardents.v1.NetworkService.ResolveService.
func (c *networkServiceClient) ResolveService(ctx context.Context, req *connect.Request[protocol.ResolveServiceRequest]) (*connect.Response[protocol.ServiceResult], error) {
	return c.resolveService.CallUnary(ctx, req)
}

// ListRecords calls ardents.v1.NetworkService.ListRecords.
func (c *networkServiceClient) ListRecords(ctx context.Context, req *connect.Request[protocol.ListRecordsRequest]) (*connect.Response[protocol.ListRecordsResponse], error) {
	return c.listRecords.CallUnary(ctx, req)
}

// ImportRecord calls ardents.v1.NetworkService.ImportRecord.
func (c *networkServiceClient) ImportRecord(ctx context.Context, req *connect.Request[protocol.ImportRecordRequest]) (*connect.Response[protocol.RecordImportResponse], error) {
	return c.importRecord.CallUnary(ctx, req)
}

// NetworkServiceHandler is an implementation of the ardents.v1.NetworkService service.
type NetworkServiceHandler interface {
	GetNetworkStatus(context.Context, *connect.Request[protocol.GetNetworkStatusRequest]) (*connect.Response[protocol.NetworkStatusResponse], error)
	GetDiscoveryStatus(context.Context, *connect.Request[protocol.GetDiscoveryStatusRequest]) (*connect.Response[protocol.DiscoveryStatusResponse], error)
	GetLocalPresence(context.Context, *connect.Request[protocol.GetLocalPresenceRequest]) (*connect.Response[protocol.LocalPresenceResponse], error)
	ListPeers(context.Context, *connect.Request[protocol.ListPeersRequest]) (*connect.Response[protocol.ListPeersResponse], error)
	ListRouteCandidates(context.Context, *connect.Request[protocol.ListRouteCandidatesRequest]) (*connect.Response[protocol.ListRouteCandidatesResponse], error)
	ResolveRecord(context.Context, *connect.Request[protocol.ResolveRecordRequest]) (*connect.Response[protocol.DiscoveryResult], error)
	ResolveService(context.Context, *connect.Request[protocol.ResolveServiceRequest]) (*connect.Response[protocol.ServiceResult], error)
	ListRecords(context.Context, *connect.Request[protocol.ListRecordsRequest]) (*connect.Response[protocol.ListRecordsResponse], error)
	ImportRecord(context.Context, *connect.Request[protocol.ImportRecordRequest]) (*connect.Response[protocol.RecordImportResponse], error)
}

// NewNetworkServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNetworkServiceHandler(svc NetworkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	networkServiceMethods := protocol.File_api_ardents_v1_network_proto.Services().ByName("NetworkService").Methods()
	networkServiceGetNetworkStatusHandler := connect.NewUnaryHandler(
		NetworkServiceGetNetworkStatusProcedure,
		svc.GetNetworkStatus,
		connect.WithSchema(networkServiceMethods.ByName("GetNetworkStatus")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceGetDiscoveryStatusHandler := connect.NewUnaryHandler(
		NetworkServiceGetDiscoveryStatusProcedure,
		svc.GetDiscoveryStatus,
		connect.WithSchema(networkServiceMethods.ByName("GetDiscoveryStatus")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceGetLocalPresenceHandler := connect.NewUnaryHandler(
		NetworkServiceGetLocalPresenceProcedure,
		svc.GetLocalPresence,
		connect.WithSchema(networkServiceMethods.ByName("GetLocalPresence")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListPeersHandler := connect.NewUnaryHandler(
		NetworkServiceListPeersProcedure,
		svc.ListPeers,
		connect.WithSchema(networkServiceMethods.ByName("ListPeers")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListRouteCandidatesHandler := connect.NewUnaryHandler(
		NetworkServiceListRouteCandidatesProcedure,
		svc.ListRouteCandidates,
		connect.WithSchema(networkServiceMethods.ByName("ListRouteCandidates")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceResolveRecordHandler := connect.NewUnaryHandler(
		NetworkServiceResolveRecordProcedure,
		svc.ResolveRecord,
		connect.WithSchema(networkServiceMethods.ByName("ResolveRecord")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceResolveServiceHandler := connect.NewUnaryHandler(
		NetworkServiceResolveServiceProcedure,
		svc.ResolveService,
		connect.WithSchema(networkServiceMethods.ByName("ResolveService")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListRecordsHandler := connect.NewUnaryHandler(
		NetworkServiceListRecordsProcedure,
		svc.ListRecords,
		connect.WithSchema(networkServiceMethods.ByName("ListRecords")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceImportRecordHandler := connect.NewUnaryHandler(
		NetworkServiceImportRecordProcedure,
		svc.ImportRecord,
		connect.WithSchema(networkServiceMethods.ByName("ImportRecord")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.NetworkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NetworkServiceGetNetworkStatusProcedure:
			networkServiceGetNetworkStatusHandler.ServeHTTP(w, r)
		case NetworkServiceGetDiscoveryStatusProcedure:
			networkServiceGetDiscoveryStatusHandler.ServeHTTP(w, r)
		case NetworkServiceGetLocalPresenceProcedure:
			networkServiceGetLocalPresenceHandler.ServeHTTP(w, r)
		case NetworkServiceListPeersProcedure:
			networkServiceListPeersHandler.ServeHTTP(w, r)
		case NetworkServiceListRouteCandidatesProcedure:
			networkServiceListRouteCandidatesHandler.ServeHTTP(w, r)
		case NetworkServiceResolveRecordProcedure:
			networkServiceResolveRecordHandler.ServeHTTP(w, r)
		case NetworkServiceResolveServiceProcedure:
			networkServiceResolveServiceHandler.ServeHTTP(w, r)
		case NetworkServiceListRecordsProcedure:
			networkServiceListRecordsHandler.ServeHTTP(w, r)
		case NetworkServiceImportRecordProcedure:
			networkServiceImportRecordHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNetworkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNetworkServiceHandler struct{}

func (UnimplementedNetworkServiceHandler) GetNetworkStatus(context.Context, *connect.Request[protocol.GetNetworkStatusRequest]) (*connect.Response[protocol.NetworkStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.GetNetworkStatus is not implemented"))
}

func (UnimplementedNetworkServiceHandler) GetDiscoveryStatus(context.Context, *connect.Request[protocol.GetDiscoveryStatusRequest]) (*connect.Response[protocol.DiscoveryStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.GetDiscoveryStatus is not implemented"))
}

func (UnimplementedNetworkServiceHandler) GetLocalPresence(context.Context, *connect.Request[protocol.GetLocalPresenceRequest]) (*connect.Response[protocol.LocalPresenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.GetLocalPresence is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListPeers(context.Context, *connect.Request[protocol.ListPeersRequest]) (*connect.Response[protocol.ListPeersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.ListPeers is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListRouteCandidates(context.Context, *connect.Request[protocol.ListRouteCandidatesRequest]) (*connect.Response[protocol.ListRouteCandidatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.ListRouteCandidates is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ResolveRecord(context.Context, *connect.Request[protocol.ResolveRecordRequest]) (*connect.Response[protocol.DiscoveryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.ResolveRecord is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ResolveService(context.Context, *connect.Request[protocol.ResolveServiceRequest]) (*connect.Response[protocol.ServiceResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.ResolveService is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListRecords(context.Context, *connect.Request[protocol.ListRecordsRequest]) (*connect.Response[protocol.ListRecordsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.ListRecords is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ImportRecord(context.Context, *connect.Request[protocol.ImportRecordRequest]) (*connect.Response[protocol.RecordImportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NetworkService.ImportRecord is not implemented"))
}
