// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/node.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "ardents.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceStartNodeProcedure is the fully-qualified name of the NodeService's StartNode RPC.
	NodeServiceStartNodeProcedure = "/ardents.v1.NodeService/StartNode"
	// NodeServiceStopNodeProcedure is the fully-qualified name of the NodeService's StopNode RPC.
	NodeServiceStopNodeProcedure = "/ardents.v1.NodeService/StopNode"
	// NodeServiceGetNodeStatusProcedure is the fully-qualified name of the NodeService's GetNodeStatus
	// RPC.
	NodeServiceGetNodeStatusProcedure = "/ardents.v1.NodeService/GetNodeStatus"
	// NodeServiceGetNodeCapabilitiesProcedure is the fully-qualified name of the NodeService's
	// GetNodeCapabilities RPC.
	NodeServiceGetNodeCapabilitiesProcedure = "/ardents.v1.NodeService/GetNodeCapabilities"
	// NodeServiceGetNodeRuntimeProcedure is the fully-qualified name of the NodeService's
	// GetNodeRuntime RPC.
	NodeServiceGetNodeRuntimeProcedure = "/ardents.v1.NodeService/GetNodeRuntime"
	// NodeServiceStreamNodeEventsProcedure is the fully-qualified name of the NodeService's
	// StreamNodeEvents RPC.
	NodeServiceStreamNodeEventsProcedure = "/ardents.v1.NodeService/StreamNodeEvents"
)

// NodeServiceClient is a client for the ardents.v1.NodeService service.
type NodeServiceClient interface {
	StartNode(context.Context, *connect.Request[protocol.StartNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error)
	StopNode(context.Context, *connect.Request[protocol.StopNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error)
	GetNodeStatus(context.Context, *connect.Request[protocol.GetNodeStatusRequest]) (*connect.Response[protocol.NodeStatusResponse], error)
	GetNodeCapabilities(context.Context, *connect.Request[protocol.GetNodeCapabilitiesRequest]) (*connect.Response[protocol.CapabilitiesResponse], error)
	GetNodeRuntime(context.Context, *connect.Request[protocol.GetNodeRuntimeRequest]) (*connect.Response[protocol.NodeRuntimeResponse], error)
	StreamNodeEvents(context.Context, *connect.Request[protocol.StreamNodeEventsRequest]) (*connect.ServerStreamForClient[protocol.EventEnvelope], error)
}

// NewNodeServiceClient constructs a client for the ardents.v1.NodeService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := protocol.File_api_ardents_v1_node_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		startNode: connect.NewClient[protocol.StartNodeRequest, protocol.CommandAckResponse](
			httpClient,
			baseURL+NodeServiceStartNodeProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("StartNode")),
			connect.WithClientOptions(opts...),
		),
		stopNode: connect.NewClient[protocol.StopNodeRequest, protocol.CommandAckResponse](
			httpClient,
			baseURL+NodeServiceStopNodeProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("StopNode")),
			connect.WithClientOptions(opts...),
		),
		getNodeStatus: connect.NewClient[protocol.GetNodeStatusRequest, protocol.NodeStatusResponse](
			httpClient,
			baseURL+NodeServiceGetNodeStatusProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetNodeStatus")),
			connect.WithClientOptions(opts...),
		),
		getNodeCapabilities: connect.NewClient[protocol.GetNodeCapabilitiesRequest, protocol.CapabilitiesResponse](
			httpClient,
			baseURL+NodeServiceGetNodeCapabilitiesProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetNodeCapabilities")),
			connect.WithClientOptions(opts...),
		),
		getNodeRuntime: connect.NewClient[protocol.GetNodeRuntimeRequest, protocol.NodeRuntimeResponse](
			httpClient,
			baseURL+NodeServiceGetNodeRuntimeProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetNodeRuntime")),
			connect.WithClientOptions(opts...),
		),
		streamNodeEvents: connect.NewClient[protocol.StreamNodeEventsRequest, protocol.EventEnvelope](
			httpClient,
			baseURL+NodeServiceStreamNodeEventsProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("StreamNodeEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	startNode           *connect.Client[protocol.StartNodeRequest, protocol.CommandAckResponse]
	stopNode            *connect.Client[protocol.StopNodeRequest, protocol.CommandAckResponse]
	getNodeStatus       *connect.Client[protocol.GetNodeStatusRequest, protocol.NodeStatusResponse]
	getNodeCapabilities *connect.Client[protocol.GetNodeCapabilitiesRequest, protocol.CapabilitiesResponse]
	getNodeRuntime      *connect.Client[protocol.GetNodeRuntimeRequest, protocol.NodeRuntimeResponse]
	streamNodeEvents    *connect.Client[protocol.StreamNodeEventsRequest, protocol.EventEnvelope]
}

// StartNode calls ardents.v1.NodeService.StartNode.
func (c *nodeServiceClient) StartNode(ctx context.Context, req *connect.Request[protocol.StartNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error) {
	return c.startNode.CallUnary(ctx, req)
}

// StopNode calls ardents.v1.NodeService.StopNode.
func (c *nodeServiceClient) StopNode(ctx context.Context, req *connect.Request[protocol.StopNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error) {
	return c.stopNode.CallUnary(ctx, req)
}

// GetNodeStatus calls ardents.v1.NodeService.GetNodeStatus.
func (c *nodeServiceClient) GetNodeStatus(ctx context.Context, req *connect.Request[protocol.GetNodeStatusRequest]) (*connect.Response[protocol.NodeStatusResponse], error) {
	return c.getNodeStatus.CallUnary(ctx, req)
}

// GetNodeCapabilities calls ardents.v1.NodeService.GetNodeCapabilities.
func (c *nodeServiceClient) GetNodeCapabilities(ctx context.Context, req *connect.Request[protocol.GetNodeCapabilitiesRequest]) (*connect.Response[protocol.CapabilitiesResponse], error) {
	return c.getNodeCapabilities.CallUnary(ctx, req)
}

// GetNodeRuntime calls ardents.v1.NodeService.GetNodeRuntime.
func (c *nodeServiceClient) GetNodeRuntime(ctx context.Context, req *connect.Request[protocol.GetNodeRuntimeRequest]) (*connect.Response[protocol.NodeRuntimeResponse], error) {
	return c.getNodeRuntime.CallUnary(ctx, req)
}

// StreamNodeEvents calls ardents.v1.NodeService.StreamNodeEvents.
func (c *nodeServiceClient) StreamNodeEvents(ctx context.Context, req *connect.Request[protocol.StreamNodeEventsRequest]) (*connect.ServerStreamForClient[protocol.EventEnvelope], error) {
	return c.streamNodeEvents.CallServerStream(ctx, req)
}

// NodeServiceHandler is an implementation of the ardents.v1.NodeService service.
type NodeServiceHandler interface {
	StartNode(context.Context, *connect.Request[protocol.StartNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error)
	StopNode(context.Context, *connect.Request[protocol.StopNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error)
	GetNodeStatus(context.Context, *connect.Request[protocol.GetNodeStatusRequest]) (*connect.Response[protocol.NodeStatusResponse], error)
	GetNodeCapabilities(context.Context, *connect.Request[protocol.GetNodeCapabilitiesRequest]) (*connect.Response[protocol.CapabilitiesResponse], error)
	GetNodeRuntime(context.Context, *connect.Request[protocol.GetNodeRuntimeRequest]) (*connect.Response[protocol.NodeRuntimeResponse], error)
	StreamNodeEvents(context.Context, *connect.Request[protocol.StreamNodeEventsRequest], *connect.ServerStream[protocol.EventEnvelope]) error
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := protocol.File_api_ardents_v1_node_proto.Services().ByName("NodeService").Methods()
	nodeServiceStartNodeHandler := connect.NewUnaryHandler(
		NodeServiceStartNodeProcedure,
		svc.StartNode,
		connect.WithSchema(nodeServiceMethods.ByName("StartNode")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceStopNodeHandler := connect.NewUnaryHandler(
		NodeServiceStopNodeProcedure,
		svc.StopNode,
		connect.WithSchema(nodeServiceMethods.ByName("StopNode")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetNodeStatusHandler := connect.NewUnaryHandler(
		NodeServiceGetNodeStatusProcedure,
		svc.GetNodeStatus,
		connect.WithSchema(nodeServiceMethods.ByName("GetNodeStatus")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetNodeCapabilitiesHandler := connect.NewUnaryHandler(
		NodeServiceGetNodeCapabilitiesProcedure,
		svc.GetNodeCapabilities,
		connect.WithSchema(nodeServiceMethods.ByName("GetNodeCapabilities")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetNodeRuntimeHandler := connect.NewUnaryHandler(
		NodeServiceGetNodeRuntimeProcedure,
		svc.GetNodeRuntime,
		connect.WithSchema(nodeServiceMethods.ByName("GetNodeRuntime")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceStreamNodeEventsHandler := connect.NewServerStreamHandler(
		NodeServiceStreamNodeEventsProcedure,
		svc.StreamNodeEvents,
		connect.WithSchema(nodeServiceMethods.ByName("StreamNodeEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceStartNodeProcedure:
			nodeServiceStartNodeHandler.ServeHTTP(w, r)
		case NodeServiceStopNodeProcedure:
			nodeServiceStopNodeHandler.ServeHTTP(w, r)
		case NodeServiceGetNodeStatusProcedure:
			nodeServiceGetNodeStatusHandler.ServeHTTP(w, r)
		case NodeServiceGetNodeCapabilitiesProcedure:
			nodeServiceGetNodeCapabilitiesHandler.ServeHTTP(w, r)
		case NodeServiceGetNodeRuntimeProcedure:
			nodeServiceGetNodeRuntimeHandler.ServeHTTP(w, r)
		case NodeServiceStreamNodeEventsProcedure:
			nodeServiceStreamNodeEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) StartNode(context.Context, *connect.Request[protocol.StartNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NodeService.StartNode is not implemented"))
}

func (UnimplementedNodeServiceHandler) StopNode(context.Context, *connect.Request[protocol.StopNodeRequest]) (*connect.Response[protocol.CommandAckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NodeService.StopNode is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetNodeStatus(context.Context, *connect.Request[protocol.GetNodeStatusRequest]) (*connect.Response[protocol.NodeStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NodeService.GetNodeStatus is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetNodeCapabilities(context.Context, *connect.Request[protocol.GetNodeCapabilitiesRequest]) (*connect.Response[protocol.CapabilitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NodeService.GetNodeCapabilities is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetNodeRuntime(context.Context, *connect.Request[protocol.GetNodeRuntimeRequest]) (*connect.Response[protocol.NodeRuntimeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NodeService.GetNodeRuntime is not implemented"))
}

func (UnimplementedNodeServiceHandler) StreamNodeEvents(context.Context, *connect.Request[protocol.StreamNodeEventsRequest], *connect.ServerStream[protocol.EventEnvelope]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.NodeService.StreamNodeEvents is not implemented"))
}
