// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/retention.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RetentionServiceName is the fully-qualified name of the RetentionService service.
	RetentionServiceName = "ardents.v1.RetentionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RetentionServiceRetainBlobProcedure is the fully-qualified name of the RetentionService's
	// RetainBlob RPC.
	RetentionServiceRetainBlobProcedure = "/ardents.v1.RetentionService/RetainBlob"
	// RetentionServicePinBlobProcedure is the fully-qualified name of the RetentionService's PinBlob
	// RPC.
	RetentionServicePinBlobProcedure = "/ardents.v1.RetentionService/PinBlob"
	// RetentionServiceDropBlobProcedure is the fully-qualified name of the RetentionService's DropBlob
	// RPC.
	RetentionServiceDropBlobProcedure = "/ardents.v1.RetentionService/DropBlob"
)

// RetentionServiceClient is a client for the ardents.v1.RetentionService service.
type RetentionServiceClient interface {
	RetainBlob(context.Context, *connect.Request[protocol.RetainBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	PinBlob(context.Context, *connect.Request[protocol.PinBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	DropBlob(context.Context, *connect.Request[protocol.DropBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
}

// NewRetentionServiceClient constructs a client for the ardents.v1.RetentionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRetentionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RetentionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	retentionServiceMethods := protocol.File_api_ardents_v1_retention_proto.Services().ByName("RetentionService").Methods()
	return &retentionServiceClient{
		retainBlob: connect.NewClient[protocol.RetainBlobRequest, protocol.BlobSnapshot](
			httpClient,
			baseURL+RetentionServiceRetainBlobProcedure,
			connect.WithSchema(retentionServiceMethods.ByName("RetainBlob")),
			connect.WithClientOptions(opts...),
		),
		pinBlob: connect.NewClient[protocol.PinBlobRequest, protocol.BlobSnapshot](
			httpClient,
			baseURL+RetentionServicePinBlobProcedure,
			connect.WithSchema(retentionServiceMethods.ByName("PinBlob")),
			connect.WithClientOptions(opts...),
		),
		dropBlob: connect.NewClient[protocol.DropBlobRequest, protocol.BlobSnapshot](
			httpClient,
			baseURL+RetentionServiceDropBlobProcedure,
			connect.WithSchema(retentionServiceMethods.ByName("DropBlob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// retentionServiceClient implements RetentionServiceClient.
type retentionServiceClient struct {
	retainBlob *connect.Client[protocol.RetainBlobRequest, protocol.BlobSnapshot]
	pinBlob    *connect.Client[protocol.PinBlobRequest, protocol.BlobSnapshot]
	dropBlob   *connect.Client[protocol.DropBlobRequest, protocol.BlobSnapshot]
}

// RetainBlob calls ardents.v1.RetentionService.RetainBlob.
func (c *retentionServiceClient) RetainBlob(ctx context.Context, req *connect.Request[protocol.RetainBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return c.retainBlob.CallUnary(ctx, req)
}

// PinBlob calls ardents.v1.RetentionService.PinBlob.
func (c *retentionServiceClient) PinBlob(ctx context.Context, req *connect.Request[protocol.PinBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return c.pinBlob.CallUnary(ctx, req)
}

// DropBlob calls ardents.v1.RetentionService.DropBlob.
func (c *retentionServiceClient) DropBlob(ctx context.Context, req *connect.Request[protocol.DropBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return c.dropBlob.CallUnary(ctx, req)
}

// RetentionServiceHandler is an implementation of the ardents.v1.RetentionService service.
type RetentionServiceHandler interface {
	RetainBlob(context.Context, *connect.Request[protocol.RetainBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	PinBlob(context.Context, *connect.Request[protocol.PinBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	DropBlob(context.Context, *connect.Request[protocol.DropBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
}

// NewRetentionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRetentionServiceHandler(svc RetentionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	retentionServiceMethods := protocol.File_api_ardents_v1_retention_proto.Services().ByName("RetentionService").Methods()
	retentionServiceRetainBlobHandler := connect.NewUnaryHandler(
		RetentionServiceRetainBlobProcedure,
		svc.RetainBlob,
		connect.WithSchema(retentionServiceMethods.ByName("RetainBlob")),
		connect.WithHandlerOptions(opts...),
	)
	retentionServicePinBlobHandler := connect.NewUnaryHandler(
		RetentionServicePinBlobProcedure,
		svc.PinBlob,
		connect.WithSchema(retentionServiceMethods.ByName("PinBlob")),
		connect.WithHandlerOptions(opts...),
	)
	retentionServiceDropBlobHandler := connect.NewUnaryHandler(
		RetentionServiceDropBlobProcedure,
		svc.DropBlob,
		connect.WithSchema(retentionServiceMethods.ByName("DropBlob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.RetentionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RetentionServiceRetainBlobProcedure:
			retentionServiceRetainBlobHandler.ServeHTTP(w, r)
		case RetentionServicePinBlobProcedure:
			retentionServicePinBlobHandler.ServeHTTP(w, r)
		case RetentionServiceDropBlobProcedure:
			retentionServiceDropBlobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRetentionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRetentionServiceHandler struct{}

func (UnimplementedRetentionServiceHandler) RetainBlob(context.Context, *connect.Request[protocol.RetainBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.RetentionService.RetainBlob is not implemented"))
}

func (UnimplementedRetentionServiceHandler) PinBlob(context.Context, *connect.Request[protocol.PinBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.RetentionService.PinBlob is not implemented"))
}

func (UnimplementedRetentionServiceHandler) DropBlob(context.Context, *connect.Request[protocol.DropBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.RetentionService.DropBlob is not implemented"))
}
