// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/transfer.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TransferServiceName is the fully-qualified name of the TransferService service.
	TransferServiceName = "ardents.v1.TransferService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TransferServiceFetchBlobProcedure is the fully-qualified name of the TransferService's FetchBlob
	// RPC.
	TransferServiceFetchBlobProcedure = "/ardents.v1.TransferService/FetchBlob"
	// TransferServiceListBlobSourcesProcedure is the fully-qualified name of the TransferService's
	// ListBlobSources RPC.
	TransferServiceListBlobSourcesProcedure = "/ardents.v1.TransferService/ListBlobSources"
	// TransferServiceGetTransferProcedure is the fully-qualified name of the TransferService's
	// GetTransfer RPC.
	TransferServiceGetTransferProcedure = "/ardents.v1.TransferService/GetTransfer"
	// TransferServiceListTransfersProcedure is the fully-qualified name of the TransferService's
	// ListTransfers RPC.
	TransferServiceListTransfersProcedure = "/ardents.v1.TransferService/ListTransfers"
)

// TransferServiceClient is a client for the ardents.v1.TransferService service.
type TransferServiceClient interface {
	FetchBlob(context.Context, *connect.Request[protocol.FetchBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	ListBlobSources(context.Context, *connect.Request[protocol.ListBlobSourcesRequest]) (*connect.Response[protocol.ListBlobSourcesResponse], error)
	GetTransfer(context.Context, *connect.Request[protocol.GetTransferRequest]) (*connect.Response[protocol.GetTransferResponse], error)
	ListTransfers(context.Context, *connect.Request[protocol.ListTransfersRequest]) (*connect.Response[protocol.ListTransfersResponse], error)
}

// NewTransferServiceClient constructs a client for the ardents.v1.TransferService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTransferServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TransferServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	transferServiceMethods := protocol.File_api_ardents_v1_transfer_proto.Services().ByName("TransferService").Methods()
	return &transferServiceClient{
		fetchBlob: connect.NewClient[protocol.FetchBlobRequest, protocol.BlobSnapshot](
			httpClient,
			baseURL+TransferServiceFetchBlobProcedure,
			connect.WithSchema(transferServiceMethods.ByName("FetchBlob")),
			connect.WithClientOptions(opts...),
		),
		listBlobSources: connect.NewClient[protocol.ListBlobSourcesRequest, protocol.ListBlobSourcesResponse](
			httpClient,
			baseURL+TransferServiceListBlobSourcesProcedure,
			connect.WithSchema(transferServiceMethods.ByName("ListBlobSources")),
			connect.WithClientOptions(opts...),
		),
		getTransfer: connect.NewClient[protocol.GetTransferRequest, protocol.GetTransferResponse](
			httpClient,
			baseURL+TransferServiceGetTransferProcedure,
			connect.WithSchema(transferServiceMethods.ByName("GetTransfer")),
			connect.WithClientOptions(opts...),
		),
		listTransfers: connect.NewClient[protocol.ListTransfersRequest, protocol.ListTransfersResponse](
			httpClient,
			baseURL+TransferServiceListTransfersProcedure,
			connect.WithSchema(transferServiceMethods.ByName("ListTransfers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// transferServiceClient implements TransferServiceClient.
type transferServiceClient struct {
	fetchBlob       *connect.Client[protocol.FetchBlobRequest, protocol.BlobSnapshot]
	listBlobSources *connect.Client[protocol.ListBlobSourcesRequest, protocol.ListBlobSourcesResponse]
	getTransfer     *connect.Client[protocol.GetTransferRequest, protocol.GetTransferResponse]
	listTransfers   *connect.Client[protocol.ListTransfersRequest, protocol.ListTransfersResponse]
}

// FetchBlob calls ardents.v1.TransferService.FetchBlob.
func (c *transferServiceClient) FetchBlob(ctx context.Context, req *connect.Request[protocol.FetchBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return c.fetchBlob.CallUnary(ctx, req)
}

// ListBlobSources calls ardents.v1.TransferService.ListBlobSources.
func (c *transferServiceClient) ListBlobSources(ctx context.Context, req *connect.Request[protocol.ListBlobSourcesRequest]) (*connect.Response[protocol.ListBlobSourcesResponse], error) {
	return c.listBlobSources.CallUnary(ctx, req)
}

// GetTransfer calls ardents.v1.TransferService.GetTransfer.
func (c *transferServiceClient) GetTransfer(ctx context.Context, req *connect.Request[protocol.GetTransferRequest]) (*connect.Response[protocol.GetTransferResponse], error) {
	return c.getTransfer.CallUnary(ctx, req)
}

// ListTransfers calls ardents.v1.TransferService.ListTransfers.
func (c *transferServiceClient) ListTransfers(ctx context.Context, req *connect.Request[protocol.ListTransfersRequest]) (*connect.Response[protocol.ListTransfersResponse], error) {
	return c.listTransfers.CallUnary(ctx, req)
}

// TransferServiceHandler is an implementation of the ardents.v1.TransferService service.
type TransferServiceHandler interface {
	FetchBlob(context.Context, *connect.Request[protocol.FetchBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error)
	ListBlobSources(context.Context, *connect.Request[protocol.ListBlobSourcesRequest]) (*connect.Response[protocol.ListBlobSourcesResponse], error)
	GetTransfer(context.Context, *connect.Request[protocol.GetTransferRequest]) (*connect.Response[protocol.GetTransferResponse], error)
	ListTransfers(context.Context, *connect.Request[protocol.ListTransfersRequest]) (*connect.Response[protocol.ListTransfersResponse], error)
}

// NewTransferServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTransferServiceHandler(svc TransferServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	transferServiceMethods := protocol.File_api_ardents_v1_transfer_proto.Services().ByName("TransferService").Methods()
	transferServiceFetchBlobHandler := connect.NewUnaryHandler(
		TransferServiceFetchBlobProcedure,
		svc.FetchBlob,
		connect.WithSchema(transferServiceMethods.ByName("FetchBlob")),
		connect.WithHandlerOptions(opts...),
	)
	transferServiceListBlobSourcesHandler := connect.NewUnaryHandler(
		TransferServiceListBlobSourcesProcedure,
		svc.ListBlobSources,
		connect.WithSchema(transferServiceMethods.ByName("ListBlobSources")),
		connect.WithHandlerOptions(opts...),
	)
	transferServiceGetTransferHandler := connect.NewUnaryHandler(
		TransferServiceGetTransferProcedure,
		svc.GetTransfer,
		connect.WithSchema(transferServiceMethods.ByName("GetTransfer")),
		connect.WithHandlerOptions(opts...),
	)
	transferServiceListTransfersHandler := connect.NewUnaryHandler(
		TransferServiceListTransfersProcedure,
		svc.ListTransfers,
		connect.WithSchema(transferServiceMethods.ByName("ListTransfers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.TransferService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TransferServiceFetchBlobProcedure:
			transferServiceFetchBlobHandler.ServeHTTP(w, r)
		case TransferServiceListBlobSourcesProcedure:
			transferServiceListBlobSourcesHandler.ServeHTTP(w, r)
		case TransferServiceGetTransferProcedure:
			transferServiceGetTransferHandler.ServeHTTP(w, r)
		case TransferServiceListTransfersProcedure:
			transferServiceListTransfersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTransferServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTransferServiceHandler struct{}

func (UnimplementedTransferServiceHandler) FetchBlob(context.Context, *connect.Request[protocol.FetchBlobRequest]) (*connect.Response[protocol.BlobSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.TransferService.FetchBlob is not implemented"))
}

func (UnimplementedTransferServiceHandler) ListBlobSources(context.Context, *connect.Request[protocol.ListBlobSourcesRequest]) (*connect.Response[protocol.ListBlobSourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.TransferService.ListBlobSources is not implemented"))
}

func (UnimplementedTransferServiceHandler) GetTransfer(context.Context, *connect.Request[protocol.GetTransferRequest]) (*connect.Response[protocol.GetTransferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.TransferService.GetTransfer is not implemented"))
}

func (UnimplementedTransferServiceHandler) ListTransfers(context.Context, *connect.Request[protocol.ListTransfersRequest]) (*connect.Response[protocol.ListTransfersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.TransferService.ListTransfers is not implemented"))
}
