// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/v1/workload.proto

package ardentsv1connect

import (
	protocol "ardents/internal/localapi/protocol"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkloadServiceName is the fully-qualified name of the WorkloadService service.
	WorkloadServiceName = "ardents.v1.WorkloadService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkloadServiceRegisterWorkloadProcedure is the fully-qualified name of the WorkloadService's
	// RegisterWorkload RPC.
	WorkloadServiceRegisterWorkloadProcedure = "/ardents.v1.WorkloadService/RegisterWorkload"
	// WorkloadServiceStartWorkloadProcedure is the fully-qualified name of the WorkloadService's
	// StartWorkload RPC.
	WorkloadServiceStartWorkloadProcedure = "/ardents.v1.WorkloadService/StartWorkload"
	// WorkloadServiceStopWorkloadProcedure is the fully-qualified name of the WorkloadService's
	// StopWorkload RPC.
	WorkloadServiceStopWorkloadProcedure = "/ardents.v1.WorkloadService/StopWorkload"
	// WorkloadServiceRestartWorkloadProcedure is the fully-qualified name of the WorkloadService's
	// RestartWorkload RPC.
	WorkloadServiceRestartWorkloadProcedure = "/ardents.v1.WorkloadService/RestartWorkload"
	// WorkloadServiceGetWorkloadStatusProcedure is the fully-qualified name of the WorkloadService's
	// GetWorkloadStatus RPC.
	WorkloadServiceGetWorkloadStatusProcedure = "/ardents.v1.WorkloadService/GetWorkloadStatus"
	// WorkloadServiceListWorkloadsProcedure is the fully-qualified name of the WorkloadService's
	// ListWorkloads RPC.
	WorkloadServiceListWorkloadsProcedure = "/ardents.v1.WorkloadService/ListWorkloads"
	// WorkloadServiceGetHostedServiceProcedure is the fully-qualified name of the WorkloadService's
	// GetHostedService RPC.
	WorkloadServiceGetHostedServiceProcedure = "/ardents.v1.WorkloadService/GetHostedService"
	// WorkloadServiceListHostedServicesProcedure is the fully-qualified name of the WorkloadService's
	// ListHostedServices RPC.
	WorkloadServiceListHostedServicesProcedure = "/ardents.v1.WorkloadService/ListHostedServices"
	// WorkloadServiceGetServicePublicationStatusProcedure is the fully-qualified name of the
	// WorkloadService's GetServicePublicationStatus RPC.
	WorkloadServiceGetServicePublicationStatusProcedure = "/ardents.v1.WorkloadService/GetServicePublicationStatus"
)

// WorkloadServiceClient is a client for the ardents.v1.WorkloadService service.
type WorkloadServiceClient interface {
	RegisterWorkload(context.Context, *connect.Request[protocol.RegisterWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	StartWorkload(context.Context, *connect.Request[protocol.StartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	StopWorkload(context.Context, *connect.Request[protocol.StopWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	RestartWorkload(context.Context, *connect.Request[protocol.RestartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	GetWorkloadStatus(context.Context, *connect.Request[protocol.GetWorkloadStatusRequest]) (*connect.Response[protocol.WorkloadStatusSnapshot], error)
	ListWorkloads(context.Context, *connect.Request[protocol.ListWorkloadsRequest]) (*connect.Response[protocol.ListWorkloadsResponse], error)
	GetHostedService(context.Context, *connect.Request[protocol.GetHostedServiceRequest]) (*connect.Response[protocol.GetHostedServiceResponse], error)
	ListHostedServices(context.Context, *connect.Request[protocol.ListHostedServicesRequest]) (*connect.Response[protocol.ListHostedServicesResponse], error)
	GetServicePublicationStatus(context.Context, *connect.Request[protocol.GetServicePublicationStatusRequest]) (*connect.Response[protocol.ServicePublicationStatusResponse], error)
}

// NewWorkloadServiceClient constructs a client for the ardents.v1.WorkloadService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkloadServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkloadServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workloadServiceMethods := protocol.File_api_ardents_v1_workload_proto.Services().ByName("WorkloadService").Methods()
	return &workloadServiceClient{
		registerWorkload: connect.NewClient[protocol.RegisterWorkloadRequest, protocol.WorkloadCommandResponse](
			httpClient,
			baseURL+WorkloadServiceRegisterWorkloadProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("RegisterWorkload")),
			connect.WithClientOptions(opts...),
		),
		startWorkload: connect.NewClient[protocol.StartWorkloadRequest, protocol.WorkloadCommandResponse](
			httpClient,
			baseURL+WorkloadServiceStartWorkloadProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("StartWorkload")),
			connect.WithClientOptions(opts...),
		),
		stopWorkload: connect.NewClient[protocol.StopWorkloadRequest, protocol.WorkloadCommandResponse](
			httpClient,
			baseURL+WorkloadServiceStopWorkloadProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("StopWorkload")),
			connect.WithClientOptions(opts...),
		),
		restartWorkload: connect.NewClient[protocol.RestartWorkloadRequest, protocol.WorkloadCommandResponse](
			httpClient,
			baseURL+WorkloadServiceRestartWorkloadProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("RestartWorkload")),
			connect.WithClientOptions(opts...),
		),
		getWorkloadStatus: connect.NewClient[protocol.GetWorkloadStatusRequest, protocol.WorkloadStatusSnapshot](
			httpClient,
			baseURL+WorkloadServiceGetWorkloadStatusProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("GetWorkloadStatus")),
			connect.WithClientOptions(opts...),
		),
		listWorkloads: connect.NewClient[protocol.ListWorkloadsRequest, protocol.ListWorkloadsResponse](
			httpClient,
			baseURL+WorkloadServiceListWorkloadsProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("ListWorkloads")),
			connect.WithClientOptions(opts...),
		),
		getHostedService: connect.NewClient[protocol.GetHostedServiceRequest, protocol.GetHostedServiceResponse](
			httpClient,
			baseURL+WorkloadServiceGetHostedServiceProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("GetHostedService")),
			connect.WithClientOptions(opts...),
		),
		listHostedServices: connect.NewClient[protocol.ListHostedServicesRequest, protocol.ListHostedServicesResponse](
			httpClient,
			baseURL+WorkloadServiceListHostedServicesProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("ListHostedServices")),
			connect.WithClientOptions(opts...),
		),
		getServicePublicationStatus: connect.NewClient[protocol.GetServicePublicationStatusRequest, protocol.ServicePublicationStatusResponse](
			httpClient,
			baseURL+WorkloadServiceGetServicePublicationStatusProcedure,
			connect.WithSchema(workloadServiceMethods.ByName("GetServicePublicationStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workloadServiceClient implements WorkloadServiceClient.
type workloadServiceClient struct {
	registerWorkload            *connect.Client[protocol.RegisterWorkloadRequest, protocol.WorkloadCommandResponse]
	startWorkload               *connect.Client[protocol.StartWorkloadRequest, protocol.WorkloadCommandResponse]
	stopWorkload                *connect.Client[protocol.StopWorkloadRequest, protocol.WorkloadCommandResponse]
	restartWorkload             *connect.Client[protocol.RestartWorkloadRequest, protocol.WorkloadCommandResponse]
	getWorkloadStatus           *connect.Client[protocol.GetWorkloadStatusRequest, protocol.WorkloadStatusSnapshot]
	listWorkloads               *connect.Client[protocol.ListWorkloadsRequest, protocol.ListWorkloadsResponse]
	getHostedService            *connect.Client[protocol.GetHostedServiceRequest, protocol.GetHostedServiceResponse]
	listHostedServices          *connect.Client[protocol.ListHostedServicesRequest, protocol.ListHostedServicesResponse]
	getServicePublicationStatus *connect.Client[protocol.GetServicePublicationStatusRequest, protocol.ServicePublicationStatusResponse]
}

// RegisterWorkload calls ardents.v1.WorkloadService.RegisterWorkload.
func (c *workloadServiceClient) RegisterWorkload(ctx context.Context, req *connect.Request[protocol.RegisterWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return c.registerWorkload.CallUnary(ctx, req)
}

// StartWorkload calls ardents.v1.WorkloadService.StartWorkload.
func (c *workloadServiceClient) StartWorkload(ctx context.Context, req *connect.Request[protocol.StartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return c.startWorkload.CallUnary(ctx, req)
}

// StopWorkload calls ardents.v1.WorkloadService.StopWorkload.
func (c *workloadServiceClient) StopWorkload(ctx context.Context, req *connect.Request[protocol.StopWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return c.stopWorkload.CallUnary(ctx, req)
}

// RestartWorkload calls ardents.v1.WorkloadService.RestartWorkload.
func (c *workloadServiceClient) RestartWorkload(ctx context.Context, req *connect.Request[protocol.RestartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return c.restartWorkload.CallUnary(ctx, req)
}

// GetWorkloadStatus calls ardents.v1.WorkloadService.GetWorkloadStatus.
func (c *workloadServiceClient) GetWorkloadStatus(ctx context.Context, req *connect.Request[protocol.GetWorkloadStatusRequest]) (*connect.Response[protocol.WorkloadStatusSnapshot], error) {
	return c.getWorkloadStatus.CallUnary(ctx, req)
}

// ListWorkloads calls ardents.v1.WorkloadService.ListWorkloads.
func (c *workloadServiceClient) ListWorkloads(ctx context.Context, req *connect.Request[protocol.ListWorkloadsRequest]) (*connect.Response[protocol.ListWorkloadsResponse], error) {
	return c.listWorkloads.CallUnary(ctx, req)
}

// GetHostedService calls ardents.v1.WorkloadService.GetHostedService.
func (c *workloadServiceClient) GetHostedService(ctx context.Context, req *connect.Request[protocol.GetHostedServiceRequest]) (*connect.Response[protocol.GetHostedServiceResponse], error) {
	return c.getHostedService.CallUnary(ctx, req)
}

// ListHostedServices calls ardents.v1.WorkloadService.ListHostedServices.
func (c *workloadServiceClient) ListHostedServices(ctx context.Context, req *connect.Request[protocol.ListHostedServicesRequest]) (*connect.Response[protocol.ListHostedServicesResponse], error) {
	return c.listHostedServices.CallUnary(ctx, req)
}

// GetServicePublicationStatus calls ardents.v1.WorkloadService.GetServicePublicationStatus.
func (c *workloadServiceClient) GetServicePublicationStatus(ctx context.Context, req *connect.Request[protocol.GetServicePublicationStatusRequest]) (*connect.Response[protocol.ServicePublicationStatusResponse], error) {
	return c.getServicePublicationStatus.CallUnary(ctx, req)
}

// WorkloadServiceHandler is an implementation of the ardents.v1.WorkloadService service.
type WorkloadServiceHandler interface {
	RegisterWorkload(context.Context, *connect.Request[protocol.RegisterWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	StartWorkload(context.Context, *connect.Request[protocol.StartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	StopWorkload(context.Context, *connect.Request[protocol.StopWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	RestartWorkload(context.Context, *connect.Request[protocol.RestartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error)
	GetWorkloadStatus(context.Context, *connect.Request[protocol.GetWorkloadStatusRequest]) (*connect.Response[protocol.WorkloadStatusSnapshot], error)
	ListWorkloads(context.Context, *connect.Request[protocol.ListWorkloadsRequest]) (*connect.Response[protocol.ListWorkloadsResponse], error)
	GetHostedService(context.Context, *connect.Request[protocol.GetHostedServiceRequest]) (*connect.Response[protocol.GetHostedServiceResponse], error)
	ListHostedServices(context.Context, *connect.Request[protocol.ListHostedServicesRequest]) (*connect.Response[protocol.ListHostedServicesResponse], error)
	GetServicePublicationStatus(context.Context, *connect.Request[protocol.GetServicePublicationStatusRequest]) (*connect.Response[protocol.ServicePublicationStatusResponse], error)
}

// NewWorkloadServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkloadServiceHandler(svc WorkloadServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workloadServiceMethods := protocol.File_api_ardents_v1_workload_proto.Services().ByName("WorkloadService").Methods()
	workloadServiceRegisterWorkloadHandler := connect.NewUnaryHandler(
		WorkloadServiceRegisterWorkloadProcedure,
		svc.RegisterWorkload,
		connect.WithSchema(workloadServiceMethods.ByName("RegisterWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceStartWorkloadHandler := connect.NewUnaryHandler(
		WorkloadServiceStartWorkloadProcedure,
		svc.StartWorkload,
		connect.WithSchema(workloadServiceMethods.ByName("StartWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceStopWorkloadHandler := connect.NewUnaryHandler(
		WorkloadServiceStopWorkloadProcedure,
		svc.StopWorkload,
		connect.WithSchema(workloadServiceMethods.ByName("StopWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceRestartWorkloadHandler := connect.NewUnaryHandler(
		WorkloadServiceRestartWorkloadProcedure,
		svc.RestartWorkload,
		connect.WithSchema(workloadServiceMethods.ByName("RestartWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceGetWorkloadStatusHandler := connect.NewUnaryHandler(
		WorkloadServiceGetWorkloadStatusProcedure,
		svc.GetWorkloadStatus,
		connect.WithSchema(workloadServiceMethods.ByName("GetWorkloadStatus")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceListWorkloadsHandler := connect.NewUnaryHandler(
		WorkloadServiceListWorkloadsProcedure,
		svc.ListWorkloads,
		connect.WithSchema(workloadServiceMethods.ByName("ListWorkloads")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceGetHostedServiceHandler := connect.NewUnaryHandler(
		WorkloadServiceGetHostedServiceProcedure,
		svc.GetHostedService,
		connect.WithSchema(workloadServiceMethods.ByName("GetHostedService")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceListHostedServicesHandler := connect.NewUnaryHandler(
		WorkloadServiceListHostedServicesProcedure,
		svc.ListHostedServices,
		connect.WithSchema(workloadServiceMethods.ByName("ListHostedServices")),
		connect.WithHandlerOptions(opts...),
	)
	workloadServiceGetServicePublicationStatusHandler := connect.NewUnaryHandler(
		WorkloadServiceGetServicePublicationStatusProcedure,
		svc.GetServicePublicationStatus,
		connect.WithSchema(workloadServiceMethods.ByName("GetServicePublicationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.v1.WorkloadService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkloadServiceRegisterWorkloadProcedure:
			workloadServiceRegisterWorkloadHandler.ServeHTTP(w, r)
		case WorkloadServiceStartWorkloadProcedure:
			workloadServiceStartWorkloadHandler.ServeHTTP(w, r)
		case WorkloadServiceStopWorkloadProcedure:
			workloadServiceStopWorkloadHandler.ServeHTTP(w, r)
		case WorkloadServiceRestartWorkloadProcedure:
			workloadServiceRestartWorkloadHandler.ServeHTTP(w, r)
		case WorkloadServiceGetWorkloadStatusProcedure:
			workloadServiceGetWorkloadStatusHandler.ServeHTTP(w, r)
		case WorkloadServiceListWorkloadsProcedure:
			workloadServiceListWorkloadsHandler.ServeHTTP(w, r)
		case WorkloadServiceGetHostedServiceProcedure:
			workloadServiceGetHostedServiceHandler.ServeHTTP(w, r)
		case WorkloadServiceListHostedServicesProcedure:
			workloadServiceListHostedServicesHandler.ServeHTTP(w, r)
		case WorkloadServiceGetServicePublicationStatusProcedure:
			workloadServiceGetServicePublicationStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkloadServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkloadServiceHandler struct{}

func (UnimplementedWorkloadServiceHandler) RegisterWorkload(context.Context, *connect.Request[protocol.RegisterWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.RegisterWorkload is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) StartWorkload(context.Context, *connect.Request[protocol.StartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.StartWorkload is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) StopWorkload(context.Context, *connect.Request[protocol.StopWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.StopWorkload is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) RestartWorkload(context.Context, *connect.Request[protocol.RestartWorkloadRequest]) (*connect.Response[protocol.WorkloadCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.RestartWorkload is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) GetWorkloadStatus(context.Context, *connect.Request[protocol.GetWorkloadStatusRequest]) (*connect.Response[protocol.WorkloadStatusSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.GetWorkloadStatus is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) ListWorkloads(context.Context, *connect.Request[protocol.ListWorkloadsRequest]) (*connect.Response[protocol.ListWorkloadsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.ListWorkloads is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) GetHostedService(context.Context, *connect.Request[protocol.GetHostedServiceRequest]) (*connect.Response[protocol.GetHostedServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.GetHostedService is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) ListHostedServices(context.Context, *connect.Request[protocol.ListHostedServicesRequest]) (*connect.Response[protocol.ListHostedServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.ListHostedServices is not implemented"))
}

func (UnimplementedWorkloadServiceHandler) GetServicePublicationStatus(context.Context, *connect.Request[protocol.GetServicePublicationStatusRequest]) (*connect.Response[protocol.ServicePublicationStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.v1.WorkloadService.GetServicePublicationStatus is not implemented"))
}
