// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/access.proto

package ardentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperatorAccess is the protocol-owned admission metadata consumed by the
// protected Operator Interface authorization interceptor.
type OperatorAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ResourceKind  string                 `protobuf:"bytes,3,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	Mutating      bool                   `protobuf:"varint,4,opt,name=mutating,proto3" json:"mutating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorAccess) Reset() {
	*x = OperatorAccess{}
	mi := &file_api_ardents_v1_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorAccess) ProtoMessage() {}

func (x *OperatorAccess) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorAccess.ProtoReflect.Descriptor instead.
func (*OperatorAccess) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorAccess) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OperatorAccess) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *OperatorAccess) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *OperatorAccess) GetMutating() bool {
	if x != nil {
		return x.Mutating
	}
	return false
}

var file_api_ardents_v1_access_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OperatorAccess)(nil),
		Field:         51000,
		Name:          "ardents.v1.operator_access",
		Tag:           "bytes,51000,opt,name=operator_access",
		Filename:      "api/ardents/v1/access.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional ardents.v1.OperatorAccess operator_access = 51000;
	E_OperatorAccess = &file_api_ardents_v1_access_proto_extTypes[0]
)

var File_api_ardents_v1_access_proto protoreflect.FileDescriptor

const file_api_ardents_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/ardents/v1/access.proto\x12\n" +
	"ardents.v1\x1a google/protobuf/descriptor.proto\"\x81\x01\n" +
	"\x0eOperatorAccess\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12#\n" +
	"\rresource_kind\x18\x03 \x01(\tR\fresourceKind\x12\x1a\n" +
	"\bmutating\x18\x04 \x01(\bR\bmutating:e\n" +
	"\x0foperator_access\x12\x1e.google.protobuf.MethodOptions\x18\xb8\x8e\x03 \x01(\v2\x1a.ardents.v1.OperatorAccessR\x0eoperatorAccessB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var (
	file_api_ardents_v1_access_proto_rawDescOnce sync.Once
	file_api_ardents_v1_access_proto_rawDescData []byte
)

func file_api_ardents_v1_access_proto_rawDescGZIP() []byte {
	file_api_ardents_v1_access_proto_rawDescOnce.Do(func() {
		file_api_ardents_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_v1_access_proto_rawDesc), len(file_api_ardents_v1_access_proto_rawDesc)))
	})
	return file_api_ardents_v1_access_proto_rawDescData
}

var file_api_ardents_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_ardents_v1_access_proto_goTypes = []any{
	(*OperatorAccess)(nil),             // 0: ardents.v1.OperatorAccess
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_api_ardents_v1_access_proto_depIdxs = []int32{
	1, // 0: ardents.v1.operator_access:extendee -> google.protobuf.MethodOptions
	0, // 1: ardents.v1.operator_access:type_name -> ardents.v1.OperatorAccess
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_access_proto_init() }
func file_api_ardents_v1_access_proto_init() {
	if File_api_ardents_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_access_proto_rawDesc), len(file_api_ardents_v1_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_api_ardents_v1_access_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_access_proto_depIdxs,
		MessageInfos:      file_api_ardents_v1_access_proto_msgTypes,
		ExtensionInfos:    file_api_ardents_v1_access_proto_extTypes,
	}.Build()
	File_api_ardents_v1_access_proto = out.File
	file_api_ardents_v1_access_proto_goTypes = nil
	file_api_ardents_v1_access_proto_depIdxs = nil
}
