// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/authority.proto

package ardentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRealmAuthorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RealmClass    string                 `protobuf:"bytes,3,opt,name=realm_class,json=realmClass,proto3" json:"realm_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRealmAuthorityRequest) Reset() {
	*x = CreateRealmAuthorityRequest{}
	mi := &file_api_ardents_v1_authority_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRealmAuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmAuthorityRequest) ProtoMessage() {}

func (x *CreateRealmAuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_authority_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmAuthorityRequest.ProtoReflect.Descriptor instead.
func (*CreateRealmAuthorityRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_authority_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRealmAuthorityRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateRealmAuthorityRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateRealmAuthorityRequest) GetRealmClass() string {
	if x != nil {
		return x.RealmClass
	}
	return ""
}

type InspectRealmAuthorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	RealmId       string                 `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRealmAuthorityRequest) Reset() {
	*x = InspectRealmAuthorityRequest{}
	mi := &file_api_ardents_v1_authority_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRealmAuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRealmAuthorityRequest) ProtoMessage() {}

func (x *InspectRealmAuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_authority_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRealmAuthorityRequest.ProtoReflect.Descriptor instead.
func (*InspectRealmAuthorityRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_authority_proto_rawDescGZIP(), []int{1}
}

func (x *InspectRealmAuthorityRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InspectRealmAuthorityRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

type AuthorityStatusSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Version               uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SchemaVersion         uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RealmId               string                 `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	RealmClass            string                 `protobuf:"bytes,4,opt,name=realm_class,json=realmClass,proto3" json:"realm_class,omitempty"`
	AuthorityEpoch        uint64                 `protobuf:"varint,5,opt,name=authority_epoch,json=authorityEpoch,proto3" json:"authority_epoch,omitempty"`
	AuthoritySequence     uint64                 `protobuf:"varint,6,opt,name=authority_sequence,json=authoritySequence,proto3" json:"authority_sequence,omitempty"`
	CheckpointDigest      string                 `protobuf:"bytes,7,opt,name=checkpoint_digest,json=checkpointDigest,proto3" json:"checkpoint_digest,omitempty"`
	Phase                 string                 `protobuf:"bytes,8,opt,name=phase,proto3" json:"phase,omitempty"`
	Readiness             string                 `protobuf:"bytes,9,opt,name=readiness,proto3" json:"readiness,omitempty"`
	Reason                string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	MemberCount           uint32                 `protobuf:"varint,11,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	ChannelCount          uint32                 `protobuf:"varint,12,opt,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty"`
	PendingOperationCount uint32                 `protobuf:"varint,13,opt,name=pending_operation_count,json=pendingOperationCount,proto3" json:"pending_operation_count,omitempty"`
	AuditOutboxDepth      uint32                 `protobuf:"varint,14,opt,name=audit_outbox_depth,json=auditOutboxDepth,proto3" json:"audit_outbox_depth,omitempty"`
	CurrentGeneration     uint32                 `protobuf:"varint,15,opt,name=current_generation,json=currentGeneration,proto3" json:"current_generation,omitempty"`
	OperationDeadline     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=operation_deadline,json=operationDeadline,proto3" json:"operation_deadline,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthorityStatusSnapshot) Reset() {
	*x = AuthorityStatusSnapshot{}
	mi := &file_api_ardents_v1_authority_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityStatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityStatusSnapshot) ProtoMessage() {}

func (x *AuthorityStatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_authority_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityStatusSnapshot.ProtoReflect.Descriptor instead.
func (*AuthorityStatusSnapshot) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_authority_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorityStatusSnapshot) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *AuthorityStatusSnapshot) GetRealmClass() string {
	if x != nil {
		return x.RealmClass
	}
	return ""
}

func (x *AuthorityStatusSnapshot) GetAuthorityEpoch() uint64 {
	if x != nil {
		return x.AuthorityEpoch
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetAuthoritySequence() uint64 {
	if x != nil {
		return x.AuthoritySequence
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetCheckpointDigest() string {
	if x != nil {
		return x.CheckpointDigest
	}
	return ""
}

func (x *AuthorityStatusSnapshot) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AuthorityStatusSnapshot) GetReadiness() string {
	if x != nil {
		return x.Readiness
	}
	return ""
}

func (x *AuthorityStatusSnapshot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthorityStatusSnapshot) GetMemberCount() uint32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetChannelCount() uint32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetPendingOperationCount() uint32 {
	if x != nil {
		return x.PendingOperationCount
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetAuditOutboxDepth() uint32 {
	if x != nil {
		return x.AuditOutboxDepth
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetCurrentGeneration() uint32 {
	if x != nil {
		return x.CurrentGeneration
	}
	return 0
}

func (x *AuthorityStatusSnapshot) GetOperationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.OperationDeadline
	}
	return nil
}

type CreateRealmAuthorityResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *OperationStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Authority     *AuthorityStatusSnapshot `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	OperationId   string                   `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRealmAuthorityResponse) Reset() {
	*x = CreateRealmAuthorityResponse{}
	mi := &file_api_ardents_v1_authority_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRealmAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmAuthorityResponse) ProtoMessage() {}

func (x *CreateRealmAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_authority_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmAuthorityResponse.ProtoReflect.Descriptor instead.
func (*CreateRealmAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_authority_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRealmAuthorityResponse) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateRealmAuthorityResponse) GetAuthority() *AuthorityStatusSnapshot {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *CreateRealmAuthorityResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type InspectRealmAuthorityResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *OperationStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Authority     *AuthorityStatusSnapshot `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRealmAuthorityResponse) Reset() {
	*x = InspectRealmAuthorityResponse{}
	mi := &file_api_ardents_v1_authority_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRealmAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRealmAuthorityResponse) ProtoMessage() {}

func (x *InspectRealmAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_authority_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRealmAuthorityResponse.ProtoReflect.Descriptor instead.
func (*InspectRealmAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_authority_proto_rawDescGZIP(), []int{4}
}

func (x *InspectRealmAuthorityResponse) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InspectRealmAuthorityResponse) GetAuthority() *AuthorityStatusSnapshot {
	if x != nil {
		return x.Authority
	}
	return nil
}

var File_api_ardents_v1_authority_proto protoreflect.FileDescriptor

const file_api_ardents_v1_authority_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/ardents/v1/authority.proto\x12\n" +
	"ardents.v1\x1a\x1aapi/ardents/v1/types.proto\x1a\x1bapi/ardents/v1/access.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x1bCreateRealmAuthorityRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vrealm_class\x18\x03 \x01(\tR\n" +
	"realmClass\"S\n" +
	"\x1cInspectRealmAuthorityRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\tR\arealmId\"\x8f\x05\n" +
	"\x17AuthorityStatusSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\x12\x1f\n" +
	"\vrealm_class\x18\x04 \x01(\tR\n" +
	"realmClass\x12'\n" +
	"\x0fauthority_epoch\x18\x05 \x01(\x04R\x0eauthorityEpoch\x12-\n" +
	"\x12authority_sequence\x18\x06 \x01(\x04R\x11authoritySequence\x12+\n" +
	"\x11checkpoint_digest\x18\a \x01(\tR\x10checkpointDigest\x12\x14\n" +
	"\x05phase\x18\b \x01(\tR\x05phase\x12\x1c\n" +
	"\treadiness\x18\t \x01(\tR\treadiness\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12!\n" +
	"\fmember_count\x18\v \x01(\rR\vmemberCount\x12#\n" +
	"\rchannel_count\x18\f \x01(\rR\fchannelCount\x126\n" +
	"\x17pending_operation_count\x18\r \x01(\rR\x15pendingOperationCount\x12,\n" +
	"\x12audit_outbox_depth\x18\x0e \x01(\rR\x10auditOutboxDepth\x12-\n" +
	"\x12current_generation\x18\x0f \x01(\rR\x11currentGeneration\x12I\n" +
	"\x12operation_deadline\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x11operationDeadline\"\xb9\x01\n" +
	"\x1cCreateRealmAuthorityResponse\x123\n" +
	"\x06status\x18\x01 \x01(\v2\x1b.ardents.v1.OperationStatusR\x06status\x12A\n" +
	"\tauthority\x18\x02 \x01(\v2#.ardents.v1.AuthorityStatusSnapshotR\tauthority\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\"\x97\x01\n" +
	"\x1dInspectRealmAuthorityResponse\x123\n" +
	"\x06status\x18\x01 \x01(\v2\x1b.ardents.v1.OperationStatusR\x06status\x12A\n" +
	"\tauthority\x18\x02 \x01(\v2#.ardents.v1.AuthorityStatusSnapshotR\tauthority2\xe4\x02\n" +
	"\x10AuthorityService\x12\xae\x01\n" +
	"\x14CreateRealmAuthority\x12'.ardents.v1.CreateRealmAuthorityRequest\x1a(.ardents.v1.CreateRealmAuthorityResponse\"C\xc2\xf3\x18?\n" +
	"\x16realm.authority.create\x12\tauthority\x1a\x18realm-authority-instance \x01\x12\x9e\x01\n" +
	"\x15InspectRealmAuthority\x12(.ardents.v1.InspectRealmAuthorityRequest\x1a).ardents.v1.InspectRealmAuthorityResponse\"0\xc2\xf3\x18,\n" +
	"\x18realm.channel.audit.read\x12\tauthority\x1a\x05realmB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var (
	file_api_ardents_v1_authority_proto_rawDescOnce sync.Once
	file_api_ardents_v1_authority_proto_rawDescData []byte
)

func file_api_ardents_v1_authority_proto_rawDescGZIP() []byte {
	file_api_ardents_v1_authority_proto_rawDescOnce.Do(func() {
		file_api_ardents_v1_authority_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_v1_authority_proto_rawDesc), len(file_api_ardents_v1_authority_proto_rawDesc)))
	})
	return file_api_ardents_v1_authority_proto_rawDescData
}

var file_api_ardents_v1_authority_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_ardents_v1_authority_proto_goTypes = []any{
	(*CreateRealmAuthorityRequest)(nil),   // 0: ardents.v1.CreateRealmAuthorityRequest
	(*InspectRealmAuthorityRequest)(nil),  // 1: ardents.v1.InspectRealmAuthorityRequest
	(*AuthorityStatusSnapshot)(nil),       // 2: ardents.v1.AuthorityStatusSnapshot
	(*CreateRealmAuthorityResponse)(nil),  // 3: ardents.v1.CreateRealmAuthorityResponse
	(*InspectRealmAuthorityResponse)(nil), // 4: ardents.v1.InspectRealmAuthorityResponse
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
	(*OperationStatus)(nil),               // 6: ardents.v1.OperationStatus
}
var file_api_ardents_v1_authority_proto_depIdxs = []int32{
	5, // 0: ardents.v1.AuthorityStatusSnapshot.operation_deadline:type_name -> google.protobuf.Timestamp
	6, // 1: ardents.v1.CreateRealmAuthorityResponse.status:type_name -> ardents.v1.OperationStatus
	2, // 2: ardents.v1.CreateRealmAuthorityResponse.authority:type_name -> ardents.v1.AuthorityStatusSnapshot
	6, // 3: ardents.v1.InspectRealmAuthorityResponse.status:type_name -> ardents.v1.OperationStatus
	2, // 4: ardents.v1.InspectRealmAuthorityResponse.authority:type_name -> ardents.v1.AuthorityStatusSnapshot
	0, // 5: ardents.v1.AuthorityService.CreateRealmAuthority:input_type -> ardents.v1.CreateRealmAuthorityRequest
	1, // 6: ardents.v1.AuthorityService.InspectRealmAuthority:input_type -> ardents.v1.InspectRealmAuthorityRequest
	3, // 7: ardents.v1.AuthorityService.CreateRealmAuthority:output_type -> ardents.v1.CreateRealmAuthorityResponse
	4, // 8: ardents.v1.AuthorityService.InspectRealmAuthority:output_type -> ardents.v1.InspectRealmAuthorityResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_authority_proto_init() }
func file_api_ardents_v1_authority_proto_init() {
	if File_api_ardents_v1_authority_proto != nil {
		return
	}
	file_api_ardents_v1_types_proto_init()
	file_api_ardents_v1_access_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_authority_proto_rawDesc), len(file_api_ardents_v1_authority_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_v1_authority_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_authority_proto_depIdxs,
		MessageInfos:      file_api_ardents_v1_authority_proto_msgTypes,
	}.Build()
	File_api_ardents_v1_authority_proto = out.File
	file_api_ardents_v1_authority_proto_goTypes = nil
	file_api_ardents_v1_authority_proto_depIdxs = nil
}
