// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/content.proto

package ardentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_ardents_v1_content_proto protoreflect.FileDescriptor

const file_api_ardents_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1capi/ardents/v1/content.proto\x12\n" +
	"ardents.v1\x1a\x1aapi/ardents/v1/types.proto2\x9e\x06\n" +
	"\x0eContentService\x12M\n" +
	"\rPublishObject\x12 .ardents.v1.PublishObjectRequest\x1a\x1a.ardents.v1.ObjectSnapshot\x12E\n" +
	"\tGetObject\x12\x1c.ardents.v1.GetObjectRequest\x1a\x1a.ardents.v1.ObjectSnapshot\x12N\n" +
	"\vListObjects\x12\x1e.ardents.v1.ListObjectsRequest\x1a\x1f.ardents.v1.ListObjectsResponse\x12G\n" +
	"\vPublishBlob\x12\x1e.ardents.v1.PublishBlobRequest\x1a\x18.ardents.v1.BlobSnapshot\x12?\n" +
	"\aGetBlob\x12\x1a.ardents.v1.GetBlobRequest\x1a\x18.ardents.v1.BlobSnapshot\x12H\n" +
	"\tListBlobs\x12\x1c.ardents.v1.ListBlobsRequest\x1a\x1d.ardents.v1.ListBlobsResponse\x12S\n" +
	"\x0fPublishManifest\x12\".ardents.v1.PublishManifestRequest\x1a\x1c.ardents.v1.ManifestSnapshot\x12K\n" +
	"\vGetManifest\x12\x1e.ardents.v1.GetManifestRequest\x1a\x1c.ardents.v1.ManifestSnapshot\x12T\n" +
	"\rListManifests\x12 .ardents.v1.ListManifestsRequest\x1a!.ardents.v1.ListManifestsResponse\x12Z\n" +
	"\x10GetDataInventory\x12#.ardents.v1.GetDataInventoryRequest\x1a!.ardents.v1.DataInventorySnapshotB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var file_api_ardents_v1_content_proto_goTypes = []any{
	(*PublishObjectRequest)(nil),    // 0: ardents.v1.PublishObjectRequest
	(*GetObjectRequest)(nil),        // 1: ardents.v1.GetObjectRequest
	(*ListObjectsRequest)(nil),      // 2: ardents.v1.ListObjectsRequest
	(*PublishBlobRequest)(nil),      // 3: ardents.v1.PublishBlobRequest
	(*GetBlobRequest)(nil),          // 4: ardents.v1.GetBlobRequest
	(*ListBlobsRequest)(nil),        // 5: ardents.v1.ListBlobsRequest
	(*PublishManifestRequest)(nil),  // 6: ardents.v1.PublishManifestRequest
	(*GetManifestRequest)(nil),      // 7: ardents.v1.GetManifestRequest
	(*ListManifestsRequest)(nil),    // 8: ardents.v1.ListManifestsRequest
	(*GetDataInventoryRequest)(nil), // 9: ardents.v1.GetDataInventoryRequest
	(*ObjectSnapshot)(nil),          // 10: ardents.v1.ObjectSnapshot
	(*ListObjectsResponse)(nil),     // 11: ardents.v1.ListObjectsResponse
	(*BlobSnapshot)(nil),            // 12: ardents.v1.BlobSnapshot
	(*ListBlobsResponse)(nil),       // 13: ardents.v1.ListBlobsResponse
	(*ManifestSnapshot)(nil),        // 14: ardents.v1.ManifestSnapshot
	(*ListManifestsResponse)(nil),   // 15: ardents.v1.ListManifestsResponse
	(*DataInventorySnapshot)(nil),   // 16: ardents.v1.DataInventorySnapshot
}
var file_api_ardents_v1_content_proto_depIdxs = []int32{
	0,  // 0: ardents.v1.ContentService.PublishObject:input_type -> ardents.v1.PublishObjectRequest
	1,  // 1: ardents.v1.ContentService.GetObject:input_type -> ardents.v1.GetObjectRequest
	2,  // 2: ardents.v1.ContentService.ListObjects:input_type -> ardents.v1.ListObjectsRequest
	3,  // 3: ardents.v1.ContentService.PublishBlob:input_type -> ardents.v1.PublishBlobRequest
	4,  // 4: ardents.v1.ContentService.GetBlob:input_type -> ardents.v1.GetBlobRequest
	5,  // 5: ardents.v1.ContentService.ListBlobs:input_type -> ardents.v1.ListBlobsRequest
	6,  // 6: ardents.v1.ContentService.PublishManifest:input_type -> ardents.v1.PublishManifestRequest
	7,  // 7: ardents.v1.ContentService.GetManifest:input_type -> ardents.v1.GetManifestRequest
	8,  // 8: ardents.v1.ContentService.ListManifests:input_type -> ardents.v1.ListManifestsRequest
	9,  // 9: ardents.v1.ContentService.GetDataInventory:input_type -> ardents.v1.GetDataInventoryRequest
	10, // 10: ardents.v1.ContentService.PublishObject:output_type -> ardents.v1.ObjectSnapshot
	10, // 11: ardents.v1.ContentService.GetObject:output_type -> ardents.v1.ObjectSnapshot
	11, // 12: ardents.v1.ContentService.ListObjects:output_type -> ardents.v1.ListObjectsResponse
	12, // 13: ardents.v1.ContentService.PublishBlob:output_type -> ardents.v1.BlobSnapshot
	12, // 14: ardents.v1.ContentService.GetBlob:output_type -> ardents.v1.BlobSnapshot
	13, // 15: ardents.v1.ContentService.ListBlobs:output_type -> ardents.v1.ListBlobsResponse
	14, // 16: ardents.v1.ContentService.PublishManifest:output_type -> ardents.v1.ManifestSnapshot
	14, // 17: ardents.v1.ContentService.GetManifest:output_type -> ardents.v1.ManifestSnapshot
	15, // 18: ardents.v1.ContentService.ListManifests:output_type -> ardents.v1.ListManifestsResponse
	16, // 19: ardents.v1.ContentService.GetDataInventory:output_type -> ardents.v1.DataInventorySnapshot
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_content_proto_init() }
func file_api_ardents_v1_content_proto_init() {
	if File_api_ardents_v1_content_proto != nil {
		return
	}
	file_api_ardents_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_content_proto_rawDesc), len(file_api_ardents_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_v1_content_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_content_proto_depIdxs,
	}.Build()
	File_api_ardents_v1_content_proto = out.File
	file_api_ardents_v1_content_proto_goTypes = nil
	file_api_ardents_v1_content_proto_depIdxs = nil
}
