// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/diagnostics.proto

package ardentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_ardents_v1_diagnostics_proto protoreflect.FileDescriptor

const file_api_ardents_v1_diagnostics_proto_rawDesc = "" +
	"\n" +
	" api/ardents/v1/diagnostics.proto\x12\n" +
	"ardents.v1\x1a\x1aapi/ardents/v1/types.proto2\xec\x03\n" +
	"\x12DiagnosticsService\x12\\\n" +
	"\x0eGetDiagnostics\x12!.ardents.v1.GetDiagnosticsRequest\x1a'.ardents.v1.DiagnosticsSnapshotResponse\x12f\n" +
	"\x14GetPendingOperations\x12'.ardents.v1.GetPendingOperationsRequest\x1a%.ardents.v1.PendingOperationsResponse\x12Z\n" +
	"\x10GetHealthSummary\x12#.ardents.v1.GetHealthSummaryRequest\x1a!.ardents.v1.HealthSummaryResponse\x12[\n" +
	"\x0eExplainFailure\x12!.ardents.v1.ExplainFailureRequest\x1a&.ardents.v1.FailureExplanationResponse\x12W\n" +
	"\x10ListRecentEvents\x12#.ardents.v1.ListRecentEventsRequest\x1a\x1e.ardents.v1.ListEventsResponseB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var file_api_ardents_v1_diagnostics_proto_goTypes = []any{
	(*GetDiagnosticsRequest)(nil),       // 0: ardents.v1.GetDiagnosticsRequest
	(*GetPendingOperationsRequest)(nil), // 1: ardents.v1.GetPendingOperationsRequest
	(*GetHealthSummaryRequest)(nil),     // 2: ardents.v1.GetHealthSummaryRequest
	(*ExplainFailureRequest)(nil),       // 3: ardents.v1.ExplainFailureRequest
	(*ListRecentEventsRequest)(nil),     // 4: ardents.v1.ListRecentEventsRequest
	(*DiagnosticsSnapshotResponse)(nil), // 5: ardents.v1.DiagnosticsSnapshotResponse
	(*PendingOperationsResponse)(nil),   // 6: ardents.v1.PendingOperationsResponse
	(*HealthSummaryResponse)(nil),       // 7: ardents.v1.HealthSummaryResponse
	(*FailureExplanationResponse)(nil),  // 8: ardents.v1.FailureExplanationResponse
	(*ListEventsResponse)(nil),          // 9: ardents.v1.ListEventsResponse
}
var file_api_ardents_v1_diagnostics_proto_depIdxs = []int32{
	0, // 0: ardents.v1.DiagnosticsService.GetDiagnostics:input_type -> ardents.v1.GetDiagnosticsRequest
	1, // 1: ardents.v1.DiagnosticsService.GetPendingOperations:input_type -> ardents.v1.GetPendingOperationsRequest
	2, // 2: ardents.v1.DiagnosticsService.GetHealthSummary:input_type -> ardents.v1.GetHealthSummaryRequest
	3, // 3: ardents.v1.DiagnosticsService.ExplainFailure:input_type -> ardents.v1.ExplainFailureRequest
	4, // 4: ardents.v1.DiagnosticsService.ListRecentEvents:input_type -> ardents.v1.ListRecentEventsRequest
	5, // 5: ardents.v1.DiagnosticsService.GetDiagnostics:output_type -> ardents.v1.DiagnosticsSnapshotResponse
	6, // 6: ardents.v1.DiagnosticsService.GetPendingOperations:output_type -> ardents.v1.PendingOperationsResponse
	7, // 7: ardents.v1.DiagnosticsService.GetHealthSummary:output_type -> ardents.v1.HealthSummaryResponse
	8, // 8: ardents.v1.DiagnosticsService.ExplainFailure:output_type -> ardents.v1.FailureExplanationResponse
	9, // 9: ardents.v1.DiagnosticsService.ListRecentEvents:output_type -> ardents.v1.ListEventsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_diagnostics_proto_init() }
func file_api_ardents_v1_diagnostics_proto_init() {
	if File_api_ardents_v1_diagnostics_proto != nil {
		return
	}
	file_api_ardents_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_diagnostics_proto_rawDesc), len(file_api_ardents_v1_diagnostics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_v1_diagnostics_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_diagnostics_proto_depIdxs,
	}.Build()
	File_api_ardents_v1_diagnostics_proto = out.File
	file_api_ardents_v1_diagnostics_proto_goTypes = nil
	file_api_ardents_v1_diagnostics_proto_depIdxs = nil
}
