// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/identity.proto

package ardentsv1

import (
	protocol "ardents/internal/identity/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginAuthenticationRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PrincipalId   string                    `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Purpose       protocol.ChallengePurpose `protobuf:"varint,2,opt,name=purpose,proto3,enum=ardents.identity.v1.ChallengePurpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthenticationRequest) Reset() {
	*x = BeginAuthenticationRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthenticationRequest) ProtoMessage() {}

func (x *BeginAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*BeginAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *BeginAuthenticationRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *BeginAuthenticationRequest) GetPurpose() protocol.ChallengePurpose {
	if x != nil {
		return x.Purpose
	}
	return protocol.ChallengePurpose(0)
}

type BeginAuthenticationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Challenge     *protocol.ChallengeFields `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthenticationResponse) Reset() {
	*x = BeginAuthenticationResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthenticationResponse) ProtoMessage() {}

func (x *BeginAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*BeginAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *BeginAuthenticationResponse) GetChallenge() *protocol.ChallengeFields {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type CompleteAuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	RootPublicKey []byte                 `protobuf:"bytes,3,opt,name=root_public_key,json=rootPublicKey,proto3" json:"root_public_key,omitempty"`
	Credential    []byte                 `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthenticationRequest) Reset() {
	*x = CompleteAuthenticationRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthenticationRequest) ProtoMessage() {}

func (x *CompleteAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*CompleteAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteAuthenticationRequest) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *CompleteAuthenticationRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *CompleteAuthenticationRequest) GetRootPublicKey() []byte {
	if x != nil {
		return x.RootPublicKey
	}
	return nil
}

func (x *CompleteAuthenticationRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CompleteAuthenticationRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CompleteAuthenticationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionSecret   []byte                 `protobuf:"bytes,1,opt,name=session_secret,json=sessionSecret,proto3" json:"session_secret,omitempty"`
	EnrollmentProof []byte                 `protobuf:"bytes,2,opt,name=enrollment_proof,json=enrollmentProof,proto3" json:"enrollment_proof,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteAuthenticationResponse) Reset() {
	*x = CompleteAuthenticationResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthenticationResponse) ProtoMessage() {}

func (x *CompleteAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*CompleteAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteAuthenticationResponse) GetSessionSecret() []byte {
	if x != nil {
		return x.SessionSecret
	}
	return nil
}

func (x *CompleteAuthenticationResponse) GetEnrollmentProof() []byte {
	if x != nil {
		return x.EnrollmentProof
	}
	return nil
}

func (x *CompleteAuthenticationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteAuthenticationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type EnrollFirstPrincipalRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	BootstrapTicket []byte                    `protobuf:"bytes,1,opt,name=bootstrap_ticket,json=bootstrapTicket,proto3" json:"bootstrap_ticket,omitempty"`
	Challenge       *protocol.ChallengeFields `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	EnrollmentProof []byte                    `protobuf:"bytes,3,opt,name=enrollment_proof,json=enrollmentProof,proto3" json:"enrollment_proof,omitempty"`
	RootPublicKey   []byte                    `protobuf:"bytes,4,opt,name=root_public_key,json=rootPublicKey,proto3" json:"root_public_key,omitempty"`
	Credential      []byte                    `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollFirstPrincipalRequest) Reset() {
	*x = EnrollFirstPrincipalRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollFirstPrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollFirstPrincipalRequest) ProtoMessage() {}

func (x *EnrollFirstPrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollFirstPrincipalRequest.ProtoReflect.Descriptor instead.
func (*EnrollFirstPrincipalRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollFirstPrincipalRequest) GetBootstrapTicket() []byte {
	if x != nil {
		return x.BootstrapTicket
	}
	return nil
}

func (x *EnrollFirstPrincipalRequest) GetChallenge() *protocol.ChallengeFields {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *EnrollFirstPrincipalRequest) GetEnrollmentProof() []byte {
	if x != nil {
		return x.EnrollmentProof
	}
	return nil
}

func (x *EnrollFirstPrincipalRequest) GetRootPublicKey() []byte {
	if x != nil {
		return x.RootPublicKey
	}
	return nil
}

func (x *EnrollFirstPrincipalRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type EnrollFirstPrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollFirstPrincipalResponse) Reset() {
	*x = EnrollFirstPrincipalResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollFirstPrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollFirstPrincipalResponse) ProtoMessage() {}

func (x *EnrollFirstPrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollFirstPrincipalResponse.ProtoReflect.Descriptor instead.
func (*EnrollFirstPrincipalResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollFirstPrincipalResponse) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

type EnrollPrincipalRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	RequestId       string                    `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Challenge       *protocol.ChallengeFields `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	EnrollmentProof []byte                    `protobuf:"bytes,3,opt,name=enrollment_proof,json=enrollmentProof,proto3" json:"enrollment_proof,omitempty"`
	RootPublicKey   []byte                    `protobuf:"bytes,4,opt,name=root_public_key,json=rootPublicKey,proto3" json:"root_public_key,omitempty"`
	Credential      []byte                    `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollPrincipalRequest) Reset() {
	*x = EnrollPrincipalRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollPrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollPrincipalRequest) ProtoMessage() {}

func (x *EnrollPrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollPrincipalRequest.ProtoReflect.Descriptor instead.
func (*EnrollPrincipalRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollPrincipalRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnrollPrincipalRequest) GetChallenge() *protocol.ChallengeFields {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *EnrollPrincipalRequest) GetEnrollmentProof() []byte {
	if x != nil {
		return x.EnrollmentProof
	}
	return nil
}

func (x *EnrollPrincipalRequest) GetRootPublicKey() []byte {
	if x != nil {
		return x.RootPublicKey
	}
	return nil
}

func (x *EnrollPrincipalRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type EnrollPrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollPrincipalResponse) Reset() {
	*x = EnrollPrincipalResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollPrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollPrincipalResponse) ProtoMessage() {}

func (x *EnrollPrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollPrincipalResponse.ProtoReflect.Descriptor instead.
func (*EnrollPrincipalResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *EnrollPrincipalResponse) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

type RevokeDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceRequest) Reset() {
	*x = RevokeDeviceRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceRequest) ProtoMessage() {}

func (x *RevokeDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceRequest.ProtoReflect.Descriptor instead.
func (*RevokeDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeDeviceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RevokeDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevocationId  string                 `protobuf:"bytes,1,opt,name=revocation_id,json=revocationId,proto3" json:"revocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceResponse) Reset() {
	*x = RevokeDeviceResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResponse) ProtoMessage() {}

func (x *RevokeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResponse.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeDeviceResponse) GetRevocationId() string {
	if x != nil {
		return x.RevocationId
	}
	return ""
}

type ListDeviceRevocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceRevocationsRequest) Reset() {
	*x = ListDeviceRevocationsRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceRevocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceRevocationsRequest) ProtoMessage() {}

func (x *ListDeviceRevocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceRevocationsRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceRevocationsRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *ListDeviceRevocationsRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

type DeviceRevocationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRevocationMetadata) Reset() {
	*x = DeviceRevocationMetadata{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRevocationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRevocationMetadata) ProtoMessage() {}

func (x *DeviceRevocationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRevocationMetadata.ProtoReflect.Descriptor instead.
func (*DeviceRevocationMetadata) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceRevocationMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceRevocationMetadata) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *DeviceRevocationMetadata) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRevocationMetadata) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type ListDeviceRevocationsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Revocations   []*DeviceRevocationMetadata `protobuf:"bytes,1,rep,name=revocations,proto3" json:"revocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceRevocationsResponse) Reset() {
	*x = ListDeviceRevocationsResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceRevocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceRevocationsResponse) ProtoMessage() {}

func (x *ListDeviceRevocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceRevocationsResponse.ProtoReflect.Descriptor instead.
func (*ListDeviceRevocationsResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ListDeviceRevocationsResponse) GetRevocations() []*DeviceRevocationMetadata {
	if x != nil {
		return x.Revocations
	}
	return nil
}

type AccessGrantProposal struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	SubjectPrincipalId string                  `protobuf:"bytes,1,opt,name=subject_principal_id,json=subjectPrincipalId,proto3" json:"subject_principal_id,omitempty"`
	Actions            []string                `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Scope              *protocol.ResourceScope `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	NotBefore          *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter           *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessGrantProposal) Reset() {
	*x = AccessGrantProposal{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGrantProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGrantProposal) ProtoMessage() {}

func (x *AccessGrantProposal) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGrantProposal.ProtoReflect.Descriptor instead.
func (*AccessGrantProposal) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *AccessGrantProposal) GetSubjectPrincipalId() string {
	if x != nil {
		return x.SubjectPrincipalId
	}
	return ""
}

func (x *AccessGrantProposal) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AccessGrantProposal) GetScope() *protocol.ResourceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AccessGrantProposal) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *AccessGrantProposal) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type IssueAccessGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Proposal      *AccessGrantProposal   `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAccessGrantRequest) Reset() {
	*x = IssueAccessGrantRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAccessGrantRequest) ProtoMessage() {}

func (x *IssueAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*IssueAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *IssueAccessGrantRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *IssueAccessGrantRequest) GetProposal() *AccessGrantProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type IssueAccessGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAccessGrantResponse) Reset() {
	*x = IssueAccessGrantResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAccessGrantResponse) ProtoMessage() {}

func (x *IssueAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*IssueAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *IssueAccessGrantResponse) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type RevokeAccessGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessGrantRequest) Reset() {
	*x = RevokeAccessGrantRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessGrantRequest) ProtoMessage() {}

func (x *RevokeAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*RevokeAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeAccessGrantRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RevokeAccessGrantRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type RevokeAccessGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevocationId  string                 `protobuf:"bytes,1,opt,name=revocation_id,json=revocationId,proto3" json:"revocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessGrantResponse) Reset() {
	*x = RevokeAccessGrantResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessGrantResponse) ProtoMessage() {}

func (x *RevokeAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*RevokeAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeAccessGrantResponse) GetRevocationId() string {
	if x != nil {
		return x.RevocationId
	}
	return ""
}

type ListAccessGrantsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubjectPrincipalId string                 `protobuf:"bytes,1,opt,name=subject_principal_id,json=subjectPrincipalId,proto3" json:"subject_principal_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListAccessGrantsRequest) Reset() {
	*x = ListAccessGrantsRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessGrantsRequest) ProtoMessage() {}

func (x *ListAccessGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListAccessGrantsRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *ListAccessGrantsRequest) GetSubjectPrincipalId() string {
	if x != nil {
		return x.SubjectPrincipalId
	}
	return ""
}

type AccessGrantMetadata struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Id                 string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectPrincipalId string                  `protobuf:"bytes,2,opt,name=subject_principal_id,json=subjectPrincipalId,proto3" json:"subject_principal_id,omitempty"`
	Actions            []string                `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Scope              *protocol.ResourceScope `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	NotBefore          *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter           *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Revoked            bool                    `protobuf:"varint,7,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessGrantMetadata) Reset() {
	*x = AccessGrantMetadata{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessGrantMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGrantMetadata) ProtoMessage() {}

func (x *AccessGrantMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGrantMetadata.ProtoReflect.Descriptor instead.
func (*AccessGrantMetadata) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{19}
}

func (x *AccessGrantMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessGrantMetadata) GetSubjectPrincipalId() string {
	if x != nil {
		return x.SubjectPrincipalId
	}
	return ""
}

func (x *AccessGrantMetadata) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AccessGrantMetadata) GetScope() *protocol.ResourceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AccessGrantMetadata) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *AccessGrantMetadata) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *AccessGrantMetadata) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ListAccessGrantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []*AccessGrantMetadata `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessGrantsResponse) Reset() {
	*x = ListAccessGrantsResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessGrantsResponse) ProtoMessage() {}

func (x *ListAccessGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessGrantsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessGrantsResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{20}
}

func (x *ListAccessGrantsResponse) GetGrants() []*AccessGrantMetadata {
	if x != nil {
		return x.Grants
	}
	return nil
}

type IssueApplicationEnrollmentTicketRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ApplicationPrincipalId string                 `protobuf:"bytes,1,opt,name=application_principal_id,json=applicationPrincipalId,proto3" json:"application_principal_id,omitempty"`
	InitialActions         []string               `protobuf:"bytes,2,rep,name=initial_actions,json=initialActions,proto3" json:"initial_actions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IssueApplicationEnrollmentTicketRequest) Reset() {
	*x = IssueApplicationEnrollmentTicketRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueApplicationEnrollmentTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueApplicationEnrollmentTicketRequest) ProtoMessage() {}

func (x *IssueApplicationEnrollmentTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueApplicationEnrollmentTicketRequest.ProtoReflect.Descriptor instead.
func (*IssueApplicationEnrollmentTicketRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{21}
}

func (x *IssueApplicationEnrollmentTicketRequest) GetApplicationPrincipalId() string {
	if x != nil {
		return x.ApplicationPrincipalId
	}
	return ""
}

func (x *IssueApplicationEnrollmentTicketRequest) GetInitialActions() []string {
	if x != nil {
		return x.InitialActions
	}
	return nil
}

type IssueApplicationEnrollmentTicketResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ApplicationEnrollmentTicket []byte                 `protobuf:"bytes,1,opt,name=application_enrollment_ticket,json=applicationEnrollmentTicket,proto3" json:"application_enrollment_ticket,omitempty"`
	ExpiresAt                   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *IssueApplicationEnrollmentTicketResponse) Reset() {
	*x = IssueApplicationEnrollmentTicketResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueApplicationEnrollmentTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueApplicationEnrollmentTicketResponse) ProtoMessage() {}

func (x *IssueApplicationEnrollmentTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueApplicationEnrollmentTicketResponse.ProtoReflect.Descriptor instead.
func (*IssueApplicationEnrollmentTicketResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{22}
}

func (x *IssueApplicationEnrollmentTicketResponse) GetApplicationEnrollmentTicket() []byte {
	if x != nil {
		return x.ApplicationEnrollmentTicket
	}
	return nil
}

func (x *IssueApplicationEnrollmentTicketResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ImportDelegationRevocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revocation    []byte                 `protobuf:"bytes,1,opt,name=revocation,proto3" json:"revocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDelegationRevocationRequest) Reset() {
	*x = ImportDelegationRevocationRequest{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDelegationRevocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDelegationRevocationRequest) ProtoMessage() {}

func (x *ImportDelegationRevocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDelegationRevocationRequest.ProtoReflect.Descriptor instead.
func (*ImportDelegationRevocationRequest) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{23}
}

func (x *ImportDelegationRevocationRequest) GetRevocation() []byte {
	if x != nil {
		return x.Revocation
	}
	return nil
}

type ImportDelegationRevocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevocationId  string                 `protobuf:"bytes,1,opt,name=revocation_id,json=revocationId,proto3" json:"revocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDelegationRevocationResponse) Reset() {
	*x = ImportDelegationRevocationResponse{}
	mi := &file_api_ardents_v1_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDelegationRevocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDelegationRevocationResponse) ProtoMessage() {}

func (x *ImportDelegationRevocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ardents_v1_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDelegationRevocationResponse.ProtoReflect.Descriptor instead.
func (*ImportDelegationRevocationResponse) Descriptor() ([]byte, []int) {
	return file_api_ardents_v1_identity_proto_rawDescGZIP(), []int{24}
}

func (x *ImportDelegationRevocationResponse) GetRevocationId() string {
	if x != nil {
		return x.RevocationId
	}
	return ""
}

var File_api_ardents_v1_identity_proto protoreflect.FileDescriptor

const file_api_ardents_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/ardents/v1/identity.proto\x12\n" +
	"ardents.v1\x1a'api/ardents/identity/v1/artifacts.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x1aBeginAuthenticationRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12?\n" +
	"\apurpose\x18\x02 \x01(\x0e2%.ardents.identity.v1.ChallengePurposeR\apurpose\"a\n" +
	"\x1bBeginAuthenticationResponse\x12B\n" +
	"\tchallenge\x18\x01 \x01(\v2$.ardents.identity.v1.ChallengeFieldsR\tchallenge\"\xcb\x01\n" +
	"\x1dCompleteAuthenticationRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12&\n" +
	"\x0froot_public_key\x18\x03 \x01(\fR\rrootPublicKey\x12\x1e\n" +
	"\n" +
	"credential\x18\x04 \x01(\fR\n" +
	"credential\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xcc\x01\n" +
	"\x1eCompleteAuthenticationResponse\x12%\n" +
	"\x0esession_secret\x18\x01 \x01(\fR\rsessionSecret\x12)\n" +
	"\x10enrollment_proof\x18\x02 \x01(\fR\x0fenrollmentProof\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xff\x01\n" +
	"\x1bEnrollFirstPrincipalRequest\x12)\n" +
	"\x10bootstrap_ticket\x18\x01 \x01(\fR\x0fbootstrapTicket\x12B\n" +
	"\tchallenge\x18\x02 \x01(\v2$.ardents.identity.v1.ChallengeFieldsR\tchallenge\x12)\n" +
	"\x10enrollment_proof\x18\x03 \x01(\fR\x0fenrollmentProof\x12&\n" +
	"\x0froot_public_key\x18\x04 \x01(\fR\rrootPublicKey\x12\x1e\n" +
	"\n" +
	"credential\x18\x05 \x01(\fR\n" +
	"credential\"A\n" +
	"\x1cEnrollFirstPrincipalResponse\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\"\xee\x01\n" +
	"\x16EnrollPrincipalRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12B\n" +
	"\tchallenge\x18\x02 \x01(\v2$.ardents.identity.v1.ChallengeFieldsR\tchallenge\x12)\n" +
	"\x10enrollment_proof\x18\x03 \x01(\fR\x0fenrollmentProof\x12&\n" +
	"\x0froot_public_key\x18\x04 \x01(\fR\rrootPublicKey\x12\x1e\n" +
	"\n" +
	"credential\x18\x05 \x01(\fR\n" +
	"credential\"<\n" +
	"\x17EnrollPrincipalResponse\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\"t\n" +
	"\x13RevokeDeviceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\";\n" +
	"\x14RevokeDeviceResponse\x12#\n" +
	"\rrevocation_id\x18\x01 \x01(\tR\frevocationId\"A\n" +
	"\x1cListDeviceRevocationsRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\"\xa5\x01\n" +
	"\x18DeviceRevocationMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x129\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"g\n" +
	"\x1dListDeviceRevocationsResponse\x12F\n" +
	"\vrevocations\x18\x01 \x03(\v2$.ardents.v1.DeviceRevocationMetadataR\vrevocations\"\x8f\x02\n" +
	"\x13AccessGrantProposal\x120\n" +
	"\x14subject_principal_id\x18\x01 \x01(\tR\x12subjectPrincipalId\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\x128\n" +
	"\x05scope\x18\x03 \x01(\v2\".ardents.identity.v1.ResourceScopeR\x05scope\x129\n" +
	"\n" +
	"not_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"u\n" +
	"\x17IssueAccessGrantRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\bproposal\x18\x02 \x01(\v2\x1f.ardents.v1.AccessGrantProposalR\bproposal\"5\n" +
	"\x18IssueAccessGrantResponse\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\"T\n" +
	"\x18RevokeAccessGrantRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bgrant_id\x18\x02 \x01(\tR\agrantId\"@\n" +
	"\x19RevokeAccessGrantResponse\x12#\n" +
	"\rrevocation_id\x18\x01 \x01(\tR\frevocationId\"K\n" +
	"\x17ListAccessGrantsRequest\x120\n" +
	"\x14subject_principal_id\x18\x01 \x01(\tR\x12subjectPrincipalId\"\xb9\x02\n" +
	"\x13AccessGrantMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14subject_principal_id\x18\x02 \x01(\tR\x12subjectPrincipalId\x12\x18\n" +
	"\aactions\x18\x03 \x03(\tR\aactions\x128\n" +
	"\x05scope\x18\x04 \x01(\v2\".ardents.identity.v1.ResourceScopeR\x05scope\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x18\n" +
	"\arevoked\x18\a \x01(\bR\arevoked\"S\n" +
	"\x18ListAccessGrantsResponse\x127\n" +
	"\x06grants\x18\x01 \x03(\v2\x1f.ardents.v1.AccessGrantMetadataR\x06grants\"\xb5\x01\n" +
	"'IssueApplicationEnrollmentTicketRequest\x128\n" +
	"\x18application_principal_id\x18\x01 \x01(\tR\x16applicationPrincipalId\x12'\n" +
	"\x0finitial_actions\x18\x02 \x03(\tR\x0einitialActionsJ\x04\b\x03\x10\x04R!replace_current_legacy_credential\"\xa9\x01\n" +
	"(IssueApplicationEnrollmentTicketResponse\x12B\n" +
	"\x1dapplication_enrollment_ticket\x18\x01 \x01(\fR\x1bapplicationEnrollmentTicket\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"C\n" +
	"!ImportDelegationRevocationRequest\x12\x1e\n" +
	"\n" +
	"revocation\x18\x01 \x01(\fR\n" +
	"revocation\"I\n" +
	"\"ImportDelegationRevocationResponse\x12#\n" +
	"\rrevocation_id\x18\x01 \x01(\tR\frevocationId2\x9f\t\n" +
	"\x0fIdentityService\x12f\n" +
	"\x13BeginAuthentication\x12&.ardents.v1.BeginAuthenticationRequest\x1a'.ardents.v1.BeginAuthenticationResponse\x12o\n" +
	"\x16CompleteAuthentication\x12).ardents.v1.CompleteAuthenticationRequest\x1a*.ardents.v1.CompleteAuthenticationResponse\x12i\n" +
	"\x14EnrollFirstPrincipal\x12'.ardents.v1.EnrollFirstPrincipalRequest\x1a(.ardents.v1.EnrollFirstPrincipalResponse\x12Z\n" +
	"\x0fEnrollPrincipal\x12\".ardents.v1.EnrollPrincipalRequest\x1a#.ardents.v1.EnrollPrincipalResponse\x12Q\n" +
	"\fRevokeDevice\x12\x1f.ardents.v1.RevokeDeviceRequest\x1a .ardents.v1.RevokeDeviceResponse\x12l\n" +
	"\x15ListDeviceRevocations\x12(.ardents.v1.ListDeviceRevocationsRequest\x1a).ardents.v1.ListDeviceRevocationsResponse\x12]\n" +
	"\x10IssueAccessGrant\x12#.ardents.v1.IssueAccessGrantRequest\x1a$.ardents.v1.IssueAccessGrantResponse\x12`\n" +
	"\x11RevokeAccessGrant\x12$.ardents.v1.RevokeAccessGrantRequest\x1a%.ardents.v1.RevokeAccessGrantResponse\x12]\n" +
	"\x10ListAccessGrants\x12#.ardents.v1.ListAccessGrantsRequest\x1a$.ardents.v1.ListAccessGrantsResponse\x12\x8d\x01\n" +
	" IssueApplicationEnrollmentTicket\x123.ardents.v1.IssueApplicationEnrollmentTicketRequest\x1a4.ardents.v1.IssueApplicationEnrollmentTicketResponse\x12{\n" +
	"\x1aImportDelegationRevocation\x12-.ardents.v1.ImportDelegationRevocationRequest\x1a..ardents.v1.ImportDelegationRevocationResponseB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var (
	file_api_ardents_v1_identity_proto_rawDescOnce sync.Once
	file_api_ardents_v1_identity_proto_rawDescData []byte
)

func file_api_ardents_v1_identity_proto_rawDescGZIP() []byte {
	file_api_ardents_v1_identity_proto_rawDescOnce.Do(func() {
		file_api_ardents_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ardents_v1_identity_proto_rawDesc), len(file_api_ardents_v1_identity_proto_rawDesc)))
	})
	return file_api_ardents_v1_identity_proto_rawDescData
}

var file_api_ardents_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_ardents_v1_identity_proto_goTypes = []any{
	(*BeginAuthenticationRequest)(nil),               // 0: ardents.v1.BeginAuthenticationRequest
	(*BeginAuthenticationResponse)(nil),              // 1: ardents.v1.BeginAuthenticationResponse
	(*CompleteAuthenticationRequest)(nil),            // 2: ardents.v1.CompleteAuthenticationRequest
	(*CompleteAuthenticationResponse)(nil),           // 3: ardents.v1.CompleteAuthenticationResponse
	(*EnrollFirstPrincipalRequest)(nil),              // 4: ardents.v1.EnrollFirstPrincipalRequest
	(*EnrollFirstPrincipalResponse)(nil),             // 5: ardents.v1.EnrollFirstPrincipalResponse
	(*EnrollPrincipalRequest)(nil),                   // 6: ardents.v1.EnrollPrincipalRequest
	(*EnrollPrincipalResponse)(nil),                  // 7: ardents.v1.EnrollPrincipalResponse
	(*RevokeDeviceRequest)(nil),                      // 8: ardents.v1.RevokeDeviceRequest
	(*RevokeDeviceResponse)(nil),                     // 9: ardents.v1.RevokeDeviceResponse
	(*ListDeviceRevocationsRequest)(nil),             // 10: ardents.v1.ListDeviceRevocationsRequest
	(*DeviceRevocationMetadata)(nil),                 // 11: ardents.v1.DeviceRevocationMetadata
	(*ListDeviceRevocationsResponse)(nil),            // 12: ardents.v1.ListDeviceRevocationsResponse
	(*AccessGrantProposal)(nil),                      // 13: ardents.v1.AccessGrantProposal
	(*IssueAccessGrantRequest)(nil),                  // 14: ardents.v1.IssueAccessGrantRequest
	(*IssueAccessGrantResponse)(nil),                 // 15: ardents.v1.IssueAccessGrantResponse
	(*RevokeAccessGrantRequest)(nil),                 // 16: ardents.v1.RevokeAccessGrantRequest
	(*RevokeAccessGrantResponse)(nil),                // 17: ardents.v1.RevokeAccessGrantResponse
	(*ListAccessGrantsRequest)(nil),                  // 18: ardents.v1.ListAccessGrantsRequest
	(*AccessGrantMetadata)(nil),                      // 19: ardents.v1.AccessGrantMetadata
	(*ListAccessGrantsResponse)(nil),                 // 20: ardents.v1.ListAccessGrantsResponse
	(*IssueApplicationEnrollmentTicketRequest)(nil),  // 21: ardents.v1.IssueApplicationEnrollmentTicketRequest
	(*IssueApplicationEnrollmentTicketResponse)(nil), // 22: ardents.v1.IssueApplicationEnrollmentTicketResponse
	(*ImportDelegationRevocationRequest)(nil),        // 23: ardents.v1.ImportDelegationRevocationRequest
	(*ImportDelegationRevocationResponse)(nil),       // 24: ardents.v1.ImportDelegationRevocationResponse
	(protocol.ChallengePurpose)(0),                   // 25: ardents.identity.v1.ChallengePurpose
	(*protocol.ChallengeFields)(nil),                 // 26: ardents.identity.v1.ChallengeFields
	(*timestamppb.Timestamp)(nil),                    // 27: google.protobuf.Timestamp
	(*protocol.ResourceScope)(nil),                   // 28: ardents.identity.v1.ResourceScope
}
var file_api_ardents_v1_identity_proto_depIdxs = []int32{
	25, // 0: ardents.v1.BeginAuthenticationRequest.purpose:type_name -> ardents.identity.v1.ChallengePurpose
	26, // 1: ardents.v1.BeginAuthenticationResponse.challenge:type_name -> ardents.identity.v1.ChallengeFields
	27, // 2: ardents.v1.CompleteAuthenticationResponse.expires_at:type_name -> google.protobuf.Timestamp
	26, // 3: ardents.v1.EnrollFirstPrincipalRequest.challenge:type_name -> ardents.identity.v1.ChallengeFields
	26, // 4: ardents.v1.EnrollPrincipalRequest.challenge:type_name -> ardents.identity.v1.ChallengeFields
	27, // 5: ardents.v1.DeviceRevocationMetadata.revoked_at:type_name -> google.protobuf.Timestamp
	11, // 6: ardents.v1.ListDeviceRevocationsResponse.revocations:type_name -> ardents.v1.DeviceRevocationMetadata
	28, // 7: ardents.v1.AccessGrantProposal.scope:type_name -> ardents.identity.v1.ResourceScope
	27, // 8: ardents.v1.AccessGrantProposal.not_before:type_name -> google.protobuf.Timestamp
	27, // 9: ardents.v1.AccessGrantProposal.not_after:type_name -> google.protobuf.Timestamp
	13, // 10: ardents.v1.IssueAccessGrantRequest.proposal:type_name -> ardents.v1.AccessGrantProposal
	28, // 11: ardents.v1.AccessGrantMetadata.scope:type_name -> ardents.identity.v1.ResourceScope
	27, // 12: ardents.v1.AccessGrantMetadata.not_before:type_name -> google.protobuf.Timestamp
	27, // 13: ardents.v1.AccessGrantMetadata.not_after:type_name -> google.protobuf.Timestamp
	19, // 14: ardents.v1.ListAccessGrantsResponse.grants:type_name -> ardents.v1.AccessGrantMetadata
	27, // 15: ardents.v1.IssueApplicationEnrollmentTicketResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 16: ardents.v1.IdentityService.BeginAuthentication:input_type -> ardents.v1.BeginAuthenticationRequest
	2,  // 17: ardents.v1.IdentityService.CompleteAuthentication:input_type -> ardents.v1.CompleteAuthenticationRequest
	4,  // 18: ardents.v1.IdentityService.EnrollFirstPrincipal:input_type -> ardents.v1.EnrollFirstPrincipalRequest
	6,  // 19: ardents.v1.IdentityService.EnrollPrincipal:input_type -> ardents.v1.EnrollPrincipalRequest
	8,  // 20: ardents.v1.IdentityService.RevokeDevice:input_type -> ardents.v1.RevokeDeviceRequest
	10, // 21: ardents.v1.IdentityService.ListDeviceRevocations:input_type -> ardents.v1.ListDeviceRevocationsRequest
	14, // 22: ardents.v1.IdentityService.IssueAccessGrant:input_type -> ardents.v1.IssueAccessGrantRequest
	16, // 23: ardents.v1.IdentityService.RevokeAccessGrant:input_type -> ardents.v1.RevokeAccessGrantRequest
	18, // 24: ardents.v1.IdentityService.ListAccessGrants:input_type -> ardents.v1.ListAccessGrantsRequest
	21, // 25: ardents.v1.IdentityService.IssueApplicationEnrollmentTicket:input_type -> ardents.v1.IssueApplicationEnrollmentTicketRequest
	23, // 26: ardents.v1.IdentityService.ImportDelegationRevocation:input_type -> ardents.v1.ImportDelegationRevocationRequest
	1,  // 27: ardents.v1.IdentityService.BeginAuthentication:output_type -> ardents.v1.BeginAuthenticationResponse
	3,  // 28: ardents.v1.IdentityService.CompleteAuthentication:output_type -> ardents.v1.CompleteAuthenticationResponse
	5,  // 29: ardents.v1.IdentityService.EnrollFirstPrincipal:output_type -> ardents.v1.EnrollFirstPrincipalResponse
	7,  // 30: ardents.v1.IdentityService.EnrollPrincipal:output_type -> ardents.v1.EnrollPrincipalResponse
	9,  // 31: ardents.v1.IdentityService.RevokeDevice:output_type -> ardents.v1.RevokeDeviceResponse
	12, // 32: ardents.v1.IdentityService.ListDeviceRevocations:output_type -> ardents.v1.ListDeviceRevocationsResponse
	15, // 33: ardents.v1.IdentityService.IssueAccessGrant:output_type -> ardents.v1.IssueAccessGrantResponse
	17, // 34: ardents.v1.IdentityService.RevokeAccessGrant:output_type -> ardents.v1.RevokeAccessGrantResponse
	20, // 35: ardents.v1.IdentityService.ListAccessGrants:output_type -> ardents.v1.ListAccessGrantsResponse
	22, // 36: ardents.v1.IdentityService.IssueApplicationEnrollmentTicket:output_type -> ardents.v1.IssueApplicationEnrollmentTicketResponse
	24, // 37: ardents.v1.IdentityService.ImportDelegationRevocation:output_type -> ardents.v1.ImportDelegationRevocationResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_identity_proto_init() }
func file_api_ardents_v1_identity_proto_init() {
	if File_api_ardents_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_identity_proto_rawDesc), len(file_api_ardents_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_v1_identity_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_identity_proto_depIdxs,
		MessageInfos:      file_api_ardents_v1_identity_proto_msgTypes,
	}.Build()
	File_api_ardents_v1_identity_proto = out.File
	file_api_ardents_v1_identity_proto_goTypes = nil
	file_api_ardents_v1_identity_proto_depIdxs = nil
}
