// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/retention.proto

package ardentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_ardents_v1_retention_proto protoreflect.FileDescriptor

const file_api_ardents_v1_retention_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/ardents/v1/retention.proto\x12\n" +
	"ardents.v1\x1a\x1aapi/ardents/v1/types.proto2\xdd\x01\n" +
	"\x10RetentionService\x12E\n" +
	"\n" +
	"RetainBlob\x12\x1d.ardents.v1.RetainBlobRequest\x1a\x18.ardents.v1.BlobSnapshot\x12?\n" +
	"\aPinBlob\x12\x1a.ardents.v1.PinBlobRequest\x1a\x18.ardents.v1.BlobSnapshot\x12A\n" +
	"\bDropBlob\x12\x1b.ardents.v1.DropBlobRequest\x1a\x18.ardents.v1.BlobSnapshotB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var file_api_ardents_v1_retention_proto_goTypes = []any{
	(*RetainBlobRequest)(nil), // 0: ardents.v1.RetainBlobRequest
	(*PinBlobRequest)(nil),    // 1: ardents.v1.PinBlobRequest
	(*DropBlobRequest)(nil),   // 2: ardents.v1.DropBlobRequest
	(*BlobSnapshot)(nil),      // 3: ardents.v1.BlobSnapshot
}
var file_api_ardents_v1_retention_proto_depIdxs = []int32{
	0, // 0: ardents.v1.RetentionService.RetainBlob:input_type -> ardents.v1.RetainBlobRequest
	1, // 1: ardents.v1.RetentionService.PinBlob:input_type -> ardents.v1.PinBlobRequest
	2, // 2: ardents.v1.RetentionService.DropBlob:input_type -> ardents.v1.DropBlobRequest
	3, // 3: ardents.v1.RetentionService.RetainBlob:output_type -> ardents.v1.BlobSnapshot
	3, // 4: ardents.v1.RetentionService.PinBlob:output_type -> ardents.v1.BlobSnapshot
	3, // 5: ardents.v1.RetentionService.DropBlob:output_type -> ardents.v1.BlobSnapshot
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_retention_proto_init() }
func file_api_ardents_v1_retention_proto_init() {
	if File_api_ardents_v1_retention_proto != nil {
		return
	}
	file_api_ardents_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_retention_proto_rawDesc), len(file_api_ardents_v1_retention_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_v1_retention_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_retention_proto_depIdxs,
	}.Build()
	File_api_ardents_v1_retention_proto = out.File
	file_api_ardents_v1_retention_proto_goTypes = nil
	file_api_ardents_v1_retention_proto_depIdxs = nil
}
