// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: api/ardents/v1/transfer.proto

package ardentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_ardents_v1_transfer_proto protoreflect.FileDescriptor

const file_api_ardents_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/ardents/v1/transfer.proto\x12\n" +
	"ardents.v1\x1a\x1aapi/ardents/v1/types.proto2\xd8\x02\n" +
	"\x0fTransferService\x12C\n" +
	"\tFetchBlob\x12\x1c.ardents.v1.FetchBlobRequest\x1a\x18.ardents.v1.BlobSnapshot\x12Z\n" +
	"\x0fListBlobSources\x12\".ardents.v1.ListBlobSourcesRequest\x1a#.ardents.v1.ListBlobSourcesResponse\x12N\n" +
	"\vGetTransfer\x12\x1e.ardents.v1.GetTransferRequest\x1a\x1f.ardents.v1.GetTransferResponse\x12T\n" +
	"\rListTransfers\x12 .ardents.v1.ListTransfersRequest\x1a!.ardents.v1.ListTransfersResponseB.Z,ardents/internal/localapi/protocol;ardentsv1b\x06proto3"

var file_api_ardents_v1_transfer_proto_goTypes = []any{
	(*FetchBlobRequest)(nil),        // 0: ardents.v1.FetchBlobRequest
	(*ListBlobSourcesRequest)(nil),  // 1: ardents.v1.ListBlobSourcesRequest
	(*GetTransferRequest)(nil),      // 2: ardents.v1.GetTransferRequest
	(*ListTransfersRequest)(nil),    // 3: ardents.v1.ListTransfersRequest
	(*BlobSnapshot)(nil),            // 4: ardents.v1.BlobSnapshot
	(*ListBlobSourcesResponse)(nil), // 5: ardents.v1.ListBlobSourcesResponse
	(*GetTransferResponse)(nil),     // 6: ardents.v1.GetTransferResponse
	(*ListTransfersResponse)(nil),   // 7: ardents.v1.ListTransfersResponse
}
var file_api_ardents_v1_transfer_proto_depIdxs = []int32{
	0, // 0: ardents.v1.TransferService.FetchBlob:input_type -> ardents.v1.FetchBlobRequest
	1, // 1: ardents.v1.TransferService.ListBlobSources:input_type -> ardents.v1.ListBlobSourcesRequest
	2, // 2: ardents.v1.TransferService.GetTransfer:input_type -> ardents.v1.GetTransferRequest
	3, // 3: ardents.v1.TransferService.ListTransfers:input_type -> ardents.v1.ListTransfersRequest
	4, // 4: ardents.v1.TransferService.FetchBlob:output_type -> ardents.v1.BlobSnapshot
	5, // 5: ardents.v1.TransferService.ListBlobSources:output_type -> ardents.v1.ListBlobSourcesResponse
	6, // 6: ardents.v1.TransferService.GetTransfer:output_type -> ardents.v1.GetTransferResponse
	7, // 7: ardents.v1.TransferService.ListTransfers:output_type -> ardents.v1.ListTransfersResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ardents_v1_transfer_proto_init() }
func file_api_ardents_v1_transfer_proto_init() {
	if File_api_ardents_v1_transfer_proto != nil {
		return
	}
	file_api_ardents_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ardents_v1_transfer_proto_rawDesc), len(file_api_ardents_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ardents_v1_transfer_proto_goTypes,
		DependencyIndexes: file_api_ardents_v1_transfer_proto_depIdxs,
	}.Build()
	File_api_ardents_v1_transfer_proto = out.File
	file_api_ardents_v1_transfer_proto_goTypes = nil
	file_api_ardents_v1_transfer_proto_depIdxs = nil
}
