package stage6verify

var expectedCells = []expectedCell{
	{"A0", "canonical name and Service Link", "canonical", "canonical-name"},
	{"A1", "invalid canonical forms and bounds", "invalid-input", "invalid-name"},
	{"A2", "initial claim and exact resolution", "resolved", "initial-resolution"},
	{"A3", "Active and Grace renewal", "renewed", "renewal"},
	{"A4", "expiry Release and reclaim", "released-reclaimed", "reclaim"},
	{"A5", "parent delegation lifecycle", "parent-bounded", "parent-lineage"},
	{"B0", "authority rotation", "rotated", "authority-rotation"},
	{"B1", "authority transfer", "transferred", "authority-transfer"},
	{"B2", "Recovery Policy mutation", "policy-activated", "recovery-policy"},
	{"B3", "authorized recovery", "recovery-completed", "authorized-recovery"},
	{"B4", "insufficient recovery authorization", "recovery-policy-absent", "recovery-denial"},
	{"B5", "old authority policy and replay", "stale-proof", "authority-replay"},
	{"C0", "same Target migration", "same-target", "same-target"},
	{"C1", "replacement Target", "target-replaced", "target-replacement"},
	{"C2", "name-origin connection update", "connection-closed", "name-origin-close"},
	{"C3", "direct Target naming change", "direct-pinned", "direct-target"},
	{"C4", "concurrent ordered claims", "ordered-collision", "claim-order"},
	{"C5", "unprovable concurrent order", "state-conflict", "claim-conflict"},
	{"C6", "copy withholding rollback equivocation", "unavailable", "claim-hostile"},
	{"C7", "bounded anonymous pressure", "admission-denied", "admission-bounds"},
	{"D0", "resolver knowledge split", "role-separated", "resolution-roles"},
	{"D1", "entry hiding and Rendezvous restriction", "query-hidden", "query-hiding"},
	{"D2", "private naming control path", "control-separated", "control-roles"},
	{"D3", "Isolation Context separation", "context-separated", "context-separation"},
	{"D4", "invalid private path", "unavailable", "no-fallback"},
	{"D5", "stale cache and lineage replay", "stale-proof", "stale-lineage"},
	{"D6", "incompatible Namespace rule", "fork-unresolved", "namespace-fork"},
}
