package record

import (
	"crypto/ed25519"
	"encoding/binary"
	"encoding/hex"
	"errors"
)

const (
	signedRecordSchema        uint16 = 1
	maximumRecordPayloadBytes        = 1_846
	maximumSignedRecordBytes         = maximumRecordPayloadBytes + 2 + 8 + ed25519.SignatureSize
	recordDomain                     = "ardents-name-record-v1"
)

// RecordSigner owns one Authority private-key operation. Namespace gives it a
// sealed request containing the exact transcript and expected Authority, never
// a caller-constructible lifecycle Record.
type RecordSigner interface {
	Sign(RecordSigningRequest) ([]byte, error)
}

// RecordSigningRequest is the opaque exact-signature request generated by
// Namespace. It exposes only the retained Record transcript and Authority key.
type RecordSigningRequest struct {
	authority  [ed25519.PublicKeySize]byte
	generation uint64
	revision   uint64
	recordWire []byte
	transcript []byte
}

// SignWith seals one derived Record through its Authority signing port.
func SignWith(network [32]byte, value Record, signer RecordSigner) ([]byte, error) {
	if signer == nil {
		return nil, errors.New("name record signer is unavailable")
	}
	request, err := newRecordSigningRequest(network, value)
	if err != nil {
		return nil, err
	}
	signature, err := signer.Sign(request)
	if err != nil {
		return nil, err
	}
	return request.seal(signature)
}

// Authority returns the exact public key that must verify the signature.
func (request RecordSigningRequest) Authority() [ed25519.PublicKeySize]byte {
	return request.authority
}

// Successor returns the exact Record generation and revision being signed.
func (request RecordSigningRequest) Successor() (uint64, uint64) {
	return request.generation, request.revision
}

// Transcript returns a copy of the exact retained signing transcript.
func (request RecordSigningRequest) Transcript() []byte {
	return append([]byte(nil), request.transcript...)
}

func newRecordSigningRequest(network [32]byte, record Record) (RecordSigningRequest, error) {
	if network == [32]byte{} {
		return RecordSigningRequest{}, errors.New("name record signing identity is invalid")
	}
	public, err := canonicalAuthority(record.Authority)
	if err != nil {
		return RecordSigningRequest{}, errors.New("name record Authority is invalid")
	}
	recordWire, err := EncodeRecord(record)
	if err != nil || len(recordWire) > maximumRecordPayloadBytes {
		return RecordSigningRequest{}, errors.New("name record cannot be signed")
	}
	request := RecordSigningRequest{generation: record.Generation, revision: record.Revision,
		recordWire: append([]byte(nil), recordWire...), transcript: recordTranscript(network, recordWire)}
	copy(request.authority[:], public)
	return request, nil
}

func (request RecordSigningRequest) seal(signature []byte) ([]byte, error) {
	if len(request.recordWire) == 0 || len(request.transcript) == 0 || len(signature) != ed25519.SignatureSize ||
		!ed25519.Verify(ed25519.PublicKey(request.authority[:]), request.transcript, signature) {
		return nil, errors.New("name record signature is invalid")
	}
	out := make([]byte, 0, 2+8+len(request.recordWire)+len(signature))
	out = binary.BigEndian.AppendUint16(out, signedRecordSchema)
	out = binary.BigEndian.AppendUint64(out, uint64(len(request.recordWire)))
	out = append(out, request.recordWire...)
	return append(out, signature...), nil
}

// SignRecord signs one canonical Record for exactly one network and returns a
// strict self-contained container. The Record Authority must be the lowercase
// hexadecimal public half of private.
func SignRecord(network [32]byte, record Record, private ed25519.PrivateKey) ([]byte, error) {
	if len(private) != ed25519.PrivateKeySize {
		return nil, errors.New("name record signing identity is invalid")
	}
	request, err := newRecordSigningRequest(network, record)
	if err != nil {
		return nil, err
	}
	public := private[ed25519.SeedSize:]
	var signer [ed25519.PublicKeySize]byte
	copy(signer[:], public)
	if request.authority != signer {
		return nil, errors.New("name record Authority does not match signer")
	}
	signature := ed25519.Sign(private, request.transcript)
	if !ed25519.Verify(ed25519.PublicKey(public), request.transcript, signature) {
		return nil, errors.New("name Authority private key is inconsistent")
	}
	return request.seal(signature)
}

// VerifyRecord authenticates and decodes one exact signed Record container.
func VerifyRecord(network [32]byte, signed []byte) (Record, error) {
	if network == [32]byte{} || len(signed) < 2+8+ed25519.SignatureSize || len(signed) > maximumSignedRecordBytes {
		return Record{}, errors.New("signed name record is malformed")
	}
	if binary.BigEndian.Uint16(signed[:2]) != signedRecordSchema {
		return Record{}, errors.New("signed name record schema is invalid")
	}
	size := binary.BigEndian.Uint64(signed[2:10])
	if size == 0 || size > maximumRecordPayloadBytes || size != uint64(len(signed)-10-ed25519.SignatureSize) {
		return Record{}, errors.New("signed name record length is invalid")
	}
	recordWire := signed[10 : 10+int(size)]
	signature := signed[10+int(size):]
	record, err := DecodeRecord(recordWire)
	if err != nil {
		return Record{}, errors.New("signed name record contains an invalid Record")
	}
	public, err := canonicalAuthority(record.Authority)
	if err != nil || !ed25519.Verify(public, recordTranscript(network, recordWire), signature) {
		return Record{}, errors.New("name record signature is invalid")
	}
	return record, nil
}

func canonicalAuthority(raw string) (ed25519.PublicKey, error) {
	decoded, err := hex.DecodeString(raw)
	if err != nil || len(decoded) != ed25519.PublicKeySize || hex.EncodeToString(decoded) != raw {
		return nil, errors.New("name Authority is not a canonical Ed25519 key")
	}
	return ed25519.PublicKey(decoded), nil
}

// AuthorityKey decodes one canonical Record Authority public key.
func AuthorityKey(raw string) (ed25519.PublicKey, error) { return canonicalAuthority(raw) }

func recordTranscript(network [32]byte, record []byte) []byte {
	out := make([]byte, 0, 2+len(recordDomain)+32+8+len(record))
	out = binary.BigEndian.AppendUint16(out, uint16(len(recordDomain)))
	out = append(out, recordDomain...)
	out = append(out, network[:]...)
	out = binary.BigEndian.AppendUint64(out, uint64(len(record)))
	return append(out, record...)
}
