// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ardents/application/v1/identity.proto

package applicationv1connect

import (
	applicationv1 "ardents/internal/applicationapi/protocol/applicationv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "ardents.application.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceBeginAuthenticationProcedure is the fully-qualified name of the IdentityService's
	// BeginAuthentication RPC.
	IdentityServiceBeginAuthenticationProcedure = "/ardents.application.v1.IdentityService/BeginAuthentication"
	// IdentityServiceCompleteAuthenticationProcedure is the fully-qualified name of the
	// IdentityService's CompleteAuthentication RPC.
	IdentityServiceCompleteAuthenticationProcedure = "/ardents.application.v1.IdentityService/CompleteAuthentication"
	// IdentityServiceEnrollApplicationProcedure is the fully-qualified name of the IdentityService's
	// EnrollApplication RPC.
	IdentityServiceEnrollApplicationProcedure = "/ardents.application.v1.IdentityService/EnrollApplication"
)

// IdentityServiceClient is a client for the ardents.application.v1.IdentityService service.
type IdentityServiceClient interface {
	BeginAuthentication(context.Context, *connect.Request[applicationv1.BeginAuthenticationRequest]) (*connect.Response[applicationv1.BeginAuthenticationResponse], error)
	CompleteAuthentication(context.Context, *connect.Request[applicationv1.CompleteAuthenticationRequest]) (*connect.Response[applicationv1.CompleteAuthenticationResponse], error)
	EnrollApplication(context.Context, *connect.Request[applicationv1.EnrollApplicationRequest]) (*connect.Response[applicationv1.EnrollApplicationResponse], error)
}

// NewIdentityServiceClient constructs a client for the ardents.application.v1.IdentityService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := applicationv1.File_api_ardents_application_v1_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		beginAuthentication: connect.NewClient[applicationv1.BeginAuthenticationRequest, applicationv1.BeginAuthenticationResponse](
			httpClient,
			baseURL+IdentityServiceBeginAuthenticationProcedure,
			connect.WithSchema(identityServiceMethods.ByName("BeginAuthentication")),
			connect.WithClientOptions(opts...),
		),
		completeAuthentication: connect.NewClient[applicationv1.CompleteAuthenticationRequest, applicationv1.CompleteAuthenticationResponse](
			httpClient,
			baseURL+IdentityServiceCompleteAuthenticationProcedure,
			connect.WithSchema(identityServiceMethods.ByName("CompleteAuthentication")),
			connect.WithClientOptions(opts...),
		),
		enrollApplication: connect.NewClient[applicationv1.EnrollApplicationRequest, applicationv1.EnrollApplicationResponse](
			httpClient,
			baseURL+IdentityServiceEnrollApplicationProcedure,
			connect.WithSchema(identityServiceMethods.ByName("EnrollApplication")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	beginAuthentication    *connect.Client[applicationv1.BeginAuthenticationRequest, applicationv1.BeginAuthenticationResponse]
	completeAuthentication *connect.Client[applicationv1.CompleteAuthenticationRequest, applicationv1.CompleteAuthenticationResponse]
	enrollApplication      *connect.Client[applicationv1.EnrollApplicationRequest, applicationv1.EnrollApplicationResponse]
}

// BeginAuthentication calls ardents.application.v1.IdentityService.BeginAuthentication.
func (c *identityServiceClient) BeginAuthentication(ctx context.Context, req *connect.Request[applicationv1.BeginAuthenticationRequest]) (*connect.Response[applicationv1.BeginAuthenticationResponse], error) {
	return c.beginAuthentication.CallUnary(ctx, req)
}

// CompleteAuthentication calls ardents.application.v1.IdentityService.CompleteAuthentication.
func (c *identityServiceClient) CompleteAuthentication(ctx context.Context, req *connect.Request[applicationv1.CompleteAuthenticationRequest]) (*connect.Response[applicationv1.CompleteAuthenticationResponse], error) {
	return c.completeAuthentication.CallUnary(ctx, req)
}

// EnrollApplication calls ardents.application.v1.IdentityService.EnrollApplication.
func (c *identityServiceClient) EnrollApplication(ctx context.Context, req *connect.Request[applicationv1.EnrollApplicationRequest]) (*connect.Response[applicationv1.EnrollApplicationResponse], error) {
	return c.enrollApplication.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the ardents.application.v1.IdentityService
// service.
type IdentityServiceHandler interface {
	BeginAuthentication(context.Context, *connect.Request[applicationv1.BeginAuthenticationRequest]) (*connect.Response[applicationv1.BeginAuthenticationResponse], error)
	CompleteAuthentication(context.Context, *connect.Request[applicationv1.CompleteAuthenticationRequest]) (*connect.Response[applicationv1.CompleteAuthenticationResponse], error)
	EnrollApplication(context.Context, *connect.Request[applicationv1.EnrollApplicationRequest]) (*connect.Response[applicationv1.EnrollApplicationResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := applicationv1.File_api_ardents_application_v1_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceBeginAuthenticationHandler := connect.NewUnaryHandler(
		IdentityServiceBeginAuthenticationProcedure,
		svc.BeginAuthentication,
		connect.WithSchema(identityServiceMethods.ByName("BeginAuthentication")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceCompleteAuthenticationHandler := connect.NewUnaryHandler(
		IdentityServiceCompleteAuthenticationProcedure,
		svc.CompleteAuthentication,
		connect.WithSchema(identityServiceMethods.ByName("CompleteAuthentication")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceEnrollApplicationHandler := connect.NewUnaryHandler(
		IdentityServiceEnrollApplicationProcedure,
		svc.EnrollApplication,
		connect.WithSchema(identityServiceMethods.ByName("EnrollApplication")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ardents.application.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceBeginAuthenticationProcedure:
			identityServiceBeginAuthenticationHandler.ServeHTTP(w, r)
		case IdentityServiceCompleteAuthenticationProcedure:
			identityServiceCompleteAuthenticationHandler.ServeHTTP(w, r)
		case IdentityServiceEnrollApplicationProcedure:
			identityServiceEnrollApplicationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) BeginAuthentication(context.Context, *connect.Request[applicationv1.BeginAuthenticationRequest]) (*connect.Response[applicationv1.BeginAuthenticationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.application.v1.IdentityService.BeginAuthentication is not implemented"))
}

func (UnimplementedIdentityServiceHandler) CompleteAuthentication(context.Context, *connect.Request[applicationv1.CompleteAuthenticationRequest]) (*connect.Response[applicationv1.CompleteAuthenticationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.application.v1.IdentityService.CompleteAuthentication is not implemented"))
}

func (UnimplementedIdentityServiceHandler) EnrollApplication(context.Context, *connect.Request[applicationv1.EnrollApplicationRequest]) (*connect.Response[applicationv1.EnrollApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ardents.application.v1.IdentityService.EnrollApplication is not implemented"))
}
