package daemon

const (
	apiTokenEnv                 = "ARDENTS_API_TOKEN"
	apiTokenFileEnv             = "ARDENTS_API_TOKEN_FILE"
	nodeNameEnv                 = "ARDENTS_NODE_NAME"
	dataDirEnv                  = "ARDENTS_DATA_DIR"
	storePathEnv                = "ARDENTS_WAKU_STORE_PATH"
	bootstrapPeersEnv           = "ARDENTS_BOOTSTRAP_PEERS"
	trustAnchorsEnv             = "ARDENTS_TRUST_ANCHORS"
	transportProfileEnv         = "ARDENTS_TRANSPORT_PROFILE"
	transportPortEnv            = "ARDENTS_TRANSPORT_PORT"
	nodeProfileEnv              = "ARDENTS_NODE_PROFILE"
	wssPortEnv                  = "ARDENTS_WSS_PORT"
	wssCertPathEnv              = "ARDENTS_WSS_CERT_PATH"
	wssKeyPathEnv               = "ARDENTS_WSS_KEY_PATH"
	wssCAPathEnv                = "ARDENTS_WSS_CA_PATH"
	wssAdvertiseEnv             = "ARDENTS_WSS_ADVERTISE_ADDRESS"
	dnsDiscoveryURLsEnv         = "ARDENTS_DNS_DISCOVERY_URLS"
	dnsNameServerEnv            = "ARDENTS_DNS_DISCOVERY_NAMESERVER"
	reachabilityModeEnv         = "ARDENTS_REACHABILITY_MODE"
	advertiseAddrsEnv           = "ARDENTS_ADVERTISE_ADDRESSES"
	maxMessageBytesEnv          = "ARDENTS_MAX_NETWORK_MESSAGE_BYTES"
	maxPeerConnsEnv             = "ARDENTS_MAX_PEER_CONNECTIONS"
	maxConnsPerIPEnv            = "ARDENTS_MAX_CONNECTIONS_PER_IP"
	maxNetworkOpsEnv            = "ARDENTS_MAX_NETWORK_CONCURRENCY"
	networkRateEnv              = "ARDENTS_NETWORK_OPERATION_RATE"
	networkBurstEnv             = "ARDENTS_NETWORK_OPERATION_BURST"
	maxFilterSubsEnv            = "ARDENTS_MAX_FILTER_SUBSCRIBERS"
	maxStoreResultsEnv          = "ARDENTS_MAX_STORE_RESULTS"
	workloadExecutorEnv         = "ARDENTS_WORKLOAD_EXECUTOR"
	workloadRegistriesEnv       = "ARDENTS_WORKLOAD_ALLOWED_REGISTRIES"
	workloadPolicyRefsEnv       = "ARDENTS_WORKLOAD_ALLOWED_POLICY_REFS"
	workloadTrustedRuntimeEnv   = "ARDENTS_WORKLOAD_TRUSTED_RUNTIME"
	workloadUntrustedRuntimeEnv = "ARDENTS_WORKLOAD_UNTRUSTED_RUNTIME"
	operatorConfigFileEnv       = "ARDENTS_CONFIG_FILE"
)
